### ISSUE TITLE
Number type (int vs. double) in Sampler

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#1003]
--------
Issue Description
--------
Putting an integer value in a custom constructed grid sampler leads to a code crash (indicating a type error) during the construction of the grid.

Integers should be recast as doubles in the proper places in the code. This was no issue in Python 2, but showed-up after the conversion to Python 3.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __No, the code will crash.__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
I think this issue is related to #973

**Comment by alfoa** [comment]
I can not replicate the error... can you attach an input file?

**Comment by wangcj05** [comment]
In my machine, I have changed the test test_Grid_Sampler.xml line 59 to integers, and I got the similar errors as mentioned in #973  @alfoa 
```
      <variable name="VarGauss1">
        <distribution>Gauss1</distribution>
        <grid construction="custom" type="value">0 1 2</grid>
      </variable>
```

**Comment by wangcj05** [comment]
The test is located under tests/framework/test_Grid_Sampler.xml @alfoa

**Comment by PaulTalbot-INL** [comment]
Approved to close via #1008. No user-facing email needed, as this resulted in a crash and is not of general concern.
