### ISSUE TITLE
ROM should check the inputs sent to it and compare it to the required ones, then give an appropriate error.

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1027]
--------
Issue Description
--------
##### What did you expect to see happen?
When multi running the rom, a history set with defined inputs and outputs was sent to the rom as an input, the error was not descriptive at all.
<img width="1154" alt="Screen Shot 2019-08-06 at 8 33 45 AM" src="https://user-images.githubusercontent.com/52417034/62549267-6c319400-b825-11e9-9973-04f51710eca0.png">
I would expect one of two:

1) Either the rom gives an error to the user saying outputs should not be predetermined. Please use a dummy set/output Place Holder.

2) Or the ROM can be smart enough to only extract what it needs and ignore the rest. (Might not be the best option).

It worth mentioning that this error was not generated when DMD was used as the ROM.
##### What did you see instead?
Error: 'In evaluate request for feature REP_PCT_a: The list type is allowed for dynamic ROMS only'

##### Do you have a suggested fix for the development team?
A check should be added preferably in ROM.py to compare the given dictionary with the expected inputs for the ROM.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
__crash, no wrong results__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@Jimmy-INL do we have an input to test?
