### ISSUE TITLE
Raven installation

### ISSUE THREAD

**Issue by petersondroogh** [idaholab/raven#1054]
--------
Issue Description
--------
##### What did you expect to see happen?

git submodule update --init to work
##### What did you see instead?

base) INL607951:raven petejl$ git submodule update --init
Submodule 'plugins/CashFlow' (git@hpcgitlab.inl.gov:epinas/CashFlow.git) registered for path 'plugins/CashFlow'
Cloning into '/Users/petejl/raven/plugins/CashFlow'...
The authenticity of host 'hpcgitlab.inl.gov (141.221.75.201)' can't be established.
ECDSA key fingerprint is SHA256:rfSK90i3++xq5gTvzGsLnLvEuVICZAMgBvZzb7f9YEY.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'hpcgitlab.inl.gov' (ECDSA) to the list of known hosts.
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@hpcgitlab.inl.gov:epinas/CashFlow.git' into submodule path '/Users/petejl/raven/plugins/CashFlow' failed
Failed to clone 'plugins/CashFlow'. Retry scheduled
Cloning into '/Users/petejl/raven/plugins/CashFlow'...
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@hpcgitlab.inl.gov:epinas/CashFlow.git' into submodule path '/Users/petejl/raven/plugins/CashFlow' failed
Failed to clone 'plugins/CashFlow' a second time, aborting

##### Do you have a suggested fix for the development team?

it might be because I do not have access to those repositories

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Hi Peter,
In the installation wiki page we say to run the git submodule --init just in case you have access to a particular RAVEN PlugIn (e.g. CashFlow). Did you find this command anywhere else? I think it might be a defect of the documentation somewhere.

**Comment by petersondroogh** [comment]
In the raven_user_manual it does not have any specify that the git submodule is an option and not required.  Also on the website https://raven.inl.gov/SitePages/Code.aspx it shows it as a step and not an option.  The wiki does describe it much better however the wiki was rather difficult to get to.  I would recommend having a link for the wiki on your website and updating both the manual and website with the new directions.  

The code was able to compile without this step and I am running the test right now.  Thanks,

**Comment by wangcj05** [comment]
I believe this can be closed.
