### ISSUE TITLE
RAVEN Plugins and RAVEN Runners

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1055]
--------
Issue Description
--------
I created this issue for the design meeting on Sept. 26, 2019 regarding the list of things that we need to do:

1. Clear definition of RAVEN plugins and RAVEN runners, NQA documentations regarding the changes in both plugins and runners. Clear statement regarding the responsibilities from the NQA point of view.  -- Andrea

2. Documents regarding how to create plugins and runners, the strategies/steps that how to integrate with current regression test system, as well as regression test structures.  (RAVEN teams)

3. Developer guide for the NQA documentations for plugins and runners -- Andrea

4. Developer guide for using rook as regression test system  -- Josh

5. CI issues (HPC teams): first, enable the deploy key to resolve access right issue; second, estimation of labors, third, user guide as well as "Teams"

6. Strategies for plugin and runners extra libraries. -- Congjian and Paul

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Hello @PaulTalbot-INL @joshua-cogliati-inl @alfoa @mandd, I have created this issue to keep track of the this problem, and I have listed several things that we need to do. Please update the list or provide comments for today's meeting. @PaulTalbot-INL could you attach the pictures of the discussion to this issue.

**Comment by PaulTalbot-INL** [comment]
![IMG_20190926_110031](https://user-images.githubusercontent.com/2044370/65716775-0d3a0f80-e05d-11e9-989c-04472a9b1a40.jpg)
![IMG_20190926_112447](https://user-images.githubusercontent.com/2044370/65716776-0dd2a600-e05d-11e9-8f97-d41c0df4aae5.jpg)
![MVIMG_20190926_113505](https://user-images.githubusercontent.com/2044370/65716778-0dd2a600-e05d-11e9-9098-dead832b0910.jpg)
![MVIMG_20190926_121031](https://user-images.githubusercontent.com/2044370/65716779-0dd2a600-e05d-11e9-83f7-bb40387aa788.jpg)
