### ISSUE TITLE
Workshop Issues (Rome 2019)

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1060]
--------
Issue Description
--------
These are issues/feature requests discovered in the Rome 2019 workshop. They should be categorized and split into specific issues WHEN a developer is acting on resolving a part of them.

- The Windows install is almost impossible on a slow internet connection due to the size of Visual Studio. At minimum, having a copy on a pen drive to distribute might help resolve this; we've found participants hesitant to try installing before coming in roughly 50% of participants.

- Examples in workshop slides don't use the "bash.exe" for Windows users. Either an alias function should be set up at the beginning of the workshop, or something similar, so that all users are able to run the same commands.
- If examples include a plot output, including that plot in the slides helps participants know if they got the "right" result.
- the Grid sampler CDF from 0 to 90 in 90 steps (should have been 0 to 0.9) caused RAVEN to exit prematurely and not register an error (no new samples).
- Outstream Plot on an empty dataobject causes an error that is deep in python and not clear at all.
- Changing libraries within the week before starting the workshop caused issues for many participants, as they had to git pull to see the fresh slides, but this broke their installations. Recommend not changing libraries in the week before a workshop.
- The code coupling presentation continues to be difficult for users to follow. No good suggestion on how to improve this, although perhaps instead of coupling a new code they could "couple" a code through the generic interface?
- The ROMs currently has a low-value set of exercises; a guided tour through the kinds of data that ROMs can capture well could be much better. Perhaps a "competition" to play with ROMs and parameters to minimize a pre-written metric by hand? Perhaps surrogates for common physics (neutronics, TH, severe accident, economics, etc)?
- The exercise instruction slides are great, but you can't do stuff on your laptop while showing them. Proving handouts with the exercise instructions instead would free up the projector.
- Static data mining should start with the projectile, then move to other, more interesting algorithms, as the projectile does not provide interesting clustering.
- For the DataMining PostProcessor family, the user should be *required* to provide a "label" name, not defaulted; the default leads to significant confusion in participants.
- The DataMining "init_params" are old in the manual (e.g. wc doesn't exist anymore in GMM)
- Add "Motivation" slides in the beginning of presentations that connect how a particular class of users might use the features highlighted in that session (e.g. different types of codes or use cases)
- For postprocessors, if the input DataObject is empty the postprocessor shouldn't try to run, and should give a useful message; right now it passes through frequently with no warning and successive steps fail or work in unexpected ways.
- Apparently tidle (~) cannot be written on an Italian keyboard. Who knew?
- Perhaps when running RAVEN via the command prompt (or powershell), everything should start with a "bash.exe" call first to set the environment.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@idaholab/raven-team can we parse these issues and see which ones are still applicable?
