### ISSUE TITLE
METADATA in Interfaced PP - Missing 

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#1065]
--------
Issue Description
--------
##### What did you expect to see happen?

To be able to run 2 multiple Interfaced PP in sequence...

##### What did you see instead?

`
(  549.13 sec) SIMULATION               : Message         -> -- Beginning step SensPost_1 of type: PostProcess                   --

(  549.13 sec) STEP SINGLERUN           : Message         -> ***  Beginning initialization ***

(  549.13 sec) STEP SINGLERUN           : DEBUG           -> jobHandler initialized

(  549.13 sec) STEP SINGLERUN           : DEBUG           -> for the role Model  the item of class PostProcessor   and name SensPost        has been initialized

(  549.13 sec) STEP SINGLERUN           : DEBUG           -> for the role Output the item of class HistorySet      and name Synchronized_History has been initialized

(  549.13 sec) STEP SINGLERUN           : DEBUG           -> for the role Output the item of class OutStreamPrint  and name Sync_FileOut    has been initialized

(  549.13 sec) STEP SINGLERUN           : Message         -> ***    Initialization done    ***

(  549.13 sec) STEP SINGLERUN           : Message         -> ***       Beginning run       ***

(  549.13 sec) HistorySet               : Warning         -> DataObject._convertToDict can be a slow operation and should be avoided where possible!

(  643.71 sec) PostProcessor            : DEBUG           -> InterfacedPostProcessor Post-Processor SensPost : start to run

Exception in thread generalOut:

Traceback (most recent call last):

  File "/home/stryg/.conda/envs/raven_libraries/lib/python3.7/threading.py", line 926, in _bootstrap_inner

    self.run()

  File "/home/stryg/.conda/envs/raven_libraries/lib/python3.7/threading.py", line 870, in run

    self._target(*self._args, **self._kwargs)

  File "/home/stryg/raven/framework/Runners/SharedMemoryRunner.py", line 136, in <lambda>

    self.thread = InterruptibleThread(target = lambda q, *arg : q.append(self.functionToRun(*arg)),

  File "/home/stryg/raven/framework/Models/PostProcessor.py", line 184, in evaluateSample

    returnValue = (Input, self.interface.run(Input))

  File "/home/stryg/raven/framework/PostProcessors/InterfacedPostProcessor.py", line 151, in run

    outputDic = self.postProcessor.run(inputDic)

  File "/home/stryg/raven/framework/PostProcessorFunctions/HistorySetSync.py", line 143, in run

    outputDic['data']['ProbabilityWeight'] = inputDic['data']['ProbabilityWeight']

KeyError: 'ProbabilityWeight'

 

(  680.02 sec) Job Handler              : Message         ->  Process Failed <Runners.SharedMemoryRunner.SharedMemoryRunner object at 0x7f5cb8cfb7d0> internal returnCode -1

(  680.02 sec) STEP SINGLERUN           : DEBUG           -> the job "generalOut" has failed.

(  680.02 sec) STEP SINGLERUN           : Warning         -> There were 1 failed runs!

(  680.02 sec) STEP SINGLERUN           : Message         -> ***       Run finished        ***

(  680.02 sec) STEP SINGLERUN           : Message         -> ***     Closing the step      ***

(  680.02 sec) STEP SINGLERUN           : Message         -> ***        Step closed        ***

(  680.04 sec) SIMULATION               : Message         -> -- End step SensPost_1 of type: PostProcess                    --

 

(  680.04 sec) SIMULATION               : Message         -> -- Beginning step io_data of type: IOStep                           --

(  680.04 sec) STEP IOCOMBINED          : Message         -> ***  Beginning initialization ***

(  680.04 sec) STEP IOCOMBINED          : DEBUG           -> jobHandler initialized

(  680.04 sec) STEP IOCOMBINED          : DEBUG           -> for the role Output the item of class OutStreamPrint  and name FileOut         has been initialized

(  680.06 sec) STEP IOCOMBINED          : DEBUG           -> for the role Output the item of class OutStreamPlot   and name MyPlot2         has been initialized

(  680.06 sec) STEP IOCOMBINED          : Message         -> ***    Initialization done    ***

(  680.06 sec) STEP IOCOMBINED          : Message         -> ***       Beginning run       ***

(  680.06 sec) HistorySet               : DEBUG           -> Printing data to CSV: "FileOut.csv"

(  916.29 sec) HistorySet               : DEBUG           -> Printing metadata XML: "FileOut.xml"

(  970.83 sec) OUTSTREAM PLOT           : DEBUG           -> creating plotMyPlot2

(  973.87 sec) STEP IOCOMBINED          : Message         -> ***       Run finished        ***

(  973.87 sec) STEP IOCOMBINED          : Message         -> ***     Closing the step      ***

(  973.87 sec) STEP IOCOMBINED          : Message         -> ***        Step closed        ***

(  973.87 sec) SIMULATION               : Message         -> -- End step io_data of type: IOStep   
`
##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@mandd

**Comment by wangcj05** [comment]
checklists are good, since this defect will cause the code raising an error, an email to the users is optional
