### ISSUE TITLE
[DEFECT] Coverage broken

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1076]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
Coverage tests run

##### What did you see instead?
0 tests found for coverage

##### Do you have a suggested fix for the development team?
Pathing issue introduced by #1056 should be fixed

**Describe how to Reproduce**
1. run coverage check
2. see lack of tests discovered

**Platform (please complete the following information):**
 - OS: OSX
 - Version: 10.12
 - Dependencies Installation: conda

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
No notification needed as coverage is not a designed user interaction.

**Comment by alfoa** [comment]
Closure check list is passed...

No email is required since the defect affects the creation of the coverage information only and does not affect any user.
