### ISSUE TITLE
[DEFECT] Raven will not produce the required csv if the number of failures description lines exceed 200 

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1082]
--------
1000 runs of relap are expected to have about 10% of failed runs, this might cause the parser not to find the run complete statement in the last 200 lines which prevents it from proceeding.
--------

**Describe the defect**
there should be a smarter way of dumping errors, or create a different log.
##### What did you expect to see happen?
I expected the output csv to be produced.

##### What did you see instead?
Nothing was produced.
##### Do you have a suggested fix for the development team?
I removed the 200 lines limit of the search in the RAVEN parser.

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
From what I understand, this is the RAVEN code interface issue, where we use the last handful of lines from the code run to determine whether the run was a success or failure; however, especially on the HPC, the error and warning prints at the end of the file might be long enough that we don't detect a successful run.

Potential fixes are to use RAVEN's return code to determine failure/success, and possibly assure that we exit with a meaningful return code depending on how the step finishes. For example, MonteCarlo with missing samples isn't a failure necessarily, while Grid with missing samples is.

**Comment by alfoa** [comment]
Checklist passed. 
Closure approved via #1409
