### ISSUE TITLE
Coverage not running Topology UI

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#1085]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
The coverage tool should be able to check coverage in the Topology UI

##### What did you see instead?
The coverage is missing in that UI.

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1.  cd <RAVEN/>tests/framework/PostProcessors/TopologicalPostProcessor
2. raven_framework test_topology_ui.xml interactiveCheck
and watch it fail
3. cd <RAVEN/>tests/framework/PostProcessors/DataMiningPostProcessor/Clustering
4. raven_framework hierarchical_ui.xml interactiveCheck
and watch it fail.

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: Fedora 30
 - Version: f40a8edd60e4d5f3f47e83af4013e0efddf56ebf
 - Dependencies Installation: Conda

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
The defect is in the regtression test system (mostly for the coverage).
 No user email is required.

Approved closure via #1086
