### ISSUE TITLE
[DEFECT] Heavy Test Skip

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1089]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
All heavy tests should run 

##### What did you see instead?
Currently, the test heavy is green but some tests are not running due to duplicated files.
```
[incorrect test] duplicated files specified: tests/framework/user_guide/ReducedOrderModeling/ROMConstruction/1-historyPlot_scatter-scatter.png tests/framework/user_guide/ReducedOrderModeling/ROMConstruction/1-samplesPlot3DROMgp_scatter-scatter.png tests/framework/user_guide/ReducedOrderModeling/ROMConstruction/1-samplesPlot3DROMinverse_scatter-scatter.png tests/framework/user_guide/ReducedOrderModeling/ROMConstruction/1-samplesPlot3DROMsvm_scatter-scatter.png tests/framework/user_guide/ReducedOrderModeling/ROMConstruction/1-samplesPlot3D_scatter-scatter.png
(682/719) Skipped(  None!  )tests/framework/user_guide/ReducedOrderModeling/ROMConstruction
[incorrect test] duplicated files specified: tests/framework/user_guide/AdaptiveSamplingStrategies/LSsearch/1-historyPlot_line-line-line-line.png tests/framework/user_guide/AdaptiveSamplingStrategies/LSsearch/1-samplesPlot3D_scatter-scatter.png tests/framework/user_guide/AdaptiveSamplingStrategies/LSsearch/1-limitSurfacePlot_scatter.png
(683/719) Skipped(  None!  )tests/framework/user_guide/AdaptiveSamplingStrategies/limitSurfaceSearch
[incorrect test] duplicated files specified: tests/framework/user_guide/DataMining/dataMiningAnalysis/1-PlotKMeans1_dataMining-dataMining.png tests/framework/user_guide/DataMining/dataMiningAnalysis/1-PlotLabels_dataMining.png tests/framework/user_guide/DataMining/dataMiningAnalysis/1-PlotPCA1_dataMining.png
```
##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. Just check the test heavy in the civet regression test system.

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __have no impact on users__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
@wangcj05 Hm, I don't see "duplicated files specified" is the output for a recent heavy test.  Can this be closed?
https://civet.inl.gov/job/495105/
Thanks.

**Comment by wangcj05** [comment]
@joshua-cogliati-inl These tests are skipped now because PIL is not available.

**Comment by joshua-cogliati-inl** [comment]
@wangcj05 Okay, I'll check with PIL installed.  Thanks.

**Comment by wangcj05** [comment]
@alfoa Do we need to enforce the installation of pillow on the regression machines? Currently, some heavy tests are skipped because PIL is not available.

**Comment by alfoa** [comment]
@wangcj05 yes we need.
Josh can you modify the civet recipes for doing so?

**Comment by alfoa** [comment]
Closure checklist passed...

**Comment by joshua-cogliati-inl** [comment]
> @wangcj05 yes we need.
> Josh can you modify the civet recipes for doing so?

The heavy tests already have --optional.
