### ISSUE TITLE
[DEFECT] Cannot Sample Multiple RELAP5 Variables on the Same Line

### ISSUE THREAD

**Issue by heagysa** [idaholab/raven#1103]
--------
Defect Description
--------
I created a RAVEN sample that would perform the same sampling for multiple variables on a single RELAP5 line and it did not perform the correct sampling and caused the calculation to abort.

RAVEN xml input line of interest:
      <variable name="7290102:1,7290102:2">

RELAP5 input line of interest:
7290102 0.0  0.0          1000

##### What did you expect to see happen?
I expected RAVEN to sample the first and second RELAP5 variables consistently on the line of interest.  

##### What did you see instead?
The code aborted with a non-descriptive error message.

##### Do you have a suggested fix for the development team?
Traceback (most recent call last):
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/Driver.py", line 285, in <module>
    raven()
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/Driver.py", line 238, in raven
    simulation.run()
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/Simulation.py", line 780, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/Steps.py", line 315, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/Steps.py", line 640, in _localTakeAstepRun
    myLambda([finishedJob,outputs[outIndex]])
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/Steps.py", line 588, in <lambda>
    self._outputCollectionLambda.append( (lambda x: inDictionary['Model'].collectOutput(x[0],x[1]), outIndex) )
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/Models/Code.py", line 738, in collectOutput
    self.raiseAnError(AttributeError,"No available Output to collect")
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/MessageHandler.py", line 99, in raiseAnError
    self.messageHandler.error(self,etype,msg,str(tag),verbosity,color)
  File "/home/cgosdin/RAVEN_FPS/RAVEN_FPS/framework/MessageHandler.py", line 313, in error
    raise etype(message)
AttributeError: No available Output to collect

**Describe how to Reproduce**
1.  Unzip file
2. Rerun Raven

**Screenshots and Input Files**
Attached a zip file of the directory where the calculation was executed.
[Multiple_Variables_Same_Line.zip](https://github.com/idaholab/raven/files/3859016/Multiple_Variables_Same_Line.zip)

**Platform (please complete the following information):**
 
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP4
Release:        12.4
Codename:       n/a

 - Dependencies Installation: CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Impact to users is only a crash, so no notification required.

Approved to close via #1118
