### ISSUE TITLE
[DEFECT] ensemble model indexMap is destructive process

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1119]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
When using an EnsembleModel and ND data with multiple output DataSets, the order of the output data sets shouldn't matter.

##### What did you see instead?
The output works as expected for the first DataSet; the second does not receive the `_indexMap` metavariable.

##### Do you have a suggested fix for the development team?
Check for destructive dictionary actions in the index map creation, perhaps, during output collection

**Describe how to Reproduce**
1. Write a MultiRun using a model producing ND data that is stored in two different output DataSets
2. Run it

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Found this same bug trying to output dispatch results for HERON.

**Comment by PaulTalbot-INL** [comment]
Hit this again; due to the fact output collection is buried in a lambda function, it's challenging to trace. No realistic user could possibly guess the right order of outputs to prevent this from happening.

**Comment by alfoa** [comment]
Closure checklist passed...

Closure approved via #1450

**Comment by alfoa** [comment]
No email is required since this issue could just cause a crash and not wrong results.
