### ISSUE TITLE
Multirun printing performance degradation

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#112]
--------
Issue Description
--------
##### What did you expect to see happen?
linear printing time

##### What did you see instead?
degradation of printing to csv time

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
```xml  
   <MultiRun name="MCrun" pauseAtEnd="True">
      <Input          class="DataObjects"   type="PointSet">SET_ARMAprice_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_dispatch_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_CashFlowPreP_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_CashFlow_in</Input>
      <Model          class="Models"        type="EnsembleModel">MyEnsemble</Model>
      <Sampler        class="Samplers"      type="MonteCarlo">DYMOLA_MC</Sampler>
      <Output         class="DataObjects"   type="PointSet">SET_All_out</Output>
      <Output         class="DataObjects"   type="PointSet">SET_IRR_out</Output>
      <Output         class="OutStreams"    type="Print">dumpAll</Output> 
    </MultiRun>
```

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by mandd** [comment]
This is not really an issue: just print on file using an IO step after having generated the dataObject.

**Comment by PaulTalbot-INL** [comment]
To be fair, it should be reasonably possible for us to append to a CSV with additional points instead of rewriting it entirely each time.  It would make this a more linear printing process.

**Comment by alfoa** [comment]
We generally suggests to use the IOStep to print out the results after the completion of an analysis.

We should identify why the degradation is not linear as we would expect.
