### ISSUE TITLE
[TASK] Allowing Callable kernels to Gaussian Process Regressors

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1124]
--------
Currently, the Gaussian Process Regressor uses a default kernel which is (1.0 RBF (1.0)), but it does not allow the user to specify any basic or callable kernels.
--------

**Is your feature request related to a problem? Please describe.**
This will frustrate a lot of users since the default kernel can perform really badly in several physical problems. For instance, if the target is not normally distributed this might lead to horrible predictions for any new testing points even within the training space (same bounds and distributions).

**Describe the solution you'd like**
It would be great if the basic kernels such as 'Constant', 'White', and more importantly the 'Matern' kernels are implemented.
In addition, a user-defined/callable kernel capability can be really useful.

**Describe alternatives you've considered**
SVR in RAVEN allows for few kernels but it does not allow for callable kernels, unlike SciKitLearn.
Other ROMS might have the same problem.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users' group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with a release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
I think this can be closed with PR#1607
