### ISSUE TITLE
[DEFECT] Relap5 Interface Minor Edit mis-collection

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#1143]
--------
Defect Description
--------

**Describe the defect**
The user reported a mis-collection of the results from RELAP5 in case of a warning injected
by the RELAP5 code at the end of the minor edits.

##### What did you expect to see happen?
The RELAP5 interface to work.

##### What did you see instead?
A failure of the interface in collection data

##### Do you have a suggested fix for the development team?
Fix the parser.

**Describe how to Reproduce**
1.  Introduce in the output file of RELAP5 the following strings at the end of a MINOR EDIT block:
`0Reflood calculation became suspect at timehy = 2.52388E+04 because the code did not allocate enough storage for the axial
nodes required for this transient; storage can not be increased by input data or jcl change, but the number of axial nodes can.
0 nmy =       161 iglrfl(ih) =       159 numbers of axial    nodes are ... 
           2           2           4          16           8           8           8           8
           8           8           8           8           8           8           8           8
           8           8           8           8           8
 Reducing time step due to max number of repeats                584470
 Reducing time step due to max number of repeats                588786`

**Screenshots and Input Files**
N/A

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Any
 - Version: [e.g. 22] Latest
 - Dependencies Installation: [CONDA or PIP] CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@alfoa Please propose an email and send to the user for the fix.
