### ISSUE TITLE
[DEFECT] Create a module for RAVEN Errors

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#1166]
--------
Defect Description
--------

Most of the RAVEN model entities use the Runners.Error exception to check for Errors
from model evaluations. Even if this approach is correct, it causes a slow down of parallelization and importing of such modules because it requires the import of each Runner subclass (and/or pickling) since the Runners are   defined in the __init__ class 

##### What did you expect to see happen?
Fast import and parallel

##### What did you see instead?

Slow down of import and parallel
##### Do you have a suggested fix for the development team?
Create a module where the RAVEN errors are defined (Runners Error, Sampler Errors, etc.)

**Describe how to Reproduce**
1. Import the plugins
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@wangcj05 @PaulTalbot-INL @mandd

**Comment by PaulTalbot-INL** [comment]
I like this idea; I have some Sampler errors and Optimizer errors that are local to their __init__ files, and these could easily be relocated.

**Comment by alfoa** [comment]
I tagged this also as a task...because it is not really a "defect" but more a task
