### ISSUE TITLE
[DEFECT] RELAP5 interface restart function failure

### ISSUE THREAD

**Issue by JarrettDValeri** [idaholab/raven#1185]
--------
Defect Description
--------
When attempting to execute a RELAP5 restart in an ensemble model, I am getting the following error in RAVEN:
 
_RuntimeError: The Model  RELAPtr identified by RELAPtr++1 failed!_
 
And the RELAP5 error is:
 
_Open failure number       29 on file restrt                                                                          , perhaps file is not available.
RELAP5-3D: Errors detected during input processing._
 
It seems like it is having issues obtaining the output from SS.  I can confirm that the SS is running to completion and providing a restrt file, as expected.  Prior to an update pulled on 3/20/20, the restart functionality had been working correctly.  The RAVEN XML input files were not changed between when it was working and when it stopped working.

##### What did you expect to see happen?

I expected that the restart would run, as it had previously.

##### What did you see instead?

An error trying to obtain the restart file.

##### Do you have a suggested fix for the development team?

No.

**Describe how to Reproduce**
1.  Unzip the input folder (this is attached in the FPoli RISA JIRA board)
2. You will have to add your own rellic.bin file and tpfh2o file
3. Edit the executable locations for RELAP5 (there are 2, one in the RELAPss "code" and one in the RELAPtr "code")
4. Execute RAVEN pointing to the RISA_raven.xml file.

**Screenshots and Input Files**
Input files are attached in the FPoli RISA JIRA board

**Platform (please complete the following information):**
 - OS/Version: SUSE Linux Enterprise Server 12, Patch Level 4
 - Dependencies Installation: default RAVEN

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
@alfoa, does this cause incorrect runs in a way that we should notify users?
