### ISSUE TITLE
[TASK] ROM Clustering improvement  

### ISSUE THREAD

**Issue by JiaZhou-PU** [idaholab/raven#1199]
--------
Issue Description
--------

Improvements that are needed in ROM clustering.
In addition to #913 

 - [ ] ROM selection:  User should be able to specify the method for selecting on which data point in each cluster, this data point should be a sufficient representation of the clustered data.

The current evaluation after clustering is taking the first data point in the cluster as the cluster typical point. This might lead to all data points in the same cluster represented by an unnormal point if we believe there is a wide variation in the cluster itself. 

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
can you add a test case here?

**Comment by JiaZhou-PU** [comment]
> can you add a test case here?

After fixing it? Or just case prove it use the same point from the cluster?

**Comment by alfoa** [comment]
I mean, can you indicate which test should be used to test the capability?  (in tests/framework/etc.etc.)

**Comment by alfoa** [comment]
Closure checklist passed and approved via #1218
