### ISSUE TITLE
Remove Crow submodule from manual

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#12]
--------
Issue Description
--------
##### What did you expect to see happen?
The install manual would not mention crow.

##### What did you see instead?
Things like:
```
git submodule update --init moose crow
```
##### Do you have a suggested fix for the development team?
Fix the manual

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? ***improvement***
- [x] 2. Is it tagged with a priority: critical, normal or minor? ***normal***
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***n/a***
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. ***n/a***
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***yes***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***improvement***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) ***improvement***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***improvement***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***improvement***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***#23***

**Comment by joshua-cogliati-inl** [comment]
Also, the .gitmodules still includes relap-7 and crow.

**Comment by alfoa** [comment]
This one probably should have been closed by PR #23
