### ISSUE TITLE
[TASK] Restructure HybridModel class 

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1202]
--------
Issue Description
--------

A new model entity "LogicalModel" will be implemented. The LogicalModel utilizes control functions or fault tree/event tree to manage the selection and execution of different models (i.e. ExternalModel, ROMs, Codes). Both LogicalModel and current HybridModel share some common functionalities. In this case, a new base class will be created for both entities. First, we are planing to restructure the HybridModel entity, and create the base class for it. Second, after the restructure, the LogicalModel entity will be created. In addition, since HybridModel and EnsembleModel entities also share some common functionalities when interact with models. A common module to handle the interactions with models will also be created. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@alfoa @PaulTalbot-INL @mandd Please take a look at this issue, and all comments are really appreciated.

**Comment by PaulTalbot-INL** [comment]
This looks consistent with our team discussions to me. I like the idea of a "model handler helper" entity more than trying to build it into any of the base classes 👍

**Comment by alfoa** [comment]
Closure checklist passed...

Closure approved via #1232
