### ISSUE TITLE
[DEFECT] Suddenly Raven Cannot Run (Error Message "Missing python modules: ...")

### ISSUE THREAD

**Issue by fmax85** [idaholab/raven#1224]
--------
Defect Description
--------

**Describe the defect**
I am running Raven on Ubuntu 18.04 for sens/unc analysis on Relap5 models. I have installed all the required packages as described the guidelines.
I could run my simulations until two weeks ago, but yesterday I failed to run new simulations (or reproduce old ones) as I got an error message stating that python modules were missing, in particular: xarray, netcdf4, statsmodels, tensorflow, pyside2, numexpr.

I tried to delete raven and re-install it but it fails to pass the tests (see log [raven_test.log](https://github.com/idaholab/raven/files/4529076/raven_test.log)).

##### What did you expect to see happen?
I can use the code normally.

##### What did you see instead?
Despite the required libraries are installed (attached the [raven_lib_install.log](https://github.com/idaholab/raven/files/4529075/raven_lib_install.log) of the library installation during re-install of Raven), Raven cannot run and reports missing libraries (xarray, statsmodels, etc.).

##### Do you have a suggested fix for the development team?
No.

**Describe how to Reproduce**
1. execute `raven_framework` on any xml input file (see [raven_execution.log](https://github.com/idaholab/raven/files/4529101/raven_execution.log) attached).
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - Version: 18.04
 - Dependencies Installation: CONDA (anaconda3)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
We are not able to replicate the error. Please let us know if you experience sitll the same problem
