### ISSUE TITLE
[TASK] Add Operations on Sampled Variables for More Codes

### ISSUE THREAD

**Issue by JarrettDValeri** [idaholab/raven#1231]
--------
Issue Description
--------

I would often like to perform math operations on a sampled variable before insertion into the code input file.  Although this can be accomplished with a Python pre-processor, this can be a bit burdensome and necessitates significant complication of the RAVEN input.

The RELAP5 code interface has an existing implementation of an elegant solution, which is the use of the operator XML node.  This allows the user to specify operations using sampled variables and the existing inputs on input file cards to produce new inputs.  This is useful in scenarios such as sampling a multiplier on existing inputs.

If possible, generic implementation of the operator XML node for more codes would be helpful.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@JarrettDValeri: I think "Functions" can be used to perform the task, for example:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/7321071/204583130-6e4d529b-f44c-4844-9388-823aa94894a4.png">

Please reopen this issue if you think the "Functions" can not resolve your issue.
