### ISSUE TITLE
[TASK] Hierarchical Fourier Detrending

### ISSUE THREAD

**Issue by dhill2522** [idaholab/raven#1242]
--------
Issue Description
--------

The ARMA modeling with Fourier detrending and segmenting seems quite effective, but an idea has come up that may help improve its performance for certain signals.

The synthetic samples generated by an ARMA model often appear more jagged than their original counterparts. With some experimentation, it becomes apparent that longer segmenting in the training step increases the smoothness of the samples. The increase in sample smoothness with increasing segment length is likely due to longer segments allowing more frequencies to be trained on the segments rather than just on the global level. Unfortunately this is not always an option as longer segments fail to capture the varying dynamics at different points in time.

Enabling a multi-level or hierarchical fourier detrending could allow the longer Fourier frequencies to be detrended both on the global and segment level.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
archived
