### ISSUE TITLE
[TASK] _indexMap for all histories

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1256]
--------
Issue Description
--------

Currently, if a realization contains multiple independent indices on which sampled variables depend, a special meta key `_indexMap` is provided that determines the mapping between dimensions of the sampled variable and the names of the corresponding indices.

However, if a realization only depends on a single index (or `pivotParameter`), there is no information in the realization to indicate what the index variable is, and which variables depend on it.

For consistency of use within RAVEN and other ExternalModels, this should be fixed so the `pivotParameter` can be inquired.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed...

**Comment by alfoa** [comment]
Closure approved via #1257
