### ISSUE TITLE
[DEFECT] Updating Plugins issue

### ISSUE THREAD

**Issue by mandd** [idaholab/raven#1258]
Defect Description

**Describe the defect**

##### What did you expect to see happen?
Background info: I wanted to update RAVEN, libraries and plugins
Performed steps:
1. scripts/establish_conda_env.sh –install
2. ./build_raven
3. scripts/install_plugins.py -a

##### What did you see instead?

[mandd][~/projects/raven]> scripts/install_plugins.py -a
Initializing plugin "CashFlow"
 ... initializing plugin submodule CashFlow ...
 ... plugin located at "/Users/mandd/projects/raven/plugins/CashFlow" ...
Initializing plugin "SR2ML"
 ... initializing plugin submodule SR2ML ...
 ...plugin located at "/Users/mandd/projects/raven/plugins/SR2ML" ...
Initializing plugin "LOGOS"
 ... initializing plugin submodule LOGOS ...
 ... plugin located at "/Users/mandd/projects/raven/plugins/LOGOS" ...
Initializing plugin "SRAW"
 ... initializing plugin submodule SRAW ...
 ... plugin located at "/Users/mandd/projects/raven/plugins/SRAW" ...
Initializing plugin "heron"
 ... initializing plugin submodule heron ...
 ... plugin located at "/Users/mandd/projects/raven/plugins/heron" ...
Initializing plugin "PRAplugin"
 ... initializing plugin submodule PRAplugin ...
 ... plugin located at "/Users/mandd/projects/raven/plugins/PRAplugin" ...
Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/Users/mandd/projects/raven/plugins/ExamplePlugin" ...
Installing plugins ...
 ... plugin "CashFlow" path created as "/Users/mandd/projects/raven/plugins/CashFlow" ...
 ... plugin "CashFlow" informed of RAVEN at "/Users/mandd/projects/raven/framework"...
 ... plugin "CashFlow" succesfully installed!
Traceback (most recent call last):
  File "scripts/install_plugins.py", line 137, in <module>
    match = pluginHandler.updatePluginXML(root, name, plugDir)
  File "/Users/mandd/projects/raven/scripts/plugin_handler.py", line 102, in updatePluginXML
    match = root.findall('./plugin/name[.=\'{}\']/..'.format(name))[0]
  File "/Users/mandd/miniconda2/lib/python2.7/xml/etree/ElementTree.py", line 390, in findall
    return ElementPath.findall(self, path, namespaces)
  File "/Users/mandd/miniconda2/lib/python2.7/xml/etree/ElementPath.py", line 293, in findall
    return list(iterfind(elem, path, namespaces))
  File "/Users/mandd/miniconda2/lib/python2.7/xml/etree/ElementPath.py", line 263, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/Users/mandd/miniconda2/lib/python2.7/xml/etree/ElementPath.py", line 224, in prepare_predicate
    raise SyntaxError("invalid predicate"
SyntaxError: invalid predicate

##### Do you have a suggested fix for the development team?

After several attempt to fix the issue, I found that after removing the old file plugin_directory.xml (see belo) in plugins folder,
the command scripts/install_plugins.py -a successfully update the plugins.

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
I believe this issue has been fixed in the past, I have tested on my Mac machine, and I do not see the error anymore.
