### ISSUE TITLE
failed run 

### ISSUE THREAD

**Issue by lhj12** [idaholab/raven#1279]
--------
Defect Description
--------
modified command to 'C:\\Users\\lhj\\Desktop\\Case1\\relap5.exe -i Case1.i -o out~Case1.o -r out~Case1.r  '
 Process Failed C:\Users\lhj\Desktop\Case1\relap5.exe -i Case1.i -o out~Case1.o -r out~Case1.r   returnCode -1
I don't know why there are returnCOde -1 when I running multi-case, and I don't know how do it.
my run xml file is relap5_multi_run.xml(here is relap5_multi_run.txt), my log file is relap5_multi_run_log.txt and RELAP5 run file is Case1.i(here is Case1.txt)
##### Do you have a suggested fix for the development team?
no

**Describe how to Reproduce**
1. [
[relap5_multi_run_log.txt](https://github.com/idaholab/raven/files/4916162/relap5_multi_run_log.txt)
[Case1.txt](https://github.com/idaholab/raven/files/4916177/Case1.txt)
[relap5_multi_run.txt](https://github.com/idaholab/raven/files/4916179/relap5_multi_run.txt)

](url)
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
I think the issue is related to Relap5.
