### ISSUE TITLE
[DEFECT] Basic Statistics Test "general" is unstable for Win 

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1281]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
Test should stable for different OS. 

##### What did you see instead?
The conditional number for the test is very large. 
```
(    3.48 sec) PostProcessor            : Warning         -> Condition Number: 26745.6986 > 30.0. Detected SEVERE multicollinearity problem. Sensitivity might be incorrect!
 
(    3.48 sec) PostProcessor            : Warning         -> Condition Number: 10478814343750130.0000 > 30.0. Detected SEVERE multicollinearity problem. Sensitivity might be incorrect!
 
(    3.48 sec) PostProcessor            : Warning         -> Condition Number: 10512499860924012.0000 > 30.0. Detected SEVERE multicollinearity problem. Sensitivity might be incorrect!
 
(    3.48 sec) PostProcessor            : Warning         -> Condition Number: 26745.6986 > 30.0. Detected SEVERE multicollinearity problem. Sensitivity might be incorrect!
```

##### Do you have a suggested fix for the development team?

I think the test is made for highly correlated inputs and outputs. The model looks like as follows:
 
Inputs: x0, y0
Outputs: x01, y02
Model: x01 = x01 + 1.0, y02 = y0
 
My suggestion for the fix is to disable the ''multipleFeatures''
**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
This test is a requirement test. As Chair of the COB I approve the change.

This test is a defect (small discrepancies in the windows machine) but it is related to the high collinearity that the code already warns the user about. No email is required.

**Comment by alfoa** [comment]
Closure checklist passed...

Closure approved via #1282
