### ISSUE TITLE
[DEFECT] establish conda fails if no python outside of conda

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#1284]
--------
Defect Description
--------

If the only python is inside of conda, then deactivating will cause there to be no python:

201 Preparing transaction: ...working... done
202 Verifying transaction: ...working... done
203 Executing transaction: ...working... done
204 Remove all packages in environment /home/cogljj/miniconda3/envs/raven_libraries:
205 ... Installing libraries ...
206 ./scripts/establish_conda_env.sh: line 115: python: command not found
207 ... conda command:
208 ... Installing libraries from conda-forge ...
209 ./scripts/establish_conda_env.sh: line 120: python: command not found
210 ... conda-forge command:
211 ... Activating environment ...
212 Could not find conda environment: raven_libraries
213 You can list all discoverable environments with `conda info --envs`.

##### What did you expect to see happen?
establish conda to find the python.

##### What did you see instead?
Above error messages.

##### Do you have a suggested fix for the development team?
Reactivate base conda.

**Describe how to Reproduce**
1.  Run establish conda on a computer that has no python (except for the one in conda)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Currently, this issue affects the regression test machine. This may also affect the other users, but we do not get any report. @joshua-cogliati-inl  I think it depends on you if you want to send out an email or not.
