### ISSUE TITLE
[TASK] Improvement of Assembler Object 

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1290]
--------
Issue Description
--------

Currently, there are several redundant handling in the Assembler object, and there are two different ways for other entities to add and retrieve Assembler objects. In addition, the `newXmlFlg` for `requiredAssObject` should be added for each individual new object. Current structure is: 
![image](https://user-images.githubusercontent.com/7321071/88837205-2cca2900-d195-11ea-9fcd-86aa2fc6d30d.png)

We may need to change it to  
`self.requiredAssObject = [(False, [], [])]`

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
@wangcj05 I agree that the Assembler Object could use some rework.  I am not entirely sure what is needed to satisfy this task however.
I have already been working on the Assembler object (see https://github.com/idaholab/raven/pull/1255/files#diff-8a303190b5f548e99f0e08f4d2e82223 ) 
Can you provide a bit more detail as to what needs to be done to close this task?

**Comment by joshua-cogliati-inl** [comment]
I propose changing it to:
```self._requiredAsmbObject = (False, [], [])```
I also propose changing:

- '-1' to InputData.Quantity.zero_to_one
- '1' to InputData.Quantity.one
- '-n' to InputData.Quantity.zero_to_infinity
- 'n' to InputData.Quanity.one_to_infinity

so it is easier to switch to InputData in the future.

I propose that addAssemblerObject take two parameters, the name and the quantity, and the quantity should be an InputData.Quantity. I also propose having other classes use addAssemblerObject instead of directly accessing the variable.

**Comment by alfoa** [comment]
I like the InputData quantity idea.
Regarding the _requiredAsmbObject, In order to address this, should not add the "requirement" of reading from the data for each possible object we request ?

**Comment by joshua-cogliati-inl** [comment]
> Regarding the _requiredAsmbObject, In order to address this, should not add the "requirement" of reading from the data for each possible object we request ?

I don't understand this sentence.

**Comment by alfoa** [comment]
@joshua-cogliati-inl I edited the post...sorry ehhee

**Comment by joshua-cogliati-inl** [comment]
Hm, right now _requiredAsmbObject[0] is just used to decided if the rest of   _requiredAsmbObject should be used or not.  I think it could probably be replaced with a check if the len() of the names was greater than zero.  The below code seems to work:
```
diff --git a/framework/Assembler.py b/framework/Assembler.py
index 3d395fac2..11aea4257 100644
--- a/framework/Assembler.py
+++ b/framework/Assembler.py
@@ -130,7 +130,7 @@ class Assembler(MessageHandler.MessageUser):
       self.verbosity = xmlNode.attrib['verbosity'].lower()
     #XXX Once InputData checks numbers of subnodes, everything in this
     # if block can be removed
-    if self.requiredAssObject[0]:
+    if len(self.requiredAssObject[1][0]) > 0:
       testObjects = {}
       for token in self.requiredAssObject[1][0]:
         testObjects[token] = 0
```

**Comment by wangcj05** [comment]
> I propose changing it to:
> `self._requiredAsmbObject = (False, [], [])`
> I also propose changing:
> 
> * '-1' to InputData.Quantity.zero_to_one
> * '1' to InputData.Quantity.one
> * '-n' to InputData.Quantity.zero_to_infinity
> * 'n' to InputData.Quanity.one_to_infinity
> 
> so it is easier to switch to InputData in the future.
> 
> I propose that addAssemblerObject take two parameters, the name and the quantity, and the quantity should be an InputData.Quantity. I also propose having other classes use addAssemblerObject instead of directly accessing the variable.

Hi Josh, I think what you proposed is good. The original purpose of the issue is to address the boolean flag in `requiredAssObject'. If you can also address the second part that you proposed that would be great (having other classes use addAssemblerObject instead of directly accessing the variable, i.e. Samplers).

**Comment by joshua-cogliati-inl** [comment]
I think I am done working on the pull request for the time being (I suppose testObjects should be renamed numberObjects in Assembler).  I am not sure that it addresses the boolean flag problem, however there is no code that currently really tests that so I am not sure how to code it properly.  The code is now shorter and hopefully more understandable.

**Comment by joshua-cogliati-inl** [comment]
Before closing this, generateAllAssemblers in Simulation.py needs to be looked at.
