### ISSUE TITLE
Strange results in Ubuntu 16.04

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#13]
--------
Issue Description
--------
##### What did you expect to see happen?
More normal Sensitivities.
[input.zip](https://github.com/idaholab/raven/files/882367/input.zip)

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
The output does not seem to have the issue when I tested on Unbunt 16.04
[output.zip](https://github.com/idaholab/raven/files/882402/output.zip)

```
raven@raven-VirtualBox:~/raven$ ./run_tests --library-report
PYTHONPATH=/home/raven/raven/framework/contrib:
PATH=/home/raven/bin:/home/raven/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Python Executable:  /usr/bin/python
Possible Python Executables on System:
/usr/bin/python3.5
/usr/bin/python
/usr/bin/python3
/usr/bin/python2.7
/usr/bin/python2
OS: Linux-4.8.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
Python: 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
Git information:
34a1b4f343a13b91bc9f05df927bdff934e205f8 Sat, 25 Mar 2017 16:29:15 -0600
fatal: No names found, cannot describe anything.
 5896f1fc7c5942d5202c78ff6b3d39208d65bbbf moose (C++03_final-2728-g5896f1f)

Libraries report:

numpy 1.11.0 
 <module 'numpy' from '/usr/lib/python2.7/dist-packages/numpy/__init__.pyc'>
 

h5py 2.6.0 
 <module 'h5py' from '/usr/lib/python2.7/dist-packages/h5py/__init__.pyc'>
 

scipy 0.17.0 
 <module 'scipy' from '/usr/lib/python2.7/dist-packages/scipy/__init__.pyc'>
scipy has version 0.17.0 but tested version is 0.17.1 

sklearn 0.17 
 <module 'sklearn' from '/usr/lib/python2.7/dist-packages/sklearn/__init__.pyc'>
sklearn has version 0.17 but tested version is 0.17.1 

matplotlib 1.5.1 
 <module 'matplotlib' from '/usr/lib/python2.7/dist-packages/matplotlib/__init__.pyc'>
 

AMSC  
 <module 'AMSC' from '/home/raven/raven/framework/contrib/AMSC/__init__.py'>
 

distribution1D 
 <module 'crow_modules.distribution1Dpy2' from '/home/raven/raven/crow/install/crow_modules/distribution1Dpy2.pyc'>

interpolationND 
 <module 'crow_modules.interpolationNDpy2' from '/home/raven/raven/crow/install/crow_modules/interpolationNDpy2.pyc'>
```

**Comment by joshua-cogliati-inl** [comment]
I noticed this in the original library report that caused this issue:
```
numpy 1.11.1
 <module 'numpy' from '/usr/local/lib/python2.7/dist-packages/numpy/__init__.pyc'>
numpy has version 1.11.1 but tested version is 1.11.0 
```
So it is possible that this was caused by a problem with compiling numpy 1.11.1

**Comment by joshua-cogliati-inl** [comment]
This problem was fixed by the user updating numpy.  Closing since it was not a raven bug.

**Comment by joshua-cogliati-inl** [comment]
There should be a test that checks the sensitivities calculated by basic statistics.

**Comment by alfoa** [comment]
Josh there are.
For example,

```tests/framework/PostProcessors/BasicStatistics/sensitivity.xml ```

**Comment by joshua-cogliati-inl** [comment]
I checked with the following modification:
```
diff --git a/framework/PostProcessors.py b/framework/PostProcessors.py
index 5314f16..0b890f6 100644
--- a/framework/PostProcessors.py
+++ b/framework/PostProcessors.py
@@ -2561,7 +2561,7 @@ class BasicStatistics(BasePostProcessor):
         #use regressor coefficients as sensitivity
         regressDict = dict(zip(useFeatures, LinearRegression().fit(inpSamples,targetVals).coef_))
         for f,feature in enumerate(features):
-          calculations[metric][target][feature] = 1.0 if feature==target else regressDict[feature]
+          calculations[metric][target][feature] = 11.0 if feature==target else regressDict[feature]
     #
     # covariance matrix
     #
```

The sensitivity tests fail as expected with this modification.  I am closing this because it has been verified that the sensitivities are checked.
