### ISSUE TITLE
Parallel Input Generation and Output Collection for MultiRun steps

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#130]
--------
Issue Description
--------
##### What did you expect to see happen?

I expect the inputs of a multi-run to be generated in parallel, and in addition, I expect the outputs of each run to be read and collected in parallel.

##### What did you see instead?

Currently, RAVEN will do both of these operations in serial on the main thread.

##### Do you have a suggested fix for the development team?

I am working on a development that will move the `createNewInput` and `finalizeModelOutput` functions to occur on the parallel jobs. This is a bit of an invasive change as it changes how data is fundamentally passed around on the inside of RAVEN and so should be tested and reviewed thoroughly before acceptance.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

This is a new improvement that will affect all existing test cases that utilize the `MutiRun` step type.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?  __Should not impact requirements, only increases efficiency of data handling__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.  __Not a defect__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed? ***improvement***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) ***improvement***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***improvement***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***improvement***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***#131***

**Comment by alfoa** [comment]
Closure check list passed...

PR #131 can be merged
