### ISSUE TITLE
[TASK] Optimizer: less resetting for persistence

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1316]
--------
Issue Description
--------

It appears that if e.g. the GradientDescent optimizer rejects an optimal point candidate, it also resets the trajectory persistence. However, this doesn't represent a new unconverged point, but an attempted improvement that is irrelevant to the convergence. Instead, the only time the persistence should be reset is if:
- A new optimal candidate is accepted
- The new optimal candidate point is not in convergence (e.g. gradient magnitude or rel. change in obj. value)

I don't have a test case that proves this behavior, but I'm observing it in some HERON runs, especially when the optimal point is near the boundary but not at the boundary (say at 4 when bounds are 1 to 100).

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist approved...

Closure Approved via #1331
