### ISSUE TITLE
Pickling high-sample GaussianProcess ROM

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#134]
--------
Issue Description
--------
##### What did you expect to see happen?
After training a Gaussian Process ROM from SciKitLearn, I should be able to pickle it for reuse later.

##### What did you see instead?
With as few as ten thousand samples, this works fine; however, with twenty thousand samples, attempting to pickle the ROM results in an error with a partial traceback:
```
Traceback (most recent call last):
  File "/home/talbpaul/projects/raven/framework/Driver.py", line 271, in <module>
    raven()
  File "/home/talbpaul/projects/raven/framework/Driver.py", line 224, in raven
    simulation.run()
  File "/home/talbpaul/projects/raven/framework/Simulation.py", line 1047, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/talbpaul/projects/raven/framework/Steps.py", line 238, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/home/talbpaul/projects/raven/framework/Steps.py", line 774, in _localTakeAstepRun
    cloudpickle.dump(val,file('test.pk','w'))
  File "/home/talbpaul/projects/raven/framework/contrib/cloudpickle/cloudpickle.py", line 699, in dump
    CloudPickler(file, protocol).dump(obj)
```
... snip ...
```
  File "/home/talbpaul/projects/raven/framework/contrib/cloudpickle/cloudpickle.py", line 604, in save_reduce
    save(state)
  File "/home/talbpaul/anaconda2/envs/raven_libraries/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/talbpaul/anaconda2/envs/raven_libraries/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/home/talbpaul/anaconda2/envs/raven_libraries/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/talbpaul/anaconda2/envs/raven_libraries/lib/python2.7/pickle.py", line 492, in save_string
    self.write(BINSTRING + pack("<i", n) + obj)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

However, it hardly seems credible that this particular method would fail to pickle with 20,000 runs with some integer-based error and not fail for a smaller number of runs.

##### Do you have a suggested fix for the development team?
I've drilled down by trying to pickle each element that's part of the object being pickled and trying to identify the offending member.  I'm not sure it's working as I expect, but it seems that the problem is `ROM(model).supervisedEngine.supervisedContainer[0].evaluate`, which is pointing to the bound method `SciKitLearn._readdressEvaluateResponse`.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
This can be reproduced by copying the `gp.xml` test from the regression tests, setting the number of MC samples to 20,000, and increasing the parameter `theta0` until the suggestion to increase it goes away (around 100).

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@PaulTalbot-INL still valid?

**Comment by PaulTalbot-INL** [comment]
I haven't tested this again, neither do I still have the test case.

**Comment by alfoa** [comment]
Not valid anymore. Closing
