### ISSUE TITLE
Grid samplers do not accept integer [DEFECT] Title Here

### ISSUE THREAD

**Issue by rouxpn** [idaholab/raven#1357]
If an integer is specified in the Grid Sampler node; for example:
<grid construction="custom" type="value">4000</grid>

An error is returned 
TypeError: in method 'BasicUniformDistribution_pdf', argument 2 of type 'double'

##### What did you expect to see happen?
RAVEN should sample the variable

##### What did you see instead?
TypeError: in method 'BasicUniformDistribution_pdf', argument 2 of type 'double'

##### Do you have a suggested fix for the development team?
Let RAVEN accept both integers and float number in the grid sampling. 

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by mandd** [comment]
I am trying to replicate this issue but i cannot get the reported error; the test tests/framework/test_Grid_Sampler.xml is already testing grid sampler node with integer values in it.
@rouxpn : can you provide more info here?

**Comment by wangcj05** [comment]
I guess the issue has been resolved
