### ISSUE TITLE
[DEFECT] Title Here

### ISSUE THREAD

**Issue by lhj12** [idaholab/raven#1363]
--------
Defect Description
--------

**Describe the defect**
OSError: No readable outputs have been found!
[fuel_log.txt](https://github.com/idaholab/raven/files/5474649/fuel_log.txt)

![`LB@YMTL`OYQ{83@NUYQJ8L](https://user-images.githubusercontent.com/63589051/97864689-f8da4300-1d43-11eb-8cec-0b9839f67afa.png)
[fuel_inp.txt](https://github.com/idaholab/raven/files/5474689/fuel_inp.txt)
[fuel_log.txt](https://github.com/idaholab/raven/files/5474690/fuel_log.txt)
[fuel_xml.txt](https://github.com/idaholab/raven/files/5474691/fuel_xml.txt)

##### What did you expect to see happen?
there aer "No readable outputs have been found!" in the fuel_log.txt. I am not sure the "keff" in the _fuel.xml_ is true? And I don't what happed and how should I do ?there are the _fuel.inp_ (is true) and _fuel.xml_(not sure).
##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
I think the current SCALE interface is made for TRITON and Origen only. For TRITON case, I think only t-dep is tested. I think this is just a limitation for current interface. I'm sorry we do not currently have the resources to expand the SCALE interface. If you would like to contribute to this feature, you are very welcome to do so. Please let us know if you need additional help.
