### ISSUE TITLE
[DEFECT] Optimizers without initial values errors out if all variables are initialized through sampler.

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1364]
--------
If all initial values of optimized variables are to be provided through a sampler an error occurs:
File "/Users/abdomg/projects/raven/framework/Optimizers/Optimizer.py", line 403, in _initializeInitSampler
    `numTraj = len(self._initialValues)`
TypeError: object of type 'NoneType' has no len()
--------

**Describe the defect**
Although there are two ways to provide initial values of an optimizer: user-provided values or sampled through a user-defined sampler, the latter does not work properly unless at least one variable has user-defined initial values.  

##### What did you expect to see happen?
no errors should occur

##### What did you see instead?
Raven errored out

##### Do you have a suggested fix for the development team?
Yes, 
replace line 403 in Optimizer.py from : `numTraj = len(self._initialValues)`
to: `numTraj = len(self._initialValues) if self._initialValues else None`
**Describe how to Reproduce**
1. just run the attached test.
**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users' group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with the release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?
[init_sampler.xml.zip](https://github.com/idaholab/raven/files/5478594/init_sampler.xml.zip)

**Comment by alfoa** [comment]
Closure checklist passed...

Even if it is a defect not an email is required since the defect can not cause erroneous results, but a crash of the software.

**Comment by alfoa** [comment]
Issure closure approved via #1365
