### ISSUE TITLE
Single Variable Optimization Error

### ISSUE THREAD

**Issue by SamKerber** [idaholab/raven#1392]
--------
When running optimizations within raven, if a user writes a module that contains only one variable to optimize, an error will result. 
--------

Single variable optimization will fail within raven. I have experienced it with both SPSA and Finite Difference optimizations. I would think the error probably persists to other optimization methods.

##### What did you expect to see happen?
When running optimization on one variable, I expected the variable to be optimized. 

##### What did you see instead?
I get an error "IndexError: invalid index to scalar variable"

##### Do you have a suggested fix for the development team?
Yes! Change line 70 in "SPSA.py" to:
     "try:
        delta[var] = perturb[i] * dh
      except IndexError:
        delta[var] = perturb * dh" 

and change line 75 in "FiniteDifference.py" to:
     "try:
        delta = dh * directions[o]
      except IndexError:
        delta = dh * directions"

**Describe how to Reproduce**
1. Write a simple module to optimize one variable (I've attached a raven input and external model)
2. Write a raven XML input to optimize the variable using finite difference or spsa
3. Run the code with raven
4. 

**Screenshots and Input Files**

[One Variable Optimization.zip](https://github.com/idaholab/raven/files/5766196/One.Variable.Optimization.zip)

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
I was able to confirm this behavior independently; I think the solution has more to do with why we sometimes get a scalar instead of a 1-d array within the Optimizer/Sampler algorithms.

@SamKerber is this preventing you from accomplishing critical work? A patch like the one you suggested would temporarily allow you to move forward while we find the right solution on our side.

**Comment by alfoa** [comment]
@SamKerber see https://github.com/idaholab/raven/pull/1393

**Comment by PaulTalbot-INL** [comment]
As this issue results in a crash, not an incorrect conclusion, no additional user-wide notification is necessary.
