### ISSUE TITLE
No-executable interface tests not working as expected

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#14]
--------
Issue Description
--------
##### What did you expect to see happen?
No-executable interface tests should be checking the input modification and output parsing functionality of code interfaces.

##### What did you see instead?
Output reading is not occurring if the executable command returns a nonzero value from the command line.  For example, for the test `raven/tests/framework/CodeInterfaceTests/test_relap5_code_interface.xml`, all of the samples fail on the OS level, so their outputs are not read in.  However, RAVEN simply reports these as failed runs and moves on.  As far as I can tell, the output is not read into RAVEN.

##### Do you have a suggested fix for the development team?

This can be solved by adding a dedicated flag or node for indicating "interface only" testing, which would set a Model-level variable that the Step can check next to the check if the OS returned a 0 value for the run.

This can be tested by actually compiling an output CSV from the gold output files and testing its contents (probably with broad tolerance for deltas).

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

See test listed above.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. 
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) __rationale is insufficient; there is already a method in place for this.__

Issue will be closed without development.

**Comment by alfoa** [comment]
in ```./raven/tests/framework/CodeInterfaceTests/tests``` file there is a flag called ```test_interface_only``` that is used to run the CodeInterface tests. 
When this flag is present, raven is run adding the ```interfaceCheck``` command line argument.

If you want to run it without using the regression test system, you need to add this command line argument by hand (e.g. ```./raven_framework interfaceCheck test_relap5_code_interface.xml```)

**Comment by PaulTalbot-INL** [comment]
@alfoa says:
> I think that issue (#14) does not apply since the regression system should add the command line argument "interfaceCheck"

I wasn't aware of this option.  Closing the issue.

**Comment by PaulTalbot-INL** [comment]
Maybe this should not be closed.  In attempting to run 
`./raven_framework interfaceCheck test_relap5_code_interface.xml`

I received the message
`IOError: [Errno 2] No such file or directory:  '/Users/talbpw/projects/raven/tests/framework/CodeInterfaceTests/test.xml'`

**Comment by alfoa** [comment]
Paul the interfaceCheck command line argument works as expected. 

No bug here and no need to reopen it
