### ISSUE TITLE
split user guider into theory manual and user guide

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#142]
--------
Issue Description
--------
##### What did you expect to see happen?
Based on the discuss with Andrea, we plan to split the current user guide into two documents, one is theory manual and the other one is user guide. 

##### What did you see instead?
The current user guide currently include two parts, one part is the theory and the other part is the guide for the user.

##### Do you have a suggested fix for the development team?
Split the documents

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
N/A

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [X] 1. Is it tagged with a type: defect or improvement? ***improvement***
- [X] 2. Is it tagged with a priority: critical, normal or minor? ***minor***
- [X] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***no***
- [X] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. ***no. improvement***
- [X] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***yes***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***not a defect***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) ***not a defect***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***not a defect***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***not a defect***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***#144***

**Comment by alfoa** [comment]
Issue Closing Check list passed
