### ISSUE TITLE
[UNDER-DISCUSSION] Splitting Math Utils

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1435]
--------
Under Discussion Topic
--------

**Summary of the topic to be discussed with the development team**
MathUtils has become bloated and very difficult to maintain due to minimal structure. There appear to be function duplicates in several places.

**Describe the solution you'd like to be implemented**
Split mathUtils into a python submodule of utils and divide the contents into sensible categories.

**Discussion**
There's some functions that need discussion, which can be added or removed from this list:

Consider for removal:
- createInterp: we now require scipy version such that this function is always a passthrough directly to scipy.interp1d.
- countBins: I think numpy has better tools to do this directly.
- log2: I know numpy and math have tools to do this directly
- distance: this is a straight passthrough to numpy.linalg.norm, probably not worth maintaining seperately
- normal: simple passthrough to scipy.stats.norm.pdf
- normalCdf: simple passthrough to scipy.stats.norm.cdf

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with the under_discussion type?
- [ ] 2. If implemented, it will add a new requirement?
- [ ] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by wangcj05** [comment]
archived.
