### ISSUE TITLE
[DEFECT] Exercise input/instruction errors in ForwardSampling workshop

### ISSUE THREAD

**Issue by huang714** [idaholab/raven#1461]
--------
Defect Description
--------

**Describe the defect**

Exercises under raven/doc/workshop/forwardSampling use a projectile model to help with sampling different variables from different samplers and analyzing the sampling results.
1. The variables distributions under `<Samplers>` include the initial velocity `v0`, `angle`, initial horizontal position `x0`, initial vertical position `y0`, and the `timeOption`. However under `<Models>/<ExternalModel>/<variables>`, only `v0`, `angle`, `r` (range), `t` (time of flight), `timeOptions` are defined. This makes the distributions defined under `<Samplers>` for `y0` and `x0` not passed to the variables in the external model, the code will use the default values for the undefined variables under `<Models>` when sampling. This directly results in that following the instructions in Exercise 3 of the ForwardSampling workshop by changing `v0` to `y0` in `<Models>` and `<Samplers>` will not get the expected results. And in all exercises, the input to set `x0` as a constant value of 0 will not be executed, the default value of `x0` defined in the external model projectile.py is actually used in all exercises.
2. `<features>` and `<targets>` definitions are not clear in analyzing statistical results using BasicStatistics PostProcessor in Exercise 5. Exercise 5 in the ForwardSampling workshop slides asked to output sensitivities of `r` to `y0` and `angle`, which reads to me: calculate sensitivities of r with respect to y0 and angle. However the exercise input gives r as <features> and y0, angle as <targets>, while in user manual 15.5.1 BasicStatistics (instructed as 17.5.1 in the workshop slides), no descriptions for <features> and <targets> are provided under <sensitivities>, which makes it confusing.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
checklist is good.
