### ISSUE TITLE
[DEFECT] Exercises in reducedOrderModeling workshop

### ISSUE THREAD

**Issue by huang714** [idaholab/raven#1462]
--------
Defect Description
--------

**Describe the defect**

Objectives of each exercise is not clear to the learners. 
For example, Exercise 4 tries to load a ROM, but it contains all steps from sampling the original model, train the ROM model, store the ROM model, and load the ROM model. And it loads the ROM model with all information to the ROM required, including the subType, Features, Target and the order selected when training the ROM. But in reality we don't have to know all the details to load a pickled ROM. 
Also, the visualized output of this load-a-rom exercise is the r vs angle plot from Monte Carlo sampling of the original projectile model, which is the same as Exercise 1, 2, and 3, whose objectives are building a sample function, training a rom, and pickling a rom respectively.
The same repeated information shows in all exercises, making it unclear what should be or have to be included to finish each rom task.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue checklist passed.
