### ISSUE TITLE
Optimization <SolutionExport> error 

### ISSUE THREAD

**Issue by SamKerber** [idaholab/raven#1474]
--------
When running an optimization, if <SolutionExport> is not provided in <Steps> the code will run the optimization but then fail at the end
--------

**Describe the defect**

##### What did you expect to see happen?
No errors

##### What did you see instead?
"AttributeError: 'NoneType' object has no attribute 'addRealization'"

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. Run optimization without <solutionExport> node in the <Steps> section
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
<img width="768" alt="Screen Shot 2021-03-12 at 2 34 13 PM" src="https://user-images.githubusercontent.com/76967035/111003776-fec0e000-8344-11eb-85e7-c1c4e57631ac.png">

[ErrorReport.zip](https://github.com/idaholab/raven/files/6133246/ErrorReport.zip)

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Catalina
 - Version: [e.g. 22] 10.15.7
 - Dependencies Installation: [CONDA or PIP] Conda

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
I see the real issue here being that the user was allowed to make an Optimizer without a SolutionExport node, perhaps?

**Comment by joshua-cogliati-inl** [comment]
If someone wants to replicate the problem with one of our test cases, here are the changes needed:
```diff
diff --git a/tests/framework/Optimizers/GradientDescent/central_diff.xml b/tests/framework/Optimizers/GradientDescent/central_diff.xml
index ab5093669..ac1b01a8d 100644
--- a/tests/framework/Optimizers/GradientDescent/central_diff.xml
+++ b/tests/framework/Optimizers/GradientDescent/central_diff.xml
@@ -24,14 +24,14 @@
       <Input class="DataObjects" type="PointSet">placeholder</Input>
       <Model class="Models" type="ExternalModel">beale</Model>
       <Optimizer class="Optimizers" type="SPSA">opter</Optimizer>
-      <SolutionExport class="DataObjects" type="PointSet">opt_export</SolutionExport>
+      <!-- <SolutionExport class="DataObjects" type="PointSet">opt_export</SolutionExport> -->
       <Output class="DataObjects" type="PointSet">optOut</Output>
-      <Output class="OutStreams" type="Print">opt_export</Output>
+      <!-- <Output class="OutStreams" type="Print">opt_export</Output> -->
     </MultiRun>
     <IOStep name="print">
       <Output class="DataObjects" type="PointSet">optOut</Output>
-      <Output class="OutStreams" type="Print">opt_export</Output>
+      <!-- <Output class="OutStreams" type="Print">opt_export</Output> -->
     </MultiRun>
     <IOStep name="print">
-      <Input class="DataObjects" type="PointSet">opt_export</Input>
+      <!-- <Input class="DataObjects" type="PointSet">opt_export</Input> -->
       <Input class="DataObjects" type="PointSet">optOut</Input>
-      <Output class="OutStreams" type="Print">opt_export</Output>
+      <!-- <Output class="OutStreams" type="Print">opt_export</Output> -->
       <Output class="OutStreams" type="Print">optOut</Output>
     </IOStep>
   </Steps>
```
