### ISSUE TITLE
[DEVELOPMENT] TimeSeriesAnalysis algorithms

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1485]
--------
Under Discussion Topic
--------

**Background of the development decision**
Frequently in RAVEN entities (`ROM`, `Sampler`, `PostProcessor`, etc) we need to use algorithms embedded in other entities. Frequently for entities needing to use ROMs, this requires instantiating, initializing, using, and deconstructing the embedded entity, forcing the using entity to implement the API that is typically reserved for the `Step`.

In particular, the ARMA, Fourier, PeakPicking, etc. embedded in the `SupervisedLearning.ARMA` object can be useful in characterizing time series in other entities such as PostProcessors.

In successive development meetings in the end of 2020 and early 2021, the decision was made to create a `TimeSeriesAnalysis` (TSA) module, containing algorithms for time series analysis that are not specific to any given RAVEN entity, such as ARMA, Fourier, etc. The `SupervisedLearning.ARMA` class can then be rewritten as a `SupervisedLearning.SyntheticHistory` class that leverages the TSA module algorithms. This allows other entities such as time series characterization PostProcessors to also use the `TSA` algorithms without instantiating `SupervisedLearning.SyntheticHistory` objects.

**Broader development implication**
This decision sets precedent for preferring algorithms be separated from entities when the algorithms are needed in multiple parts in the code.

If the algorithms are sufficiently straightforward, they might be included in the `utils` libraries, particularly `mathUtils`.

If the algorithms are a family of related algorithms, it may be preferable to create a new module for that family of algorithms.

**References**
PRs for TSA:
- Implementations: #1434, #1437, #1440, #1444  
- Introduction: #1405

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with the under_discussion type?
- [x] 2. If implemented, it will add a new requirement?
- [x] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by dylanjm** [comment]
@PaulTalbot-INL Should I close #1443 or would you consider this a different "issue". One addressing the [Task] of adding algos and one addressing the [Development Decisions]?

**Comment by PaulTalbot-INL** [comment]
I don't think this should be "closed" so much as referenced as a design decision. I would keep using #1443.
