### ISSUE TITLE
[UNDER-DISCUSSION] MultiObjective Optimization Abstraction

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1487]
--------
Under Discussion Topic
--------

**Summary of the topic to be discussed with the development team**
How to deal with multiobjective optimization problems to facilitate it in other optimizers?

**Describe the solution you'd like to be implemented**
If somehow we can allow for a list/vector of objectives, then abstract the notion of fitness so that this vector can be collapsed into a single scalar either by computing the mean, a weighted average, the sum, some L-p norm, others. Besides, how can we facilitate the use of the n-d Pareto Frontiers in other optimizers?

**Describe alternatives you've considered**
Just try to make it work in GA, then abstract and clean it later.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with the under_discussion type?
- [ ] 2. If implemented, it will add a new requirement?
- [ ] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by wangcj05** [comment]
similar to #1795
