### ISSUE TITLE
[DEFECT] Key Error for unrelated problem when using ./run_tests

### ISSUE THREAD

**Issue by dylanjm** [idaholab/raven#1489]
--------
Defect Description
--------

**Describe the defect**

If one doesn't have the "ExamplePlugin" plugin installed, then when using `./run_tests --re <pattern>` you will receive an error at end showing something like:

```
Traceback (most recent call last):
  File "/Users/mcdodj/Documents/projects/raven/scripts/plugin_handler.py", line 207, in <module>
    raise KeyError('Plugin "{}" not installed!'.format(requested))
KeyError: 'Plugin "ExamplePlugin" not installed!'
```

##### What did you expect to see happen?

Given that I'm not testing a plugin, I probably shouldn't see errors regarding plugins. It gives way to confusion to see errors past the point of the program actually succeeding. 

##### What did you see instead?

I saw errors concerning plugins when I wasn't testing plugins. 

##### Do you have a suggested fix for the development team?

I'm assuming `plugin_handler.py` is run every time `./run_tests` is run. Perhaps adding an `--all` flag will include plugin tests and thus run the `plugin_handler.py` script as well. 

**Describe how to Reproduce**
1. Try running `./run_tests --re Wavelet`

**Platform (please complete the following information):**
 - OS: macOS 10.15.7
 - Dependencies Installation: Conda

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
The intention right now is the ExamplePlugin (which is part of the repo) always gets run even if no other plugins are installed. There are separate tests that run for the full suite of plugins, but the Example plugin is used to test RAVEN's plugin mechanics separate from external plugins.

This does assume that at some point it also is installed as a plugin, which we do on all the test machines, but do not do by default as part of the build process; I agree there could be some improvement here.

**Comment by alfoa** [comment]
The example plugin must be installed by the build_raven script. We can add it.
Good catch.
@dylanjm  can you address it?

**Comment by dylanjm** [comment]
@alfoa Sure thing.

**Comment by alfoa** [comment]
Closure checklist passed...

PR approved via #1495 

No email is needed since this is a crash of the installation but not wrong results can be produced
