### ISSUE TITLE
Clean Build issue

### ISSUE THREAD

**Issue by tvulture** [idaholab/raven#15]
--------
Issue Description
--------
##### What did you expect to see happen?
I expected the tests to be executed. This was a first attempt build on a clean Ubuntu 16.04 Server distro. The build appeared to work.

##### What did you see instead?
Following the install instructions on the wiki page I got to the point where I ran the following:
./run_test -j2

I got the following errors:
Traceback (most recent call last):
 File "./backend_run_test", line 20, in <module>
  import path_tool
importError: No module named path_tool

##### Do you have a suggested fix for the development team?
This might be a missing dependency in your suggested setup for Ubuntu 16.04.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by bobkinl** [comment]
One common cause of this error is the absence of the MOOSE framework, which is a submodule of RAVEN.  RAVEN uses the test framework from MOOSE, and path_tool is part of that system.

Running this command in the raven directory will add it to your installation:
```
git submodule update --init moose
```
I definitely think that RAVEN could provide a more informative message in this case.

**Comment by tvulture** [comment]
My error here as well. I did not do a git pull of the source code. I downloaded it as a zip file.

**Comment by alfoa** [comment]
This issue can be closed since addressed in the past months
