### ISSUE TITLE
[DEFECT] Generic Interface Issue when having an Input Error

### ISSUE THREAD

**Issue by kaks2000** [idaholab/raven#1505]
--------
Defect Description
--------

**Describe the defect**

While working on the generic interface of RAVEN, it was realized that if the post-fix "$" is missing, it goes into infinite LOOP without providing any error message to the user.  
This defect seems to require a fix.

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
with the fix in PR #1885, the following error message will be raised: 

![image](https://user-images.githubusercontent.com/7321071/178036360-96887828-3dab-4290-8113-c2c213114c83.png)

**Comment by joshua-cogliati-inl** [comment]
I do not think an email is needed, since this just improves an error message.
