### ISSUE TITLE
[DEFECT] Ambiguous warning from limit surface search

### ISSUE THREAD

**Issue by Jderrill** [idaholab/raven#1515]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
Complete the limit surface search.

##### What did you see instead?
Warning about not crossing the limit surface search comes up every run because it propagates from the first sample.

![Screen Shot 2021-04-15 at 11 42 24 AM](https://user-images.githubusercontent.com/8010235/114914586-b67f5c80-9ddf-11eb-8b26-74af3b0cef67.png)

##### Do you have a suggested fix for the development team?

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Is this a defect? It looks like all the samples were explored, but like you point out, you never crossed the surface you're looking for. I think this is behaving as expected, perhaps?

**Comment by wangcj05** [comment]
I guess we can close this issue.
