### ISSUE TITLE
Code Modularization: SupervisedLearning

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#152]
--------
Issue Description
--------
##### What did you expect to see happen?

The code should be reorganized to split the sub-classes of the SupervisedLearning into separate files and place them each in their own directory with an appropriate __init__.py and a Factory.py file.

##### What did you see instead?

All of the subclasses are in a single file which can sometimes make it hard to orient oneself and find code snippets for a given class.

##### Do you have a suggested fix for the development team?

See Question 1.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

No error associated.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
This can be closed with #1607
