### ISSUE TITLE
[DEFECT] Pointset does not load a variable in the first column of a csv. 

### ISSUE THREAD

**Issue by klfrick2** [idaholab/raven#1564]
Issue being that the system does not load the variable Time in the first column of the csv. 

Error is below. Shows missing Tb and Tb as being unused. 

RAVEN Python dependencies located and checked.
(    2.99 sec) SIMULATION               : Message         -> Simulation started at 2021-05-19 15:59:39
InputData: Using param spec "DataSet" to read XML node "PointSet.
(    3.05 sec) PointSet                 : ERROR           -> Not all variables requested for data object "data" were found in csv "C:\Users\FRICKL\projects\TEDS_VandV\V_V\csv\TEDS_startup.csv"!
Needed: {'Tb', 'Flow Rate'};
Unused: {'Type K TC #1', 'Tb', 'Omega Pressure', 'Date/Time', 'Type K TC #3', 'Type K TC #2'};
Missing: {'Tb'}
OSError: Not all variables requested for data object "data" were found in csv "C:\Users\FRICKL\projects\TEDS_VandV\V_V\csv\TEDS_startup.csv"!
Needed: {'Tb', 'Flow Rate'};
Unused: {'Type K TC #1', 'Tb', 'Omega Pressure', 'Date/Time', 'Type K TC #3', 'Type K TC #2'};
Missing: {'Tb'}

**Describe how to Reproduce**
1.  unload the zip. [issue.zip](https://github.com/idaholab/raven/files/6511792/issue.zip)
2. make a csv folder and place the .csv file in there.
3.  run the .xml file in a directory above the csv folder. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
It looks like the issue is this data was scraped from `txt` into `csv` using Excel, and Excel encodes using the `\ufeff` BOM (see https://stackoverflow.com/questions/17912307/u-ufeff-in-python-string/17912811#17912811). There are some encoding options of Python that will correctly remove that; I'm looking into whether we can do this automagically.

**Comment by PaulTalbot-INL** [comment]
It turns out this fix didn't work for Windows but passed our tests somehow. I'm working on it.

**Comment by wangcj05** [comment]
@PaulTalbot-INL Could you send an email to the users regarding this fix?

**Comment by dylanjm** [comment]
@wangcj05 I will have some time to take a look at this again.
