### ISSUE TITLE
[TASK] Performance Improvement 

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1567]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**

Currently, HS2PS post processor is using dictionary to convert HistorySet to PointSet. There is a performance issue with this conversion. A test case is provided. The following is the comparison between using Dictionary and Dataset as the conversion:

Test summary: Lorentz Attractor model, 3 output variables, 3 time steps 
```
                                                                Cumtime for HS2PS
------------                       -----------------------------------------------
No. of RLZs                         Dictionary                         Dataset
10000                                    ~ 47 s                         ~ 0.3 s
20000                                    ~ 88 s                         ~ 0.4 s
---------------------------------------------------------------------------------
```
Another issue was found when profiling the test. The issue is happened during the addRealization when collect results from sampling. 
(20000 rlzs) 
![image](https://user-images.githubusercontent.com/7321071/118919250-666d4b80-b8f1-11eb-8fba-8ee87c071e9f.png)
The deep copy took about 22s 
![image](https://user-images.githubusercontent.com/7321071/118919923-a5e86780-b8f2-11eb-8d73-65f1179413f3.png)

When remove the deep copy in the "addRealization" of DataSet.py, the deep copy took about 6s. 
![image](https://user-images.githubusercontent.com/7321071/118920247-48084f80-b8f3-11eb-8a35-8c9240fdd352.png)

While with 10000 rlzs:

The deep copy took about 5s:
![image](https://user-images.githubusercontent.com/7321071/118920386-97e71680-b8f3-11eb-8933-e3bd1359560a.png)

While remove the deep copy line in the "addRealization" of DataSet.py, the deep copy took about 6s., the deep copy took about  3s:
![image](https://user-images.githubusercontent.com/7321071/118920545-d8df2b00-b8f3-11eb-887f-053003e9f935.png)

Basically, the time cost for deep copy in DataSet increase nonlinearly (i.e., exponentially). In sum 
```
                                               Cumtime for deep copy 
------------       -----------------------------------------------
No. of RLZs      with deep copy in addRealization             without
10000                              ~ 6 s                        ~ 3 s
20000                             ~ 22 s                        ~ 6 s
------------------------------------------------------------------------
```

[test.zip](https://github.com/idaholab/raven/files/6512775/test.zip)

**Describe the solution you'd like**

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Please take a look at this issue @alfoa @PaulTalbot-INL @mandd @joshua-cogliati-inl

**Comment by PaulTalbot-INL** [comment]
Previously the deep copy was added because of problems from outputting the same realization to multiple destinations, and having cross manipulation problems. If I recall, this was particularly an issue for the metadata.

**Comment by wangcj05** [comment]
@PaulTalbot-INL I have tried to remove it, I see the issue if we remove or modify the provided "rlz". I tried to change it to different name, e.g. rlzIn. In this case, we do not directly modify the provided realizations with a little bit increase in memory. I have tested the changes in my local machine, all tests run successfully.

**Comment by PaulTalbot-INL** [comment]
That's interesting; that doesn't seem like it should be very different from the deepcopy; either we have a copy of the data or not, right?

If we do want to try removing the deepcopy, I would recommend trying hard to break it, such as outputting a time-dependent MultiRun to three different data objects, etc. I am not confident we're testing things that might be broken by removing that deepcopy.

I don't remember what notes went into the code, but I distinctly remember adding that deepcopy after trying to remove it in the past; perhaps we've "fixed" the problem since then.

**Comment by PaulTalbot-INL** [comment]
Actually, it might have had to do with the SolutionExport as well; we use the DataObjects in such a variety of ways ...

Also, I notice at the top of DataSet.addRealization, we pop the indexMap right after the deepcopy. This by itself seems like it justifies the deepcopy, otherwise we've fundamentally modified the realization.

**Comment by PaulTalbot-INL** [comment]
Interesting. The `rlz = dict( ... )` pattern should work unless we're modifying the actual data contents, which seems like a bad thing to do generally speaking. Maybe it could happen in a postprocessor? Can we protect against it somehow?

I suspect that once we call `asDataset` the link to the original realization objects is gone; I'm not sure about when it's in the `collector` before that.
