### ISSUE TITLE
Clean Build Issue Doc user manual

### ISSUE THREAD

**Issue by tvulture** [idaholab/raven#16]
--------
Issue Description
--------
##### What did you expect to see happen?
I expected to see a user manual of some sorts

##### What did you see instead?
When attempting to build the user manual by executing 'make' in the /doc/user_manual directory I get an error. The command line tool pdflatex is missing. Another item to add to the dependency list.

##### Do you have a suggested fix for the development team?
Perhaps you should actually build this project in a clean environment before giving it out to the world. This way you can identify all the dependancies and layout a working build environment for others.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by tvulture** [comment]
Upon further reflection this might be a difference between the Ubuntu Server build and the Ubuntu desktop packaging.

**Comment by bobkinl** [comment]
Please pardon the incomplete Wiki.  We are still in the process of moving everything to github from our internal development system. 

The necessary Ubuntu packages for building the manuals are: 
```
texlive-latex-base texlive-extra-utils texlive-latex-extra texlive-math-extra
```
Once these packages are loaded, you can build the manuals by changing to the "doc" directory in raven and running ./make_docs.sh:
```sh
$ cd raven
$ ./make_docs.sh
```
The documents can then be found in the subdirectories of doc.

**Comment by sonatsen** [comment]
Thanks @bobkinl for giving a solution to Ubuntu users. Unfortunately, same issue exists on clean Mac systems. Although, the code successfully builds on a clean MacOS Sierra (10.12.3), the build of documents require LaTex packages. 
The Mac users can download MacTex (*LaTex on Mac*) from [MacTex.pkg](http://tug.org/cgi-bin/mactex-download/MacTeX.pkg)

**Comment by alfoa** [comment]
This issue can be closed since it has been addressed in the last months
