### ISSUE TITLE
[DEFECT] MooseBasedApp Interface error with moose [Outputs] Block

### ISSUE THREAD

**Issue by duenam5913** [idaholab/raven#1609]
--------
Defect Description
--------

When using the MooseBasedApp interface in raven, in the [Outputs] block of a moose based input deck, if a `[csv]` type block is already used, the addition of the line `csv=true` to the `[Outputs]` block results in an error in the moose based app. 

##### What did you expect to see happen?
In the original input deck the use of [no_print] block allows the printing of the output from the moose simulation.

##### What did you see instead?
The RAVEN modified input deck adds the line `csv=true` and `file_base=out~input` to the `[Outputs]` block. The inclusion of `csv=true`  results in an error stating the `file_base` input already exists and stops the run. 

##### Do you have a suggested fix for the development team?
If the `[csv]` type block is already included in the `[Outputs]` block then the line `csv=true` does not need to be added to the input deck by the interface.

**Describe how to Reproduce**
1.  In a MooseBasedApp input deck include the [csv] block under [Outputs]
2.  Run RAVEN case with MooseBasedApp interface
 
**Screenshots and Input Files**

Original Input Deck:
```
[Outputs]
# Define output file(s)
  interval = 1
  print_linear_residuals = true
  perf_graph = true
  color = false

  [console]
    type = Console
    max_rows = 25
  []

  [exodus]
    type = Exodus
    interval = 3
  []

  [no_print]
    type = csv
  []
[]

```

Input deck modified by RAVEN:
```
[Outputs]
  interval = 1
  print_linear_residuals = true
  perf_graph = true
  color = false
  [./console]
    type = Console
    max_rows = 25
  [../]
  [./exodus]
    type = Exodus
    interval = 3
  [../]
  [./no_print]
     type=csv
  [../]
  csv = true
  file_base = out~input
[]
```

**Platform (please complete the following information):**
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP]

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved to close via #2274.
