### ISSUE TITLE
[DEFECT] {Within HYBRID} Error using file path with space (such as OneDrive - Idaho National Laboratory)

### ISSUE THREAD

**Issue by mikkdm** [idaholab/raven#1612]
--------
This was originated with an installation of HYBRID within OneDrive. I have recreated the issue by naming a folder hybrid temp (as opposed to hybrid_temp). 
--------

When attempting to run tests in HYBRID or in the RAVEN submodule, I get a no such file/directory error listing the path from /c/......./Repo/hybrid <--- should be ......../hybrid\ temp/

##### Do you have a suggested fix for the development team?
After some effort, I've found quite a few locations where the path variables can be corrected using quotes around the variables names such as in line 225 in establish_conda_env.sh by quoting $RAVEN_RC_SCRIPT, that progressed me on to an error later on. 

**Describe how to Reproduce**
1. Change a directory upstream of RAVEN to having a space in it, try and run tests. 
2. 
3. 
4. 

**Platform (please complete the following information):**
 - Windows, not entirely sure of the RAVEN version. Different user had this error with a relatively recent install. 

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Okay, this is a problem.  If you have found all the locations that need to be quoted, we would be happy to merge that change.  Otherwise, it will take a bit longer for us to fix this.

**Comment by wangcj05** [comment]
I guess this issue can be archived.
