### ISSUE TITLE
[DEFECT] Raven Runs Raven fails during ExamplePlugin installation

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#1623]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?
No extra errors with Raven Runs Raven.

##### What did you see instead?
```
Installing ExamplePlugin...
Initializing plugin "/home/cogljj/raven/os/raven/scripts/../plugins/ExamplePlugin"
 ... plugin located at "/home/cogljj/raven/os/raven/plugins/ExamplePlugin" ...
Traceback (most recent call last):
  File "/home/cogljj/raven/os/raven/scripts/install_plugins.py", line 123, in <module>
    infoFile, root = pluginHandler.loadPluginTree()
  File "/home/cogljj/raven/os/raven/scripts/plugin_handler.py", line 143, in loadPluginTree
    root, _ = xmlUtils.loadToTree(pluginTreeFile)
  File "/home/cogljj/raven/os/raven/scripts/../framework/utils/xmlUtils.py", line 250, in loadToTree
    tree = ET.parse(filename, parser=parser)
  File "/home/cogljj/miniconda3/envs/raven_libraries/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/home/cogljj/miniconda3/envs/raven_libraries/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

##### Do you have a suggested fix for the development team?
Don't install the ExamplePlugin during ```establish_conda_env.sh --load```

**Describe how to Reproduce**
1. run tests/cluster_tests/RavenRunsRaven/rom.xml enough times.
2. Look at the output in Rom/FirstMRun/[1-5]/out~test_rom_trainer

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
Falcon Cluster

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue checklist is good.

**Comment by wangcj05** [comment]
This issue will not cause the wrong results for user, and an email is not required.
