### ISSUE TITLE
[TASK] Ability to export ROM parameters 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#1633]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Sometimes it would be useful to export the ROM parameters to the user.  (For example, one user has requested that the sklearn MLPRegressor model should have a way to export the weights and biases.)

Currently RAVEN does not have a way to do this (pickling for example stores theses, but in a rather opaque way.)

Update: RAVEN does have a way to do this, but does not implement it for all ROMs.

**Describe the solution you'd like**
A general way to specify that the ROM should export the parameters determined when it is trained would be useful. 

**Describe alternatives you've considered**
Using the ROM directly usually works, but this does not allow the user to understand the model, or to try different external analysis techniques.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Tagging @wangcj05  since he is working on ROM improvement, and @Jimmy-INL since he has also requested this ability.

**Comment by PaulTalbot-INL** [comment]
We do have a mechanic for this, using the `writeXML` method, but I don't think it's used for all the ROMs yet.

To use it you have an IOStep with the ROM as input and a DataObject as output. Pointwise and XML data will go into the CSV/XML files respectively.

I know it's used for the old ARMA ROM and perhaps the DMDc and PolyExponential, I don't know what else.

**Comment by joshua-cogliati-inl** [comment]
Okay, I see that in framework/SupervisedLearning/PolyExponential.py  However, framework/SupervisedLearning/SciKitLearn.py does not seem to have a ```writeXML``` method, so MLPRegressor will not be able to do that at the moment.

**Comment by PaulTalbot-INL** [comment]
I believe the base method is defined in SupervisedLearning, but is extendable in each inheritor.

**Comment by joshua-cogliati-inl** [comment]
Yes, the base method is in SupervisedLearning, but it only does:
```
writeTo.addScalar('ROM',"noInfo",'ROM has no special output options.')
```

**Comment by PaulTalbot-INL** [comment]
Yeah, the real challenge is that each ROM representation is dramatically different. We initially attempted to do a full roll-out of this meta-printing strategy across all of SupervisedLearning but quickly realized, with very few exceptions, each strategy will need to specify its own variables and value structure.

For ScikitLearn ROMs in particular, some families may share some of the descriptive meta structure, but more generally each strategy will need to identify and print its own data. Thus, perhaps the MLPRegressor could be simply extended to provide its information without having to extend all the other strategies?

**Comment by joshua-cogliati-inl** [comment]
For SciKitLearn we could probably do something like (untested psedocode):
```
writeXML(...):
for index in range(len(self.ROM)):
  if "coefs_" in dir(self.ROM[index]):
    writeTo.addVector("coefs_"+str(index), self.ROM[index].coefs_)
  if "intercepts_" in dir(self.ROM[index]):
   writeTo.addVector("coefs_"+str(index), self.ROM[index].intercepts_)
```

It would dump out information for both MLPRegressor and LinearRegression.  But yes, it would need to be more complicated to work in general.

**Comment by PaulTalbot-INL** [comment]
It looks like in PR #1607 (ROM API) there's more modularity introduced to the ScikitLearn ROM, allowing each strategy to be independent. Maybe that will facilitate rolling out attribute exposure.

**Comment by joshua-cogliati-inl** [comment]
Yes, possibly after #1607 it might be as simple as each class that inherits from ScikitLearnBase has a list of scalars to export and vectors to export.

**Comment by joshua-cogliati-inl** [comment]
LinearRegression with actual tested code: https://github.com/idaholab/raven/commit/ab4e3e76c5f567aeded53e55e6442b0f06774be4
```
diff --git a/ravenframework/SupervisedLearning/ScikitLearn/LinearModel/LinearRegression.py b/ravenframework/SupervisedLearning/ScikitLearn/LinearModel/LinearRegression.py
index a1e527ab1..8526baeb3 100644
--- a/ravenframework/SupervisedLearning/ScikitLearn/LinearModel/LinearRegression.py
+++ b/ravenframework/SupervisedLearning/ScikitLearn/LinearModel/LinearRegression.py
@@ -86,3 +86,17 @@ class LinearRegression(ScikitLearnBase):
     # notFound must be empty
     assert(not notFound)
     self.initializeModel(settings)
+
+  def writeXML(self, writeTo, targets=None, skip=None):
+    """
+      Allows the SVE to put whatever it wants into an XML to print to file.
+      Overload in subclasses.
+      @ In, writeTo, xmlUtils.StaticXmlElement, StaticXmlElement to write to
+      @ In, targets, list, optional, list of targets for whom information should be written
+      @ In, skip, list, optional, list of targets to skip
+      @ Out, None
+    """
+    #breakpoint()
+    for index, targetName in enumerate(self.target):
+      writeTo.addVector("ROM", "coefs_"+targetName, ",".join([str(x) for x in self.model.estimators_[index].coef_]))
+      writeTo.addScalar("ROM", "intercept_"+targetName, str(self.model.estimators_[index].intercept_))
```

**Comment by joshua-cogliati-inl** [comment]
Maybe it could be done this way:
```python
    #in LinearRegression.py
    self._vectorWriteList = ["coef_"]
    self._scalarWriteList = ["intercept_"]

#in ScikitLearnBase.py
  def writeXML(self, writeTo, targets=None, skip=None):
    """
      Allows the SVE to put whatever it wants into an XML to print to file.
      Subclasses should define self._vectorWriteList and self._scalarWriteList
      @ In, writeTo, xmlUtils.StaticXmlElement, StaticXmlElement to write to
      @ In, targets, list, optional, list of targets for whom information should be written
      @ In, skip, list, optional, list of targets to skip
      @ Out, None
    """
    for index, targetName in enumerate(self.target):
      for vectorName in self._vectorWriteList:
        writeTo.addVector("ROM", vectorName+targetName, ",".join([str(x) for x in getattr(self.model.estimators_[index], vectorName)]))
      for scalarName in self._scalarWriteList:
        writeTo.addScalar("ROM", scalarName+targetName, str(getattr(self.model.estimators_[index], scalarName)))
```

**Comment by PaulTalbot-INL** [comment]
LGTM. Do you want to move this into a PR?

**Comment by PaulTalbot-INL** [comment]
Approved to close via #1988
