### ISSUE TITLE
[DEFECT] Dymola interface does not show error

### ISSUE THREAD

**Issue by mgarrouste** [idaholab/raven#1635]
--------
Defect Description
--------

I tried to run dymola from RAVEN using the Code Models

##### What did you expect to see happen?
An explanation about why the Dymola executable could not be launched

##### What did you see instead?
The job failed without any explanation. The dslog is printed in one of the subfolders but not easily accessible

##### Do you have a suggested fix for the development team?
Print the location or the content of the Dymola dslog in the RAVEN out file

**Describe how to Reproduce**
1. 
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP] CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
In digging around, I found that we should be printing this statement on a failed code run generally speaking, so it might be specific to Dymola. I suspect either `finalizeCodeOutput` or `checkForOutputFailure` is to blame, but I need to confirm that still.

**Comment by PaulTalbot-INL** [comment]
Marisol confirmed that, when the license file is not present, the run command fails but returns code 0, so we can check for this in the `checkForOutputFailure` option.
