### ISSUE TITLE
[DEFECT] Dymola interface error while loading output file

### ISSUE THREAD

**Issue by mgarrouste** [idaholab/raven#1641]
--------
Defect Description
--------

**Describe the defect**
An error occurred when I tried to run Dymola using RAVEN and the results of the simulation were being retrieved by RAVEN.
##### What did you expect to see happen?
The .mat file should be read without errors and when the user is trying to retrieve a variable or a parameter that doesn't exist in the model an exception should be raised. 

##### What did you see instead?
The .mat file (Dymola) could not be read : an error occurred when matrices of incompatible shapes were concatenated on line 447.  

##### Do you have a suggested fix for the development team?
Working on it: re-writing the finalizeCodeOutput method of the Dymola interface. 

**Describe how to Reproduce**
1. RAVEN input file running a Dymola Code Model with the node <outputVariableToLoad> not empty.  
2. 
3. 
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version: [e.g. 22]
 - Dependencies Installation: [CONDA or PIP] Conda

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment]
Issue approved to be closed via #1642

No email is required since the issue can cause a crash but not "wrong results"

**Comment by wangcj05** [comment]
archived.
