### ISSUE TITLE
Image tester cause crash when images are not the same size

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#166]
--------
Issue Description
--------
##### What did you expect to see happen?
The image tester to return a failure.

##### What did you see instead?
The image tester failed:

```
Traceback (most recent call last):
  File "./backend_run_tests", line 128, in <module>
    TestHarness.buildAndRun(sys.argv, app_name, MOOSE_DIR)
  File "/home/jjc/sub/raven/moose/python/TestHarness/TestHarness.py", line 34, in buildAndRun
    harness.findAndRunTests()
  File "/home/jjc/sub/raven/moose/python/TestHarness/TestHarness.py", line 192, in findAndRunTests
    self.launchTest(find_only, file, dirpath, testers)
  File "/home/jjc/sub/raven/moose/python/TestHarness/TestHarness.py", line 274, in launchTest
    self.runner.run(tester, command)
  File "/home/jjc/sub/raven/moose/python/TestHarness/RunParallel.py", line 107, in run
    self.spinwait()
  File "/home/jjc/sub/raven/moose/python/TestHarness/RunParallel.py", line 282, in spinwait
    self.returnToTestHarness(job_index)
  File "/home/jjc/sub/raven/moose/python/TestHarness/RunParallel.py", line 240, in returnToTestHarness
    output = tester.processResults(tester.specs['moose_dir'], p.returncode, self.options, output)
  File "scripts/TestHarness/testers/RavenFramework.py", line 184, in processResults
    return self.rawProcessResults(moose_dir, retcode, options, output)
  File "scripts/TestHarness/testers/RavenFramework.py", line 262, in rawProcessResults
    (imgSame,imgMessages) = imgDiff.diff()
  File "scripts/TestHarness/testers/RAVENImageDiff.py", line 86, in diff
    self.__messages += 'Gold and test image are not the same shape: '+str(goldImage.shape)+', '+testImage.shape
TypeError: coercing to Unicode: need string or buffer, tuple found
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __because this is a defect in the error reporting of the test harness, it cannot result in incorrect results for users__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)  __there is not currently a standard method for testing the regression test system__
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? __will not impact users directly or frequently__
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved for closure with the associated merge request.
