### ISSUE TITLE
[DEFECT] Genetic Algorithm doesn't recognize constants and functions

### ISSUE THREAD

**Issue by Jderrill** [idaholab/raven#1665]
--------
Defect Description
--------

Genetic Algorithm optimizer doesn't recognize constants or functions.

##### What did you expect to see happen?
Expected the optimizer node to pass constants via multirun that could be accessed by an external model.

##### What did you see instead?
External model doesn't receive constants and throws an error when trying to access the constants.

##### Do you have a suggested fix for the development team?
Have GA send constants like gradient descent

**Describe how to Reproduce**
1. Put constant node into genetic algorithm optimization node/ MC sampler node in any of the GA tests
2. Have external model manipulate the constant
3. Get error AttributeError: 'Object' object has no attribute '[constant name]'
4. 

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

Added Constant:
![image](https://user-images.githubusercontent.com/8010235/134388506-086af7c1-c535-4c7d-b9ec-541887d2bdf5.png)

Manipulated in external model:
![image](https://user-images.githubusercontent.com/8010235/134388617-3a3fd409-91e8-45a6-b92e-88c8f3337a7e.png)

Error:
![image](https://user-images.githubusercontent.com/8010235/134388853-7586d2c0-ab99-4672-a5af-7d0fba2506c7.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Version: [e.g. 22]
 - Dependencies Installation: CONDA
----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@aalfonsi can you send an email to the user regarding the fix for this issue in PR #1666?

**Comment by aalfonsi** [comment]
@wangcj05  is this okay? if so, can you send it?
```Dear users, An issue has been identified with the genetic algorithms. That optimizer did not accept constants, functions and correlated variables. As for PR  #1666 (merged in the devel/master branches), the optimizer now behaves similarly to other optimizers and samplers. ```
