### ISSUE TITLE
[TASK] RAVEN in Python workflows

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#1682]
--------
Issue Description
--------

There are many workflows for MLAI evolving around cloud computing and Python workflows; RAVEN could be included in these workflows if we were to make a Python handler for running RAVEN.

Something that would let you instantiate a RAVEN instance, run the workflow, and interact with the DataObjects post-calculation would be quite useful.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment]
Neat! ;)

**Comment by wangcj05** [comment]
### Several Things from today's meeting for future development @mandd @PaulTalbot-INL @joshua-cogliati-inl @Jimmy-INL @dgarrett622 @dylanjm @yoshiurr-INL:

- User should be able to use RAVEN plot in Python Environment (stretch goal: RAVEN is able to interact with Plotly/Seaborn for interactive plots in Python Environment)
- RAVEN entities should be able to dump some useful information for users to guide them how to use the entities
- Should RAVEN provides certain level of protection for RAVEN entities 
- Possibility to use InputSpecs to accept Muti-format data structure (Jason, Yaml, dict, ...) for RAVEN entities initialization
