### ISSUE TITLE
[TASK] Possible new libraries that can be used to enhance the capabilities of RAVEN

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1702]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**

python-sensors: for sensors optimization
rllib and gym: for deep reinforcement learning
prophet: for time series forecast
stanza, spacy and nltk: for natural language process 
Jupyter: for live interaction with RAVEN
rise: for live Jupyter presentation mode 

**Describe the solution you'd like**

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
does stuff like deeplynx use any particular Python libraries?

**Comment by mandd** [comment]
Do we want to centralize all these libraries within RAVEN or spread them among several plugins depending on the needs?

**Comment by wangcj05** [comment]
> Do we want to centralize all these libraries within RAVEN or spread them among several plugins depending on the needs?

some libraries can be in the plugins, but they need to be no conflict with RAVEN main libraries.

**Comment by wangcj05** [comment]
> does stuff like deeplynx use any particular Python libraries?
From Deep-Lynx repo: 
![Screen Shot 2021-11-01 at 11 25 24 AM](https://user-images.githubusercontent.com/7321071/139713625-ebc45315-54ca-4f02-984e-fb54259bf878.png)

**Comment by PaulTalbot-INL** [comment]
Okay, so DeepLynx really doesn't have a Python component, that's good to know.

**Comment by Jimmy-INL** [comment]
All I know from previous readings is that to communicate with PostgreSQL DB from python you need `psycopg` but maybe that's what they have used for their python adaptor since this one is the most common. In addition, there are other things that I might consider for my LDRD such as `realtime`: https://github.com/Jimmy-INL/realtime
@joshua-cogliati-inl can give us insight if these are really needed for communication with a PostgreSQL wrapper (namely Deep Lynx).

**Comment by Jimmy-INL** [comment]
I am not sure if all the requirements listed by Congjian for Deep Lynx are needed, I think this is for development in Deep Lynx or local communication but if we will communicate with it via URLs that they gave us, do we still need those? This is unclear to me? @joshua-cogliati-inl what do you think?

**Comment by joshua-cogliati-inl** [comment]
> Okay, so DeepLynx really doesn't have a Python component, that's good to know.

Well,  there is https://pypi.org/project/deep-lynx/ which requires requests_toolbelt

**Comment by mandd** [comment]
I'd like to add the library: imageio

**Comment by wangcj05** [comment]
@mandd I think imageio is now an optional lib in raven dependency.

**Comment by wangcj05** [comment]
archived.
