### ISSUE TITLE
Preventing User Error in the Limit Surface Search

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#171]
Some people, like me, may not understand what the difference between the accelerationROM and the model used in a adaptive limit surface search do, and can therefore create a broken input file such as the excerpt below:

```xml
...
    <MultiRun name="refineLS" pauseAtEnd="False">
      <Input class="DataObjects" type="PointSet">data</Input>
      <Model class="Models" type="ROM">AccelerationROM</Model>
      <Sampler class="Samplers" type="LimitSurfaceSearch">adaptiveSearch</Sampler>
      <SolutionExport class="DataObjects" type="PointSet">limitSurface</SolutionExport>
      <Output class="DataObjects" type="PointSet">outAdaptive</Output>
    </MultiRun>
...
  <Samplers>
    <LimitSurfaceSearch name="adaptiveSearch">
      <ROM class="Models" type="ROM">AccelerationROM</ROM>
      <Function class="Functions" type="External">outcome</Function>
      <TargetEvaluation class="DataObjects" type="PointSet">outAdaptive</TargetEvaluation>
...
```
The error generated by RAVEN here is somewhat misleading. By detecting that the same ROM is being used as an acceleration ROM and the model for an adaptive search, we can hopefully protect the user from themselves and generate a useful error message.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
The error that gets out is:
```
RuntimeError: ROM model "accelerated_ROM" has not been trained yet, so it cannot be sampled! Use a RomTrainer step to train it.
```
It is understandable now so this issue can be closed without a PR (since it has been addressed working on the ROM side before)
