### ISSUE TITLE
Limit Surface PostProcessor does not report when the limit surface is empty (not found).

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#172]
User discovered an issue with the limit surface post-processor that failed with a non-sensical error message (from the user's perspective):

```
  File "raven/framework/PostProcessors.py", line 2558, in collectOutput
    for value in limitSurf[0][:, varIndex]:
IndexError: too many indices
```

Upon closer inspection it appears that this is due to the fact that the ROM was unable to identify a limit surface in the specified domain (the PointSet was empty). This should be a simple check and print of an error message.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
This issue is not valid anymore since the issue has been addressed already and the issue has not been closed...

Closure checklist passed...

Closing
