### ISSUE TITLE
[DEFECT] Two Points Crossover doesn't work 

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1724]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Once I run any GA optimization with two points cross over it errors out as follows
`Traceback (most recent call last):
  File "/Users/abdomg/projects/raven/framework/Driver.py", line 313, in <module>
    raven()
  File "/Users/abdomg/projects/raven/framework/Driver.py", line 266, in raven
    simulation.run()
  File "/Users/abdomg/projects/raven/framework/Simulation.py", line 764, in run
    stepInstance.takeAstep(stepInputDict)
  File "/Users/abdomg/projects/raven/framework/Steps/Step.py", line 326, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/Users/abdomg/projects/raven/framework/Steps/MultiRun.py", line 227, in _localTakeAstepRun
    sampler.finalizeActualSampling(finishedJobList[0],model,inputs)
  File "/Users/abdomg/projects/raven/framework/Samplers/Sampler.py", line 1074, in finalizeActualSampling
    self.localFinalizeActualSampling(jobObject,model,myInput)
  File "/Users/abdomg/projects/raven/framework/Optimizers/RavenSampled.py", line 303, in localFinalizeActualSampling
    self._useRealization(info, rlz)
  File "/Users/abdomg/projects/raven/framework/Optimizers/GeneticAlgorithm.py", line 488, in _useRealization
    points = self._crossoverPoints)
TypeError: twoPointsCrossover() missing 1 required positional argument: 'parentIndexes'`

### Steps to Reproduce

CHange any GA test to use two points cross over

### Expected Behavior

No errors

### Screenshots and Input Files

<img width="1680" alt="Screen Shot 2021-11-29 at 1 39 09 PM" src="https://user-images.githubusercontent.com/52417034/143939687-9995e3fe-3074-44bb-beed-199a59f6e590.png">

### OS

MacOS

### OS Version

11.6.1

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Defect is about crash, an email to users is optional. @Jimmy-INL @mandd
