### ISSUE TITLE
[UNDER-DISCUSSION] Deprecate test_mpiqsub_limitnode.xml

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#1730]
--------
Under Discussion Topic
--------

**Summary of the topic to be discussed with the development team**
The LimitNode command in the mpilegacy custom mode randomly fails on sawtooth.

**Describe the solution you'd like to be implemented**
I propose to skip the test since the functionality is likely little used.
The test to be skipped is tests/cluster_tests/test_mpiqsub_limitnode and the input file is tests/cluster_tests/test_mpiqsub_limitnode.xml

**Describe alternatives you've considered**
The alternative is to continue spending time maintaining mpilegacy custom mode.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with the under_discussion type?
- [x] 2. If implemented, it will add a new requirement?
- [x] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by joshua-cogliati-inl** [comment]
@wangcj05 and @AaronEpiney  Any comments?

**Comment by wangcj05** [comment]
The proposed solution is good to me.

**Comment by wangcj05** [comment]
no new requirement will be added.
