### ISSUE TITLE
[TASK] Support git 1.8

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#1732]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Raven plugin initialization does not work with git 1.8 because it does not have --name-only and so we get errors like:

```
python scripts/install_plugins.py -a
error: unknown option `name-only'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --includes            respect include directives on lookup

Initializing plugin "ExamplePlugin"
 ... initializing plugin submodule ExamplePlugin ...
 ... plugin located at "/ibmstor/scratch/moosetest/civet_sawtooth2/build_0/raven/plugins/ExamplePlugin" ...
Installing plugins ...
 ... plugin "ExamplePlugin" path created as "/ibmstor/scratch/moosetest/civet_sawtooth2/build_0/raven/plugins/ExamplePlugin" ...
 ... plugin "ExamplePlugin" informed of RAVEN at "/ibmstor/scratch/moosetest/civet_sawtooth2/build_0/raven/framework"...
 ... plugin "ExamplePlugin" succesfully installed!
 ```

**Describe the solution you'd like**
Support git 1.8

**Describe alternatives you've considered**
Use a newer git.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue checklist is satisfied.
