### ISSUE TITLE
[DEFECT] Remove invalid escape sequence deprecation warnings. 

### ISSUE THREAD

**Issue by dylanjm** [idaholab/raven#1740]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [ ] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

There appears to be several places throughout RAVEN where strings contain invalid escape sequences. These warnings clutter up the output of RAVEN and make it harder to parse. 

### Steps to Reproduce

Here is an example when trying to run RAVEN via HERON:

```
/Users/mcdodj/Documents/projects/raven/framework/Optimizers/SimulatedAnnealing.py:672: DeprecationWarning: invalid escape sequence \s
  """
/Users/mcdodj/Documents/projects/raven/framework/Optimizers/GeneticAlgorithm.py:734: DeprecationWarning: invalid escape sequence \S
  """
/Users/mcdodj/Documents/projects/raven/framework/Optimizers/GeneticAlgorithm.py:748: DeprecationWarning: invalid escape sequence \|
  """
/Users/mcdodj/Documents/projects/raven/framework/Optimizers/GeneticAlgorithm.py:769: DeprecationWarning: invalid escape sequence \m
  """
/Users/mcdodj/Documents/projects/raven/framework/Optimizers/fitness/fitness.py:55: DeprecationWarning: invalid escape sequence \S
  """
/Users/mcdodj/Documents/projects/raven/framework/Optimizers/fitness/fitness.py:107: DeprecationWarning: invalid escape sequence \[
  """
```

### Expected Behavior

No warnings about escape sequences. 

### OS

MacOS

### OS Version

12.1

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
defect only causes some output issues, will not result wrong results. An email to the users is optional. Checklist is satisfied with PR #1741
