### ISSUE TITLE
[DEFECT] Issue with <alias> in externalModels errors not being caught

### ISSUE THREAD

**Issue by greenwoodms06** [idaholab/raven#1746]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

When using aliases with external models there are two issues. 
1. All input errors not all handled properly to send result to `Input`
2. Output aliases with funky names don't appeared to be properly handled

### Steps to Reproduce

1. Errors on setting inputs are not all captured and sent to the exception
```
\raven\framework\Models\ExternalModel.py - Line 253 - Only AyntaxError is caught. Line below error is not caught AttributeError? see line 268).

<alias variable="CFs_10" type="input">CFs[10]</alias>
```

2. Output variables with funky names don't seem to be properly handled. Can't pass information from model back to raven. Below is an example followed by the python code. 
```
<alias variable="pipe_mediums_1_T" type="output">pipe.mediums[1].T</alias>

Python
    # Save output
    parentkey = 'outputs'
    for key in raven.settings[parentkey]:
        setattr(raven, key, np.asarray(results[key]))
```
### Expected Behavior

Expected aliases to work such that python can have its proper naming scheme for inputs and outputs and be readily mapped back to the raven side variables.

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Does not provide incorrect solution, but crashes code, so no notifications necessary.

**Comment by wangcj05** [comment]
issue closure checklist is satisfied with PR #1747.
