### ISSUE TITLE
[DEFECT] valueAtRisk in EconomicRatio is calculated incorrectly

### ISSUE THREAD

**Issue by dgarrett622** [idaholab/raven#1749]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Value at risk is defined as the negative of a specified quantile. The code takes the absolute value.

### Steps to Reproduce

The issue is seen when using a distribution that is always positive. The value at risk should give a negative value, however the code always returns a positive value.

### Expected Behavior

When the specified quantile is negative, value at risk should return a positive value. When the specified quantile is positive, value at risk should return a negative value.

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
It's up to @wangcj05 but I think the misleading behavior of this metric currently warrants a user notification email.

**Comment by PaulTalbot-INL** [comment]
An email needs to be sent out before this is closed, explaining the change of behavior and possible change in VaR values obtained.

**Comment by PaulTalbot-INL** [comment]
Approved to close via #1751.
