### ISSUE TITLE
[TASK] Change default for RunInfo

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1761]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**

Due to the ongoing retirement of FALCON, we need to switch the default of RunInfo parameters to align with SAWTOOTH. 

**Describe the solution you'd like**

Change default of 'NodeParameter' from '-f' to '--hostfile', and change default of 'RemoteRunCommand' from 'raven_qsub_command.sh' to 'raven_ec_qsub_command.sh'.

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
There probably should be an email to the user list about this (since someone might need to change their inputs for cluster running.)

**Comment by wangcj05** [comment]
Email is sent to the user group, here is the copy:

Hello Users,

In the past, if you want to run raven on INL SAWTOOTH cluster, you need to specify the following parameters insider <RunInfo>, otherwise you will get "mpiexec" or "mpirun" command not found error:

![image](https://user-images.githubusercontent.com/7321071/153268640-429a9386-8219-4fa7-8420-d6ce5ec85c64.png)

In recently merged PR ([https://github.com/idaholab/raven/pull/1762/files]), we have changed the default values for <RunInfo> to align with INL SAWTOOTH cluster. In other words, you do not need to specify the values for <NodeParameter> and <RemoteRunCommand> if you run RAVEN on INL SAWTOOTH. But for other clusters, you do need to specify the correct values for these parameters in order to let RAVEN run on your cluster. Please let us know if you have any question.
