### ISSUE TITLE
[DEFECT] Some EconomicRatio Metrics cannot handle HistorySet input

### ISSUE THREAD

**Issue by dgarrett622** [idaholab/raven#1769]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Requesting sortinoRatio or gainLossRatio from the EconomicRatio PostProcessor with inputs/outputs containing a pivotParameter (HistorySet or DataSet) result in an error. All other metrics (sharpeRatio, expectedShortfall, and valueAtRisk) can handle these inputs.

### Steps to Reproduce

Use HistorySet data as input to EconomicRatio PostProcessor and request sortinoRatio or gainLossRatio metrics.

### Expected Behavior

Calculate the requested metrics and return them as HistorySet or DataSet.

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Adds functionality, email is optional.
