### ISSUE TITLE
[DEFECT] LOGOS plugin failed due to recent changes in BasicStatistics PP

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#1771]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [ ] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

- Recent changes in Basic Statistics PostProcessor causes the failure of LOGOS plugin. This happens due to the add of pivotParameter into meta parameters when only static data is provided. In this case, the pivotParameter will be None, which should not be included in the meta params. 

![image](https://user-images.githubusercontent.com/7321071/154183836-0b37f55f-8a87-424c-a510-ac30bc195e26.png)

- Another issue was found in the Basic Statistics PP, the recent implementation of standard error for percentile calculation causes the timeout of SR2ML test. By investigating the tests, it seems the calculation of the standard error for percentile takes much longer to run, for example, the test /SR2ML/tests/CRAFT/test_sept_milestone.xml takes about 130s to complete before the changes, but it takes more than 450s to run for the current devel of raven. **Suggestion: to disable the calculation unless requested**

### Steps to Reproduce

LOGOS plugin is currently failing due to this issue.

### Expected Behavior

LOGOS test LOGOS/tests/MilestoneTestsSeptFY19/use_case_II/raven_capital_budgeting_II.xml should run 

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@PaulTalbot-INL @dgarrett622 I would like you to be aware of this issue, and let me know what do you think.

**Comment by PaulTalbot-INL** [comment]
I agree, if it's all static we probably don't want to provide the pivot Parameter.

**Comment by dgarrett622** [comment]
The same issue will probably happen in EconomicRatio for valueAtRisk and
expectedShortfall. The pivot Parameter should be removed there as well.
