### ISSUE TITLE
[DEFECT] IOStep with HistorySet

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#1778]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

In the IoStep for HistorySet the loading from CSV fails if the "filename" variable is not place in the last column in the master HistorySet CSV file.

The problem happens in the DataSet csv loader.

### Steps to Reproduce

Use the attached files:
basically change the order of variables in the HistorySet master file (placing the filename not in the last column)

### Expected Behavior

Independently on the location, the filename is read

### Screenshots and Input Files

[failure_io_step.zip](https://github.com/idaholab/raven/files/8113370/failure_io_step.zip)

<img width="1266" alt="Screen Shot 2022-02-21 at 8 12 20 PM" src="https://user-images.githubusercontent.com/26668536/155056389-d1f345a1-9ac1-4846-816c-638e18d1d041.png">

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment]
@raven-devel

**Comment by aalfonsi** [comment]
can anybody take a look at this?

**Comment by wangcj05** [comment]
@aalfonsi I have checked the code, the error is due to the assumption in the function """_identifyVariablesInCSV""", which we should be able to fix it easily. 

![image](https://user-images.githubusercontent.com/7321071/160332658-7ad12b49-f5bf-4d4e-a33b-a4a6631d0163.png)

**Comment by wangcj05** [comment]
@aalfonsi I suggest to change the code to use CsvLoader to process the file, instead of reading the lines.

**Comment by aalfonsi** [comment]
@wangcj05 this is good. Thanks for checking. Are you guys going to fix this?

**Comment by wangcj05** [comment]
@aalfonsi Yes, we will address it.

**Comment by aalfonsi** [comment]
> @aalfonsi Yes, we will address it.

Fixed in https://github.com/idaholab/raven/pull/1301

**Comment by wangcj05** [comment]
Issue closure checklist is good.
