### ISSUE TITLE
Support Visual Studios build

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#178]
--------
Issue Description
--------
##### What did you expect to see happen?
RAVEN should work with other compilers besides GCC such as Visual Studio's compiler.

##### What did you see instead?
There were some things that didn't work.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed. 
- [ ] 1. If the issue is a defect, is the defect fixed?  __Issue is an improvement__
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)  __Issue is an improvement, the regression test system has been updated to use Visual Studio to build__
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? __Wiki and Manual have been updated to reflect use of Visual Studio__
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?  __No stable branch currently__
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed 
been provided?  __Pull requests #176, #188, and #200 addressed this issue__

**Comment by bobkinl** [comment]
@joshua-cogliati-inl, it looks like this is finished.  What do you think?

**Comment by joshua-cogliati-inl** [comment]
Yes, I think it is finished.

**Comment by bobkinl** [comment]
Closing issue, RAVEN now builds on Windows with Visual Studio (Tested successfully with versions 2013, 2015, and 2017).
