### ISSUE TITLE
[DEFECT] 

### ISSUE THREAD

**Issue by IzaLantgios** [idaholab/raven#1840]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Trying to use RAVEN to make ROMs of Dymola models but keep getting an error that the license file is not found. User has access to INL Dymola license.

### Steps to Reproduce

Run attached input file

### Expected Behavior

The simulation fails because it cannot find the Dymola license

### Screenshots and Input Files

![LicenseError](https://user-images.githubusercontent.com/16143580/170591506-98781864-bc59-4fda-aefe-5ed8079c9057.PNG)

[test_Dymola_code_interface_load_some_vars_edit_Defect_Report.zip](https://github.com/idaholab/raven/files/8782511/test_Dymola_code_interface_load_some_vars_edit_Defect_Report.zip)

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [ ] Is it tagged with a type: defect or task?
- [ ] Is it tagged with a priority: critical, normal or minor?
- [ ] If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [ ] If the issue is a defect, is the defect fixed?
- [ ] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@IzaLantgios FYI, It seems it complains about the dymola license. Did you set the environment variable "DYMOLA_RUNTIME_LICENSE" to the location of runtime license?

**Comment by IzaLantgios** [comment]
@wangcj05 The only environment variable we are aware of is through system variables, which does not appear to work. Is there a specific command within RAVEN to set the environment variable?

**Comment by wangcj05** [comment]
@IzaLantgios Since RAVEN has already generated the subfolder and model files (listed under ~/.../Hybrid/DymolaOutput/), could you run that model directly without RAVEN?

**Comment by wangcj05** [comment]
If you have a license file that you can copy to your run directory and use it to run your model, you can always listed in RAVEN input file through <Files><Input>...</Input></Files>, and then listed as input in the <MultiRun> using <Input> node to you model. In this case, the license file will automatically be copied to your generated model subfolder.

**Comment by mikkdm** [comment]
@wangcj05 I was able to run the executable file directly through the command line, and it produced the appropriate files and output. But the RAVEN input still appears to be unsuccessfully looking for the license file. Did your last comment mean that we should list the input file within the <Files> block? Such as: 

  <Files>
    <Input name="dsin.txt" type="DymolaInitialisation">C:\Users\MIKKDM\Repo\HYBRID\raven_testing\dsin.txt</Input>
	<Input name="dymola.lic" type="DYMOLA_RUNTIME_LICENSE">C:\Users\MIKKDM\Repo\HYBRID\dymola.lic</Input>
  </Files>

**Comment by wangcj05** [comment]
I mean list your license file under:
![image](https://user-images.githubusercontent.com/7321071/170760359-9612fefd-6fba-4bea-942e-b38121a6c6b7.png)

and used in 

![image](https://user-images.githubusercontent.com/7321071/170760409-d6a3e63b-2c67-47aa-909e-945672c0d55a.png)

As you did for dsin.txt

**Comment by wangcj05** [comment]
> @wangcj05 I was able to run the executable file directly through the command line, and it produced the appropriate files and output. But the RAVEN input still appears to be unsuccessfully looking for the license file. Did your last comment mean that we should list the input file within the block? Such as:
> 
> C:\Users\MIKKDM\Repo\HYBRID\raven_testing\dsin.txt C:\Users\MIKKDM\Repo\HYBRID\dymola.lic

By the way, which command are you using to run your Dymola model in this case?

**Comment by mikkdm** [comment]
@wangcj05 @IzaLantgios Adding in the dymola license file in the input in files and as an input block in Multirun appears to have worked for me. I will share this solution and keep it in mind. 

When I ran it directly in the command line I just ran filepath/dymosim.exe dsin.txt 


@wangcj05 thanks for your help!

**Comment by wangcj05** [comment]
I think the issue has been resolved, the issue can be closed.
