### ISSUE TITLE
Probability Weights on edge cases of Grid Sampler

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#185]
There may be a defect in how the Grid sampler computes probability weights. See branch [`maljdan/fixProbability`](https://github.com/idaholab/raven/tree/maljdan/fixProbability) for a potential fix.

Attn: @PaulTalbot-INL and @aalfonsi, this is the problem we witnessed today during the sprint. The remaining part is going to be develop a more analytic test case.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Is this still an issue? I think this should be fixed ASAP. @alfoa @PaulTalbot-INL

**Comment by alfoa** [comment]
If I remember correctly it has been fix....do you mind to check it?

**Comment by alfoa** [comment]
Closing since the issue has been addressed
