### ISSUE TITLE
[DEFECT] Changing Gaussian Process Regressor default optimizer

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1855]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

If GPR is used as a ROM and RBF kernel is used but the optimizer is not specified the default one will error out.

### Steps to Reproduce

Just change the input file located at raven/tests/framework/ROM/SKLearn/gp.xml by removing the optimizer and specifying a kernel of RBF

### Expected Behavior

Should not error out

### Screenshots and Input Files

<img width="834" alt="Screen Shot 2022-06-14 at 9 49 27 PM" src="https://user-images.githubusercontent.com/52417034/173733183-3e582324-f470-41bb-8aa0-00b5e1f3f22a.png">

<img width="841" alt="Screen Shot 2022-06-14 at 9 49 08 PM" src="https://user-images.githubusercontent.com/52417034/173733201-f532d8ae-4c5a-4081-b8b8-029b8578433a.png">

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue checklist is satisfied. Issue can be closed with PR #1854
