### ISSUE TITLE
[TASK] Make RNG classes picklable

### ISSUE THREAD

**Issue by j-bryan** [idaholab/raven#1863]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Many models in RAVEN require using a random number generator, with an RNG engine in crow being used by default. Because these crow RNGs are being loaded with swig, they cannot be serialized with pickle. Currently, __getstate__ and __setstate__ methods must be implemented for each class which stores a swigged RNG instance so that the class can be serialized. This problem is currently causing SyntheticHistory ROM objects to not be picklable.

**Describe the solution you'd like**
It could be beneficial to wrap the swigged crow RNG instance so that it can be pickled, with the wrapper class reproducing the current RNG engine interface.

**Describe alternatives you've considered**
Addition of __getstate__/__setstate__ methods for the effected classes.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
@wangcj05 @PaulTalbot-INL You may have some insight or preferences for solving this issue. Please let us know your thoughts.

**Comment by PaulTalbot-INL** [comment]
I think Jacob and I talked about this for a bit and ran a design past @wangcj05. I'd be interested in any ideas you have on minimizing the impact, but our basic idea was to make a light wrapper for the swig RNG engine instance that knows how to serialize itself safely.

**Comment by dylanjm** [comment]
Approved to close via #1866
