### ISSUE TITLE
[DEFECT] Documentation does not build on Windows

### ISSUE THREAD

**Issue by dgarrett622** [idaholab/raven#1874]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

On Windows, the documentation is not generated when following the process described in the wiki. running the following does not generate the documentation:

`C:\projects\raven\doc> ./make_docs.sh`

### Steps to Reproduce

Running the following does not generate the documentation:

`C:\projects\raven\doc> ./make_docs.sh`

### Expected Behavior

All of the documentation should be built when running:

`C:\projects\raven\doc> ./make_docs.sh`

### OS

Windows

### OS Version

<img width="454" alt="doc_error" src="https://user-images.githubusercontent.com/19575707/176743078-3b0f1c41-aecc-4619-9478-c0123da6aca8.PNG">

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@dgarrett622 Could you attach the error message to this issue?

**Comment by dgarrett622** [comment]
> @dgarrett622 Could you attach the error message to this issue?

I uploaded the error I see. I've got a fix for this and will put up a PR soon. I also noticed that references were not generated and there was no plugin manual. I will have all of these fixed in my PR.
