### ISSUE TITLE
Constants in Samplers and Optimizers

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#19]
--------
Issue Description
--------
##### What did you expect to see happen?
In any Sampler and Optimizer we should be able to list variables that can be kept constants.

##### Do you have a suggested fix for the development team?
For example, the following input style can be used:

```
  <Samplers>
    <MonteCarlo>
       <variable name="a variable"> 
         <distribution>a distribution</distribution>
       </variable>
      <constant name="a constant variable">1.123456789</constant>
    </MonteCarlo>

  </Samplers>
```

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [X] 1. Is it tagged with a type: defect or improvement? ***IMPROVEMENT***
- [X] 2. Is it tagged with a priority: critical, normal or minor? ***NORMAL***
- [X] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***NO***
- [X] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. ***NO DEFECT***
- [X] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***YES***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved for closure by #32.
