### ISSUE TITLE
[TASK] Specify OS dependent gold files

### ISSUE THREAD

**Issue by dgarrett622** [idaholab/raven#1900]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Some calculations (ARMA for example) give slightly different results when run on Windows, Mac, or Linux. It would be nice if we can specify gold files for each OS in the `tests` files.

**Describe the solution you'd like**
Specify the gold file you would like to use for the test based on the OS. For example: 
```
[./testBasic]
  type = 'RavenFramework'
  input = 'test_basic.xml'
  UnorderedCsv = 'basic.csv'
  windows_gold = 'winBasic.csv'
  mac_gold = 'macBasic.csv'
  linux_gold = 'linuxBasic.csv'
[./] 
```

**Describe alternatives you've considered**
Writing separate tests for each OS and using the "skip_if_OS" parameter.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue closure checklist is good.
