### ISSUE TITLE
[TASK] Improving Vector Passing in RAVEN-Dymola Interface

### ISSUE THREAD

**Issue by dgardner26** [idaholab/raven#1903]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
When a vector is supplied to the RAVEN-Dymola interface, it writes text files of the vectors in a format Dymola can read for each sample. However, there is no way for Dymola to know the file path to those text files, and thus Dymola is unable to read in the vectors. 

**Describe the solution you'd like**
The interface can be updated to write the file path to the text files containing the vectors into the initialization file (which Dymola does successfully read with the current interface).

**Describe alternatives you've considered**
Instead of using RAVEN vectors, scalars for each time step could be used instead. However, allowing RAVEN vectors to be used in the interface allows the interface to be more flexible - this is the way the interface was originally written to work.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
archived.
