### ISSUE TITLE
[TASK] A better way of handling solution export variables in GA

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1911]
--------
Issue Description
--------
Currently, lots of the variables are added manually. there should be a more structured way. 
**Is your feature request related to a problem? Please describe.**
When an implicit constraint is added that is different from the objective function but still lives in the output space, or dependent on another variable, it was challenging to pass this variable among different classes.

**Describe the solution you'd like**
a clear distinction between input variables, output, dependent, solution export and target evaluation.

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
similar to #1912
