### ISSUE TITLE
[DEFECT] DMDc ROM with multiple inputs 

### ISSUE THREAD

**Issue by JunyungKim** [idaholab/raven#1932]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

[Description]

If one tries to construct a DMDc ROM with multiple inputs, RAVEN seems constructing a ROM, but it fails to run ROM (i.e., generate samples by using the ROM) and returns an error.

< Error Message >
![ErrorMessage_1](https://user-images.githubusercontent.com/110840088/183454612-0a4eef74-0d0c-4ab6-a382-98b3c2f05da0.png)

### Steps to Reproduce

[Steps to Reproduce]

1) Open the csv file:
\..\raven\tests\framework\ROM\TimeSeries\DMD\DMDC\trainingData\Synthesized_BOP_0.csv

2) Add a column called u2. To avoid collinearity between u1 and u2, let us create u2 using the following formula in excel sheet 

< Screen Shot of Input Data File >
![screen_shot_CSV_input](https://user-images.githubusercontent.com/110840088/183455729-ad2686b6-2cfd-4c5a-a0e4-efe16cab899c.png)

3) Open RAVEN input file
\..\raven\tests\framework\ROM\TimeSeries\DMD\test_unparameterized_dmdc.xml

4) Add u2 in relevant nodes. u2-related code lines need to be placed in "Models", "Samplers", and "DataObjects" nodes. Please be aware that I uploaded the RAVEN input file I used. 

< RAVEN Code snippet >
![RAVEN_code_snippet](https://user-images.githubusercontent.com/110840088/183456830-b94a5225-22f8-4e76-88ad-5d88a7821e19.png)

5) When one runs the RAVEN input deck, the following error message comes out. 

< Error Message >
![ErrorMessage_3](https://user-images.githubusercontent.com/110840088/183460532-435ebb46-050b-4b58-a616-148732940853.png)

### Expected Behavior

RAVEN should generate samples using the DMDc ROM. 

### Screenshots and Input Files

I uploaded one zip file containing:
1) BOP_Data_index_unPara.csv (TrainDataFile in <Files> node of RAVEN input deck)
2) Synthesized_BOP_0.csv (data input file containing u2 as well)
3) test_unparameterized_dmdc.xml (RAVEN input deck I used)

[test_unparameterized_dmdc.zip](https://github.com/idaholab/raven/files/9283188/test_unparameterized_dmdc.zip)

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Hi @wanghy-anl @aalfonsi, I guess you may have some insights into this issue.

**Comment by dgarrett622** [comment]
This appears to be an array broadcasting issue that occurs when there are > 1 actuators. I have been working with Junyung on this and can put together a fix.

**Comment by wanghy-anl** [comment]
Gents, I am currently on vacation this week but I will be back in office on
Aug 15. Do you need me to take a look when I get back?
Thanks,
Haoyu

**Comment by aalfonsi** [comment]
This has been fixed in the alfoa/feature_selection branch. I will strip it out from there and create a MR to fix this issue

**Comment by wangcj05** [comment]
checklist is good. The defect will cause code crash. No wrong results for the users. An email to the users is optional.
