### ISSUE TITLE
[DEFECT] DMDc ROM unpickling isssue

### ISSUE THREAD

**Issue by JunyungKim** [idaholab/raven#1934]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

DMDc ROM created in RAVEN environment cannot be unpickled by ravenROMexternal class in externalROMloader.py (raven/scripts/externalROMloader.py).

The figure below is the error message I have got when I tried to unpickle it. 

<Error Message>
![DMDc_ROM_unpickling_issue](https://user-images.githubusercontent.com/110840088/183505468-c5982f79-0053-45ff-a9b0-a3ae1f48248d.png)

### Steps to Reproduce

1)	Open RAVEN input deck:
\...\projects\raven\tests\framework\ROM\TimeSeries\DMD\test_unparameterized_dmdc.xml

2)	Change some nodes (e.g. <RunInfo>, <Files>, <Steps>) so that the ROM can be dumped (I attached the input deck I used).

3)	Run the Python code attached (You need to change the path accordingly). This Python code was developed to unpickle the file using the ravenROMexternal class in externalROMloader.py. 

### Expected Behavior

RAVEN should be able to unpickle the pickled file. 

### Screenshots and Input Files

In the attached zip file, there are two files:

1) junyung_test_unparameterized_dmdc.xml - RAVEN input deck used to create a picked file using DMDc ROM.
2) Junyung_LoadingRAVENpickledRomsExternaly.ipynb - Jupyter notebook used for testing unpickling. 

[Junyung_LoadingRAVENpickledRomsExternaly.zip](https://github.com/idaholab/raven/files/9284773/Junyung_LoadingRAVENpickledRomsExternaly.zip)

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
checklist is good. The defect will cause code crash. No wrong results for the users. An email to the users is optional.
