### ISSUE TITLE
[DEFECT] a bug in GA regarding uniform crossovers

### ISSUE THREAD

**Issue by JunyungKim** [idaholab/raven#1953]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

[How Issues were found]
If you open 1_GA_MaxwRep.xml in RAVEN/doc/workshop/optimizer/GeneticAlgorithms/Inputs/ and change <crossover> node from onePointCrossover to uniformCrossover, an error occurs:

Categorical distribution cannot calculate cdf for 0.0

[Reason(s) why it happens]
In crossover.py there is a  function called uniformCrossover. There were a small bug in for loop adding index of children only one so that only half of children were properly developed. 

### Steps to Reproduce

Open 1_GA_MaxwRep.xml in RAVEN/doc/workshop/optimizer/GeneticAlgorithms/Inputs/ and change <crossover> node from onePointCrossover to uniformCrossover, an error occurs:

Categorical distribution cannot calculate cdf for 0.0

### Expected Behavior

It should not create an error. 

### Screenshots and Input Files

[Error Message]

![image](https://user-images.githubusercontent.com/110840088/188022336-5596b4a6-0a0d-44b4-9810-c36281aa18df.png)

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue checklist is good.
