### ISSUE TITLE
[TASK] Install CodeInterface classes similar to External Models

### ISSUE THREAD

**Issue by claybro2005** [idaholab/raven#1958]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Using Raven with the CodeInterface class, it is required to manually copy the CodeInterface.py class into the raven/framework/CodeInterfaceClasses/SomeModule/CodeInterface.py

This is problematic because:
Any revision tracking on a "CodeInterface" class must be manually copied from the raven module back to a personal repo.

Any installation of Raven as a submodule requires the additional step of copying the interface module into Raven.

**Describe the solution you'd like**
Using Raven with the External Plugins Models it is possible to "install" a local directory which includes the plugin. Would it possible to extend the plugin installers use to include code interface classes?  

**Describe alternatives you've considered**
Didn't have success with symlinks in raven/ravenframework/CodeInterfaceClasses/

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment]
@wangcj05 @mandd

**Comment by aalfonsi** [comment]
@wangcj05 @mandd  if you think this is a feature RAVEN should support, can you provide us an ETA? (just to do some internal planning)

**Comment by wangcj05** [comment]
@aalfonsi We would like to have this feature. I will have time in October to tackle this issue.

**Comment by claybro2005** [comment]
@wangcj05 Just pinging you on this issue. Do you think there is still a chance for this to get included this month?

**Comment by wangcj05** [comment]
@claybro2005 Unfortunately, we will not be able to add this feature in this month. I just started to look at this issue. Hopefully we will add this feature in the one or two weeks.

**Comment by wangcj05** [comment]
@claybro2005 @aalfonsi FYI, I have created a PR for the code interface plugin. If you have time, please try to test it and let me know if you have any issue. The PR is #2000
