### ISSUE TITLE
[DEFECT] GA searching only in limited subspace 

### ISSUE THREAD

**Issue by JunyungKim** [idaholab/raven#1976]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

GA has been found that it only searches in limited subspace bound to initial population. If the number of population is small, then optimal solution may not be found. 

### Steps to Reproduce

Try running 

...\projects\raven\doc\workshop\optimizer\GeneticAlgorithms\Inputs\4_GA_MaximumHorizontalRange.xml with small numbers of populations. 

Even if you increase the number of iterations, optimal solution will be found. 

### Expected Behavior

Optimal solution needs to be found regardless of the number of initial population. 

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue checklist is good.
