### ISSUE TITLE
Better error message when extraneous inputs are passed as <Input> of the Code interface

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#198]
--------
Issue Description
--------
##### What did you expect to see happen?
We received the following question on the user list:
----------------------------------------------
Hi RAVEN users,

I am having troubles to have RAVEN MultipleRuning RELAP5-3D.

The RELAP5 input file I am unsuccesfully run is "ans79.i: one of the RELAP5 input files provided with the installation CD and used also to certify the installation.

Using the following input file, I would like to:
Vary both the total power and the initial pressure inside the pipe,
Run 10 RELAP5 cases,
Plot some results - both pointset and historyset types

The actual result is an error message which is not really clear, could you please help me understand what I am doing wrong?

<?xml version="1.0" ?>
<Simulation verbosity="debug">

  <RunInfo>
    <JobName>ForwardSampl_ans79</JobName>
    <WorkingDir>.</WorkingDir>
    <batchSize>4</batchSize>
    
    <Sequence>GenerateData,writePointSet,writehistory</Sequence>
  </RunInfo>

  <TestInfo>
    <name>RavenMultipleRunRelap5</name>
    <author>av</author>
    <created>2017-05-22</created>
  </TestInfo>

  <Files>
    <Input name="inputFile"   type="" >ans79.i</Input>
    <Input name="tpfh2o"      type="" >tpfh2o</Input>
    <Input name="license"     type="" >rellic.bin</Input>
  </Files>

  <Models>
    <Code name="r5model" subType="Relap5">
      <executable>./relap5.x</executable>
      <clargs type="text" arg=" -r restrt.r"/>
    </Code>
  </Models>

  <Steps>
    <MultiRun name="GenerateData">
      <Sampler class="Samplers"    type="MonteCarlo"   >myMC</Sampler>

      <Input   class="DataObjects" type="PointSet"     >DummyIN</Input>
      
      <Input    class="Files"   type=""     >inputFile</Input>
      <Input    class="Files"   type=""     >tpfh2o</Input>
      <Input    class="Files"   type=""     >license</Input>
      
      <Model    class="Models"  type="Code" >r5model</Model>
      
      <Output   class="DataObjects"  type="PointSet"  >pointValues</Output>
      <Output   class="DataObjects"  type="HistorySet">history</Output>
    </MultiRun>
    
    <IOStep name="writePointSet" pauseAtEnd="True">
        <Input class="DataObjects" type="PointSet">pointValues</Input>
        <Output class="OutStreams" type="Print">history</Output>
        <Output class="OutStreams" type="Plot">historyPlot</Output>
    </IOStep>
    
    <IOStep name="writehistory" pauseAtEnd="True">
        <Input class="DataObjects" type="HistorySet">history</Input>
        <Output class="OutStreams" type="Print">history</Output>
        <Output class="OutStreams" type="Plot">historyPlot</Output>
    </IOStep>
  </Steps>

  <Distributions>
    <Normal name="Normal">
      <mean>1.0e+6</mean>
      <sigma>2.5e+4</sigma>
      <lowerBound>9.95e+5</lowerBound>
      <upperBound>1.05e+6</upperBound>
    </Normal>
    
    <Uniform name="Uniform">
      <lowerBound>7.0e+6</lowerBound>
      <upperBound>7.5e+6</upperBound>
    </Uniform>
  </Distributions>

  <Samplers>
    <MonteCarlo name="myMC">
      <samplerInit>
        <limit>10</limit>
      </samplerInit>
      
      <variable name="30000001:2">
        <distribution>Normal</distribution>
      </variable>
      <variable name="0031201:2">
        <distribution>Uniform</distribution>
      </variable>
      
    </MonteCarlo>
  </Samplers>

  <DataObjects>
    <PointSet name="DummyIN">
      <Input>30000001:2,0031201:2</Input>
    </PointSet>

    <PointSet name="pointValues">
      <Input>30000001:2,0031201:2</Input>
      <Output>rktpow,rkreaqc</Output>
    <options>
      <outputRow>-3</outputRow>
    </options>
    </PointSet>
    
    <HistorySet name="history">
      <Input>30000001:2,0031201:2</Input>
      <Output>time,rkfipow_0,rkgapow_0,rkreac_0</Output>
    </HistorySet>
  </DataObjects>

  <OutStreams>
    <Print name="pointValues">
      <type>csv</type>
      <source>pointValues</source>
    </Print>
    
    <Print name="history">
      <type>csv</type>
      <source>history</source>
    </Print>
    
    <Plot   name="historyPlot" verbosity="debug">
      <plotSettings>
        <plot>
          <type>line</type>
          <x>history|Output|time</x>
          <y>history|Output|rkfipow_0</y>
          <c>blue</c>
        </plot>
        <plot>
          <type>line</type>
          <x>history|Output|time</x>
          <y>history|Output|rkgapow_0</y>
          <c>red</c>
        </plot>
        <plot>
          <type>line</type>
          <x>history|Output|time</x>
          <y>history|Output|rkreac_0</y>
          <c>yellow</c>
        </plot>
        <xlabel>time (s)</xlabel>
        <ylabel>power (W)</ylabel>
      </plotSettings>

      <actions>
        <how>png,screen</how>
        <title>
          <text> </text>
        </title>
      </actions>
    </Plot>
    
    <Plot  name="myPlot">
      <plotSettings>
        <plot>
          <type>scatter</type>
          <x>pointValues|Input|30000001:2</x>
          <y>pointValues|Input|0031201:2</y>
          <z>pointValues|Output|rktpow_0</z>
          <colorMap>pointValues|Output|rkreaqc_0</colorMap>
        </plot>
        <xlabel>Total Power - input (W)</xlabel>
        <ylabel>Pipe Initial Pressure (psi)</ylabel>
        <zlabel>Total Power - output (W)</zlabel>
      </plotSettings>
      <actions><how>png,screen</how></actions>
    </Plot>
  
  </OutStreams>

</Simulation>

Error message:
(    0.03 sec) STEP MULTIRUN            : DEBUG           -> jobHandler initialized
Traceback (most recent call last):
  File "/home/av_ale/raven/framework/Driver.py", line 278, in <module>
    raven()
  File "/home/av_ale/raven/framework/Driver.py", line 231, in raven
    simulation.run()
  File "/home/av_ale/raven/framework/Simulation.py", line 1051, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/av_ale/raven/framework/Steps.py", line 235, in takeAstep
    self._initializeStep(inDictionary)
  File "/home/av_ale/raven/framework/Steps.py", line 191, in _initializeStep
    self._localInitializeStep(inDictionary)
  File "/home/av_ale/raven/framework/Steps.py", line 462, in _localInitializeStep
    SingleRun._localInitializeStep(self,inDictionary)
  File "/home/av_ale/raven/framework/Steps.py", line 335, in _localInitializeStep
    inDictionary['Model'].initialize(inDictionary['jobHandler'].runInfoDict,inDictionary['Input'],modelInitDict)
  File "/home/av_ale/raven/framework/Models.py", line 1440, in initialize
    shutil.copy(inputFile.getAbsFile(),self.workingDir)
AttributeError: 'PointSet' object has no attribute 'getAbsFile'
------------------------------------------------------------------------------

##### What did you see instead?

The code should error out in a more understandable way when extraneous inputs are passed as Input of the Step.

##### Do you have a suggested fix for the development team?

Check

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [X] 1. Is it tagged with a type: defect or improvement? ***improvement***
- [X] 2. Is it tagged with a priority: critical, normal or minor? ***normal***
- [X] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***n/a***
- [X] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. ***n/a***
- [X] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***yes***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***improvement***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)   ***improvement***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?  ***improvement***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?  ***improvement***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?  ***PR #205***

**Comment by alfoa** [comment]
Closure list passed...
