### ISSUE TITLE
Ensemble Model Tests

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#201]
--------
Issue Description
--------
##### What did you expect to see happen?

The test cases for the EnsembleModel do not specify the "inputs" into each model correctly. The offending cases are:

- ensembleModelTests/test_ensemble_model_picard_thread.xml
- ensembleModelTests/test_ensemble_model_picard_parallel.xml
- ensembleModelTests/test_ensemble_model_linear_with_multiple_lateral_insertions.xml
- ensembleModelTests/test_ensemble_model_linear_threading_with_code.xml

As is, the code needed a special if conditional in the EnsembleModel to handle `Code` and everything else (only `ExternalModel` is currently under test) differently:

```python
if self.modelsDictionary[modelIn]['Instance'].type == 'Code':
  self.modelsDictionary[modelIn]['Instance'].submit(originalInput[modelIn], samplerType, jobHandler, **copy.deepcopy(inputKwargs[modelIn]))
else:
  self.modelsDictionary[modelIn]['Instance'].submit([inputKwargs], samplerType, jobHandler, **copy.deepcopy(inputKwargs[modelIn]))
```

This should not be the case, however since everything should be able to appropriately handle the input to the first case.

##### What did you see instead?

As pointed out by @AaronEpiney, if you use a `ROM` model inside an `EnsembleModel` this if conditional will cause the program to break.

##### Do you have a suggested fix for the development team?

Because there are a few tests that do not have the correct input space determined, we must alter a few existing test cases and remove the if conditional on the EnsembleModel so that every model is treated the same way.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

With the corrected code in place, the errors are existent in tests/framework already (see above). So, the defect in this case is in the input test cases in tests/framework, and the improvement is to handle all `Models` agnostic of their type in the `EnsembleModel`.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.  __Defect is in test input files__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***improvement***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) ***improvement***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***improvement***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***improvement***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***PR #202***

**Comment by alfoa** [comment]
Checklist passed...
