### ISSUE TITLE
[DEFECT] Adaptive MonteCarlo crashes if failure occurs at the begin of an evaluation

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#2027]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [x] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

If a sampling fails in the first iterations, the adaptive Montecarlo crashes when a "successful" model evaluation is achieved. This is due to the fact that the convergence is checked on ```nan``

### Steps to Reproduce

create a model that fails the first run and the code will crash.

### Expected Behavior

since it is a "Montecarlo" it should neglect the failure and go on.

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue closure checklist is satisfied.
