### ISSUE TITLE
[UNDER-DISCUSSION] Hausdorff Similarity Measure - GA convergence

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#2032]
--------
Under Discussion Topic
--------

**Summary of the topic to be discussed with the development team**
The convergence criteria for the GA algorithms "require" an idea of the variability of the objective function in the search domain, since they are based on the Hausdorff Distance-based metrics. Such distances are "absolute distances" and consequentially the convergence criteria needs to be "adjusted" performing a preliminary "exploration" of the space (e.g. via sampling) to have an idea of such variability.

**Describe the solution you'd like to be implemented**
My suggestion is to implement a convergence metrics still based on Hausdorff Distance but that takes in consideration the "not knowledge" of the variability of the objective.  An example can be a normalized metric called  Hausdorff Similarity Measure. An example of the implementation is at:

https://github.com/locationtech/jts/blob/e1767327209a6ee331a55186177b12373fb8419c/modules/core/src/main/java/org/locationtech/jts/algorithm/match/HausdorffSimilarityMeasure.java

**Describe alternatives you've considered**
Run first for some iterations...get an idea of the AHD and then use that to tune the converge criterion.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with the under_discussion type?
- [x] 2. If implemented, it will add a new requirement?
- [x] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by aalfonsi** [comment]
@mandd @Jimmy-INL @wangcj05

**Comment by Jimmy-INL** [comment]
Thanks, @aalfonsi, I will take a look at Hausdorff Similarity as soon as I can. I agree with your comment about space exploration, I believe we suggested that a few months ago.
