### ISSUE TITLE
[DEFECT] Input variables in Opt must always be present in SolutionExport

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#2039]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [ ] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

The optimization variables should always be present among the variables of the SolutionExport.
If this is not the case, the Optimizer crashes because the useRealization method tries to find a match of variables that do not exist in the list of variables belonging to the Dataobject.

### Steps to Reproduce

- Creation of a input case that uses GradientDescent, has a SolutionExport
- From the <Output> section of the SolutionExport remove input variables
- Run

### Expected Behavior

Better error handling informing me that a certain variable is not present in the list of variables of the SOlutionExport data object

### Screenshots and Input Files

![Screen Shot 2023-01-13 at 3 45 03 PM](https://user-images.githubusercontent.com/26668536/212433059-aa4b4ab4-8068-4bc8-887b-8e0990d92773.png)

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue closure checklist is satisfied. Issue can be closed with PR #2040
