### ISSUE TITLE
[DEFECT] Optimizers cannot be "initialized" with CustomSampler <Source> Files

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#2060]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Initial points (for Gradient Descent) and initial population (Genetic algorithm and Simulating annealing) cannot be
set with a ```CustomSampler``` of type ```Files```. E.g. Custom sampler defined as follows:

```
  <Samplers>
    <CustomSampler name="restartSampler">
      <Source class="Files" type="">restart.csv</Source>
      <variable name="x"/>
      <variable name="y"/>
      <variable name="z"/>
    </CustomSampler>
  </Samplers>
```
If used in the Optimizers the following crash is detected:
```
Traceback (most recent call last):
  File "./raven/raven_framework.py", line 25, in <module>
    sys.exit(main(True))
  File "./raven/ravenframework/Driver.py", line 207, in main
    raven()
  File "./raven/ravenframework/Driver.py", line 160, in raven
    simulation.run()
  File "./raven/ravenframework/Simulation.py", line 890, in run
    self.executeStep(stepInputDict, stepInstance)
  File "./raven/ravenframework/Simulation.py", line 823, in executeStep
    stepInstance.takeAstep(stepInputDict)
  File "./raven/ravenframework/Steps/Step.py", line 314, in takeAstep
    self._initializeStep(inDictionary)
  File "./raven/ravenframework/Steps/Step.py", line 247, in _initializeStep
    self._localInitializeStep(inDictionary)
  File "./raven/ravenframework/Steps/MultiRun.py", line 100, in _localInitializeStep
    self._initializeSampler(inDictionary)
  File "./raven/ravenframework/Steps/MultiRun.py", line 72, in _initializeSampler
    inDictionary[self.samplerType].initialize(**self._samplerInitDict)
  File "./raven/ravenframework/Optimizers/GeneticAlgorithm.py", line 387, in initialize
    RavenSampled.initialize(self, externalSeeding=externalSeeding, solutionExport=solutionExport)
  File "./raven/ravenframework/Optimizers/RavenSampled.py", line 160, in initialize
    Optimizer.initialize(self, externalSeeding=externalSeeding, solutionExport=solutionExport)
  File "./raven/ravenframework/Optimizers/Optimizer.py", line 301, in initialize
    self._initializeInitSampler(externalSeeding)
  File "./raven/ravenframework/Optimizers/Optimizer.py", line 406, in _initializeInitSampler
    self._initSampler._localGenerateAssembler(samplerInit)
  File "./raven/ravenframework/Samplers/CustomSampler.py", line 155, in _localGenerateAssembler
    self.assemblerDict[key].append([entity, etype, name, initDict[entity][name]])
KeyError: 'Files'
```

No problems if a DataObject is used in the CustomSampler:

```
  <Samplers>
    <CustomSampler name="restartSampler">
      <Source class="DataObjects" type="PointSet">restart</Source>
      <variable name="x"/>
      <variable name="y"/>
      <variable name="z"/>
    </CustomSampler>
  </Samplers>
```

### Steps to Reproduce

Create a restart case with GA or GD using a custom sampler with ```<Source>``` == ```<Files>```

### Expected Behavior

No crash :D 

### OS

Linux

### Dependency Manager

PIP

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@mandd @Jimmy-INL @JunyungKim I have assigned this issue to you, please make a plan to resolve it in the near future. Thanks for your help.

**Comment by mandd** [comment]
@wangcj05 : I am on it

**Comment by Jimmy-INL** [comment]
On it.
Best,

Mohammad G. Abdo, Ph.D.
Modeling and Simulation Scientist   |  Digital Reactor Technology and Development (C160)
Reactor Systems Design and Analysis   |   NS&T
***@***.******@***.***>   |  REC EROB IF-654 3EM402  |  Phone: 208-526-4640
Idaho National Laboratory   |   2525 Fremont Ave.   |   Idaho Falls, ID   |   83415
[6GC4jc7QCCEAAAAASUVORK5CYII=]<https://www.linkedin.com/in/mohammad-abdo-a7625082/>.               [PXly9OZ1PK9LcRv4PSG3pAb9jevQAAAAASUVORK5CYII=] <https://www.researchgate.net/profile/Mohammad_Abdo/research>                 [RPr5ytnPx9Cc691m9I+4T+nIo7v4HxgxndxMwKP8AAAAASUVORK5CYII=] <https://github.com/Jimmy-INL>
___________________________________
[wYtJH347IiIiAYVYS1skEvgxC4KpkYRTFRBbsT51peEIp5j0ExRuvWouzr1J+za4DYirM+SlQmTZXUTsvjtVtouILWngWSxC+xJbAP86Fg5oVmy2ERH1w38A8nnHfeT8na8AAAAASUVORK5CYII=]


From: Congjian Wang - INL ***@***.***>
Date: Monday, February 20, 2023 at 10:37 AM
To: idaholab/raven ***@***.***>
Cc: Mohammad G. Abdo ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/raven] [DEFECT] Optimizers cannot be "initialized" with CustomSampler <Source> Files (Issue #2060)

@mandd<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmandd&data=05%7C01%7Cmohammad.abdo%40inl.gov%7C5e2ef9ba7d1344b6e1ea08db13692cec%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C638125114703980102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X%2B0Thlrv%2FNQmOSPZlfhBrSNi6aaFdtQRWHZXTmsnw88%3D&reserved=0> @Jimmy-INL<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJimmy-INL&data=05%7C01%7Cmohammad.abdo%40inl.gov%7C5e2ef9ba7d1344b6e1ea08db13692cec%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C638125114703980102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oA9VWvA531RH7GOZZLe48JdyteTii%2FNVAtB6thVK2F8%3D&reserved=0> @JunyungKim<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJunyungKim&data=05%7C01%7Cmohammad.abdo%40inl.gov%7C5e2ef9ba7d1344b6e1ea08db13692cec%7C4cf464b7869a42368da2a98566485554%7C0%7C0%7C638125114703980102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XQePiO%2FTEHEiB1KnFGW9WhpdtRUw4dVtunxLGVIwAsQ%3D&reserved=0> I have assigned this issue to you, please make a plan to resolve it in the near future. Thanks for your help.

**Comment by mandd** [comment]
@aalfonsi: check this branch: mandd/GAwithCustomsampler
The added test file 
testGAMaxwRep_custom_sampler.xml
runs on my machine

**Comment by aalfonsi** [comment]
@mandd Diego tested (also in one of my test cases that was not working before). It works. Thanks a lot for taking care of this.

**Comment by wangcj05** [comment]
Issue closure checklist is satisfied.
