### ISSUE TITLE
Cannot load plugins if pytest is installed

### ISSUE THREAD

**Issue by cbroman-usnctech** [idaholab/raven#2074]
--------
Issue Description
--------
##### What did you expect to see happen?
Installed plugins should load independent of `pytest` being installed.

##### What did you see instead?
PluginManager unable to load plugins. If `pytest` is uninstalled then the plugins load fine.

##### Do you have a suggested fix for the development team?
Installing ravenframework as editable fixes this issue, but that is not an option for some. 
A configuration to pytest might be required. 
I suspect something in PluginManager line 159 to be the culprit. Instead of `__file__` returning the path within the directory it is returning the path to the virtual environment and is unable to find the relative path to `plugin_directory.xml`. I would suggest using absolute file paths based on the installation directory.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
Installed ravenframework with pip. 
```
$ cd raven
$ pip install .
$ pip install pytest
$ python
 import ravenframework
 from ravenframework import PluginManager
```

output
![image](https://user-images.githubusercontent.com/117781350/219548314-0a412654-2367-4a39-ba87-a8969e3de32d.png)

```
$ pip uninstall pytest
$ python
 import ravenframework
 from ravenframework import PluginManager
```
output

![image](https://user-images.githubusercontent.com/117781350/219548492-14cc2570-8ea8-44f5-9022-ca4467c22661.png)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
FYI: `PluginFactory: No installed plugins detected.` is also listed in this issue:
https://github.com/gmlc-dispatches/dispatches/issues/173

**Comment by joshua-cogliati-inl** [comment]
Hm, after looking at the code, I am not sure how pytest could affect this at all.

For the time being, if you install RAVEN with pip, we recommend you install any plugins you use with pip as well (Currently only TEAL and HERON are supported with a pip install, let us know if you are trying to install something else with pip.)

**Comment by cbroman-usnctech** [comment]
@joshua-cogliati-inl  
I'm not certain about why installing pytest affects this import location. Did you try to reproduce the error? Something is changing the directory before `__file__` is called though. 

I can fix the error by adding: 

`filePath = os.path.dirname(__file__)`

to line 32 of `raveframework/PluginManager.py`

then change line 159 to read like:

`pluginsPath = os.path.join(filePath, '..', 'plugins')`

and reinstall ravenframework (pip install) it has no problem importing plugins. 

![image](https://user-images.githubusercontent.com/117781350/220209702-065009db-f190-47f8-b742-56052a393b1b.png)

**Comment by joshua-cogliati-inl** [comment]
Basically, there are three ways we run the install:
1. `./scripts/establish_conda_env.sh --install --installation-manager PIP` and then `./build_raven` https://github.com/idaholab/raven/wiki/installationAdvanced#standard-pip-install
2. `./scripts/establish_conda_env.sh --install` and then `./build_raven`
3. `pip install raven_framework` (where the packages are created with `python -m build` )

If you are doing the 3rd way, then we expect that somehow you have the raven plugins in the regular PYTHONPATH, and in that case, `PluginFactory: No installed plugins detected.` is an incorrect warning since in that case the plugins should already be in the PYTHONPATH and we shouldn't need the pluginsPath to be setup.

You have managed to try a 4th way to install, so if you got it to work at all, congratulations. If you want to submit a pull request that makes the changes to PluginManager that is fine with me.  Thank you.

**Comment by joshua-cogliati-inl** [comment]
```$ python3.8 -m pip uninstall pytest
Found existing installation: pytest 7.2.1
...
  Successfully uninstalled pytest-7.2.1
$ python3.8
Python 3.8.16 (default, Dec  7 2022, 00:00:00) 
[GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ravenframework
>>> from ravenframework import PluginManager
PluginFactory: No installed plugins detected.
```
pytest does not seem to affect this at all.

**Comment by cbroman-usnctech** [comment]
@joshua-cogliati-inl  re:https://github.com/idaholab/raven/issues/2074#issuecomment-1437674792 

My issue only occurs when `pytest` is uninstalled, shouldn't you be able to load the `Example Plugin`? 

To install RAVEN I am running the following commands:
`./scripts/establish_conda_env.sh --install`
`./build_raven`

Install plugins with: 
`./scrpits/install_plugins.py -s path/to/plugin/myPlugin.py`

install RavenFramework with 
`pip install .`

**Comment by joshua-cogliati-inl** [comment]
Hm, if you install it that way, you should have two ravenframeworks installed, one from `./build_raven` and one from `pip install .`  Do you know which one your `import ravenframework` found?  (as in what was `ravenframework.__file__` )

For my test I assumed that you hadn't run establish conda or build raven.

**Comment by cbroman-usnctech** [comment]
Exactly right @joshua-cogliati-inl !
```
$ import ravenframework
$ ravenframework.__file__
bin/miniconda/envs/ravenEnv/lib/python3.8/site-packages/ravenframework/__init__.py
```

which is the path to the pip installed module and does not lend itself to finding the plugins, because they are outside of the framework @ `raven/plugins/plugin_directory.xml`

However, if the above ^^^ mentioned changes are implemented to the `PluginManager`. The assignment and placement of `__file__` in this circumstance is fixed to the `raven/__init__.py` , and it doesnt matter if `ravenframework` can is loaded from a library.

**Comment by joshua-cogliati-inl** [comment]
@cbroman-usnctech  I made a branch with your suggested fix.

**Comment by cbroman-usnctech** [comment]
Thank you @joshua-cogliati-inl

**Comment by wangcj05** [comment]
issue closure checklist is good.

**Comment by cbroman-usnctech** [comment]
@wangcj05 @joshua-cogliati-inl 
Well, this is embarrassing. I pulled the latest changes from `devel` and reinstalled ravenframework using.

```
$ cd raven
$ pip install .
$ python
> import ravenframework
> from ravenframework import PluginManager
Loading plugin "ExamplePlugin" at /home/cbroman/git/raptor/third-party/raven/plugins/ExamplePlugin
 ... successfully imported "ExamplePlugin" ...
Loading plugin "_raven" at /home/cbroman/git/raptor/src/raptor/_raven
 ... successfully imported "_raven" ...
Loading plugin "RaptorRavenInterface" at /home/cbroman/git/raptor/src/raptor/_ext/RaptorRavenInterface
 ... successfully imported "RaptorRavenInterface" ...
```
All plugins were found! This is with `pytest` installed. 

However, when I tried running from a different directory (not within raven) PluginManager is still unable to load plugins. :( 
I'm sorry, but it seems this issue is still open.

**Comment by cbroman-usnctech** [comment]
@joshua-cogliati-inl thank you for the run down. 

In the past I have purely used method `1` from above to install RAVEN and the plugins and it works great. 

My back story is now we want to test our plugin with our own set of unit tests to assure proper functionality. I can't directly import our plugin from within our own framework because RAVEN plugin package requires an  `__init__.py` file specifying `from package_name.src import pluginModule` which breaks the import structure from within a framework. If I could use the `ravenframework PluginManager` to import the plugin that would fix the issue, but that requires installing `ravenframework` with pip which apparently (and by design) messes up the RAVEN PluginManger path dependencies. So, I keep hitting dead ends, I can add some conditional statements in my `__init__.py` file to fix it, it's just not ideal. 

My two cents are that this should be addressed because the framework installation is leaving out essential datafiles (namely `plugins.plugin_directory.xml`).

**Comment by aalfonsi** [comment]
@joshua-cogliati-inl @cbroman-usnctech maybe the usage of ```[options.package_data]``` (in setup.cfg) can be useful to make sure all the essential datafiles (e.g. plugin_directory.xml) are stored in the package? 

(And then, it can be loaded using ```pkg_resources``` -> ```pkg_resources.resource_stream(path_to_file_in_package)```

**Comment by joshua-cogliati-inl** [comment]
The problem is that if we install a  plugin_directory.xml it may very well be installed read only, so this is not the solution.  I will write up some documentation on how we created our plugins to work with RAVEN and pip.

**Comment by joshua-cogliati-inl** [comment]
I started documentation on how we do the TEAL pip package: https://github.com/idaholab/raven/wiki/Plugins#pip-plugins

**Comment by cbroman-usnctech** [comment]
Thank you @joshua-cogliati-inl   this is great!

**Comment by joshua-cogliati-inl** [comment]
Okay, let me know if there are things I need to add to the documentation.

**Comment by wangcj05** [comment]
@cbroman-usnctech @joshua-cogliati-inl Can this issue be closed?

**Comment by cbroman-usnctech** [comment]
@wangcj05 Yes, thank you, we have a workaround now.
