### ISSUE TITLE
Process Failed <ravenframework.Runners.SharedMemoryRunner.SharedMemoryRunner

### ISSUE THREAD

**Issue by morsi95** [idaholab/raven#2080]
--------
Issue Description
--------
##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[Errorlog.txt](https://github.com/idaholab/raven/files/10801937/Errorlog.txt)
[XMLfile.txt](https://github.com/idaholab/raven/files/10801942/XMLfile.txt)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by mandd** [comment]
@morsi95 : would it be possible for you to share also the .i file of your moose based app?

**Comment by morsi95** [comment]
[PT_th1.txt](https://github.com/idaholab/raven/files/10813983/PT_th1.txt)

**Comment by morsi95** [comment]
[PT.txt](https://github.com/idaholab/raven/files/10813988/PT.txt)

**Comment by mandd** [comment]
@morsi95: the input file you have provided contains these variables 
   circle_center_x = 4466938.77
   circle_center_y = 5331319.025
   circle_radius = 3000
that defined outside a nodel.
This is is a syntax that do match our parser design.
Things get fixed if you insert these vars into a node:
[ExtVars]
   circle_center_x = 4466938.77
   circle_center_y = 5331319.025
   circle_radius = 3000
[]

**Comment by PaulTalbot-INL** [comment]
Improved solution in #2274.
