### ISSUE TITLE
[TASK] Support PIP installation mode with HERON

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2090]
--------
Issue Description
--------
Currently, regression tests do not work with HERON does not work with PIP installation mode:

```
Output of 'civet/build_0/raven/plugins/HERON/tests/integration_tests/mechanics/labels/Labels':
Starting HERON ...
pip_envs/raven_libraries/lib/python3.8/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
 ... RAVEN located at "civet/build_0/raven"
 ... Activating CONDA environment ...
CONDA
... Conda definitions not found at "miniconda2/etc/profile.d/conda.sh"!
... >> Specify the location of miniconda3/etc/profile.d/conda.sh through the --conda-defs option.

Running test failed with exit code 1
(7F5/39) Failed (  0.39sec)civet/build_0/raven/plugins/HERON/tests/integration_tests/mechanics/labels/Labels
```

**Describe the solution you'd like**
It would be nice if when running the tests, it used the .ravenrc to figure out which installation mode was being used.

**Describe alternatives you've considered**
Pass the installation mode some other way.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue closure checklist is good.
