### ISSUE TITLE
[TASK] Allow ExternalModels to return string data

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2096]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Sometimes it would be useful for an ExternalModel to return some string data.

Currently this results in:
```
(    0.00 sec) EXTERNAL MODEL           : DEBUG           -> Unsupported type found. Available ones are: 'float', 'bool', 'int', 'ndarray', 'c1darray', 'float16', 'float32', 'float64', 'float128', 'int16', 'int32', 'int64', 'bool8', 'numpy.float', 'numpy.bool', 'numpy.int', 'numpy.ndarray', 'numpy.c1darray', 'numpy.float16', 'numpy.float32', 'numpy.float64', 'numpy.float128', 'numpy.int16', 'numpy.int32', 'numpy.int64', 'numpy.bool8'
(    0.00 sec) EXTERNAL MODEL           : DEBUG           -> variable code has an unsupported type -> str
```

**Describe the solution you'd like**
Extend ExternalModel to support str

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
checklist is good.
