### ISSUE TITLE
[DEFECT] UnorderedCSVDiffer test is outdated

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#2126]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

The `TestUnorderedCsvDiffer` for the `UnorderedCsvDiffer` in RAVEN to extend rook is not functioning. There are pathing issues and missing test CSVs.

Does not cause wrong solutions or impact users directly.

### Steps to Reproduce

Run `TestUnorderedCSV.py` in `raven/scripts/TestHarness/testers`

### Expected Behavior

Successfully test efficacy of UCSV differ

### OS

MacOS

### OS Version

13.4

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Since this is just a testing issue, this can't cause wrong results, so I don't think any email notification needs to be sent.
