### ISSUE TITLE
[DEFECT] install fails with --no-mamba 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2141]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [ ] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

The install fails with --no-mamba on a new install.

https://civet.inl.gov/job/1627254/
```

Remove all packages in environment /home/civet/.conda/envs/raven_libraries:

BUILD_ROOT/raven/: scripts/establish_conda_env.sh --install --conda-defs /home/civet/miniconda2/etc/profile.d/conda.sh --no-mamba
... not using mamba
CONDA
... Run Options:
... ECE Mode: 2
... Verbosity: 0
... Clean: 0
... Install Mode: CONDA
... Conda Defs: /home/civet/miniconda2/etc/profile.d/conda.sh
... Installing RAVEN libraries ...
... Detected OS as --os linux ...
... Using Python command python
... RAVEN library name set through $RAVEN_LIBS_NAME global variable.
... >> If this is not desired, then unset the variable before running.
... >> RAVEN environment is named "raven_libraries"
... Found conda definitions at /home/civet/miniconda2/etc/profile.d/conda.sh
conda 4.8.2

raven_libraries_alt      /home/civet/.conda/envs/raven_libraries_alt
                         /home/civet/miniconda3/envs/raven_libraries
... Found library environment ...
... Removing old environment ...
... Installing libraries ...
... Installing libraries from conda-forge ...
/home/civet/miniconda2/bin/python
... conda-forge command: conda install --name raven_libraries -y -c conda-forge dill=0.3.5 netcdf4=1.5 cloudpickle=2.2 numpy-financial coincbc=2.10.5 xarray=2023 networkx pip pyomo=6.4 numexpr lxml nomkl pyutilib tensorflow=2.10 fmpy numpy=1.22 pandas=1.3 python=3 swig pylint matplotlib=3.5 h5py scipy=1.7 coverage glpk cvxpy imageio=2.22 hdf5 scikit-learn=1.0 psutil setuptools statsmodels=0.13 importlib_metadata ipopt

EnvironmentLocationNotFound: Not a conda environment: /home/civet/.conda/envs/raven_libraries


ERROR: exiting with code 1
```

### Steps to Reproduce

On a fresh install:
`./scripts/establish_conda_env.sh --install  --no-mamba`

### Expected Behavior

Install should work.

### OS

Linux

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue closure checklist is good, can issue can be closed with pr#2142
