### ISSUE TITLE
[TASK] Issue finding tensorflow during Install RAVEN libraries for Mac M2

### ISSUE THREAD

**Issue by yoshiurr-INL** [idaholab/raven#2158]
--------
Under Discussion Topic
--------
**Machine Specification**
Equipment: MacBook Pro
OS: Ventura 13.5
Processor: Apple M2 Max
<img width="476" alt="Screenshot 2023-07-27 at 12 28 32 PM" src="https://github.com/idaholab/raven/assets/78757932/d7f6bdbb-21ed-445d-823b-140ddc0bc187">

**Summary of the topic to be discussed with the development team**
While installing RAVEN libraries using "--install", the pip install for tensorflow cannot find a version that satisfies the requirements of tensorflow==2.10.*
<img width="577" alt="Screenshot 2023-07-27 at 12 19 29 PM" src="https://github.com/idaholab/raven/assets/78757932/9b7a1ddd-3c89-4c49-8b05-6b619ca3500e">
<img width="577" alt="Screenshot 2023-07-27 at 12 19 58 PM" src="https://github.com/idaholab/raven/assets/78757932/8a016e82-7886-4df9-8c01-47d20db5fe3a">
<img width="1244" alt="Screenshot 2023-07-27 at 12 20 41 PM" src="https://github.com/idaholab/raven/assets/78757932/cc269e78-245e-41a2-95d9-7681d7071b9d">

When trying to use "--mamba" instead, the installation process does not start.
<img width="658" alt="Screenshot 2023-07-27 at 12 21 11 PM" src="https://github.com/idaholab/raven/assets/78757932/57c6d8f8-d8d1-4de2-a9e0-6eb0d35237ea">

**Describe the solution you'd like to be implemented**
Identify whether this issue is common for Mac systems.
Identify whether this issue is common for M1 and M2 chips.

**Describe alternatives you've considered**
Maybe conda installing tensorflow?

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Hm, if you change the line in the dependencies.xml from:
`<tensorflow source="pip" os='mac,linux'>2.10</tensorflow>`
to
`<tensorflow os='mac,linux'>2.10</tensorflow>`
does it install?

(Note that we do not currently have automated testing on arm64)

**Comment by wanghy-anl** [comment]
@joshua-cogliati-inl Joshua, I found the identical issue on my M1 MacBook Pro 13 inch (OS: Ventura 13.5; Processor: Apple M1), just like Ramon experienced.

I tried to edit the `dependencies.xml` as you suggested, and the conda environment can be established by `./scripts/establish_conda_env.sh --install`.

However, after `./build_raven` and `./run_tests -j4`, 23 tests are marked as "Diff" or "Failed". See the attached log file.

Haoyu
[log_run_test_j4_20230802.log](https://github.com/idaholab/raven/files/12242694/log_run_test_j4_20230802.log)

> Hm, if you change the line in the dependencies.xml from: `<tensorflow source="pip" os='mac,linux'>2.10</tensorflow>` to `<tensorflow os='mac,linux'>2.10</tensorflow>` does it install?
> 
> (Note that we do not currently have automated testing on arm64)

**Comment by joshua-cogliati-inl** [comment]
Okay, so we can install it if we switch tensorflow back to conda-forge, but it fails some tests. I think the correct solution for this is probably to switch to a newer version of tensorflow.

**Comment by wanghy-anl** [comment]
Thanks Joshua. Let me know if you have any candidate versions in your mind. I can test on my M1 machine (it's idle recently)

> Okay, so we can install it if we switch tensorflow back to conda-forge, but it fails some tests. I think the correct solution for this is probably to switch to a newer version of tensorflow.

**Comment by joshua-cogliati-inl** [comment]
Tensorflow 2.12 and 2.13 might be worth trying.

**Comment by joshua-cogliati-inl** [comment]
I started testing tensorflow 2.12 in https://github.com/idaholab/raven/pull/2138 but we need a few updates for it.

**Comment by wanghy-anl** [comment]
@joshua-cogliati-inl, here are the results:
Using 2.12 (I modified Line 49 of `dependencies.xml` to `<tensorflow os='mac,linux'>2.12</tensorflow>`: Can establish conda environment, but has 14 Failed tests and 16 Diff tests, see log below;
[log_run_test_j4_tensorflow_2_12_2023AUG03.log](https://github.com/idaholab/raven/files/12254702/log_run_test_j4_tensorflow_2_12_2023AUG03.log)

Using 2.13 (Only available through PIP channel, I modified Line 49 of `dependencies.xml` to `<tensorflow source="pip" os='mac,linux'>2.13</tensorflow>`: Can establish conda environment, but has 673 Failed tests, see log below;
[log_run_test_j4_tensorflow_2_13_2023AUG03.log](https://github.com/idaholab/raven/files/12254736/log_run_test_j4_tensorflow_2_13_2023AUG03.log)

> Tensorflow 2.12 and 2.13 might be worth trying.

**Comment by joshua-cogliati-inl** [comment]
Hm, for 2.13, something is being done incorrectly:
```
ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
```

**Comment by wanghy-anl** [comment]
Is there anything we can do within raven's `establish_conda_env.sh` script?



> Hm, for 2.13, something is being done incorrectly:
> 
> ```
> ImportError: Failed to import grpc on Apple Silicon. On Apple Silicon machines, try `pip uninstall grpcio; conda install grpcio`. Check out https://docs.ray.io/en/master/ray-overview/installation.html#m1-mac-apple-silicon-support for more details.
> ```

**Comment by joshua-cogliati-inl** [comment]
It might be worth adding 'grpcio' as a conda dependency and see if that solves it.

**Comment by joshua-cogliati-inl** [comment]
Otherwise, yes, we might need to modify `establish_conda_env.sh`

**Comment by joshua-cogliati-inl** [comment]
> I added the <grpcio/> to dependencies.xml, and the conda environment can be established, but 14 failed and 16 diff tests. See the dependencies.xml and log attached.

It looks like a bunch of the diff and failed are because of the tensorflow update. So that is probably the first thing that we need to fix.

**Comment by wanghy-anl** [comment]
Joshua, let me know when you need to test the fix. I can do the test on M1 chip.

**Comment by wanghy-anl** [comment]
Joshua, is this `dependencies.xml` in any branch? I can give it a try if you can point me to the correct branch.

**Comment by joshua-cogliati-inl** [comment]
> Joshua, is this `dependencies.xml` in any branch? I can give it a try if you can point me to the correct branch.

I just used the dependencies.xml file you included in your zip file, and I also just updated the https://github.com/idaholab/raven/pull/2138 with 2.13 instead of 2.12

**Comment by wanghy-anl** [comment]
Thanks, I will wait until #2138 gets merged and then test it on M1 chip.

**Comment by joshua-cogliati-inl** [comment]
> Joshua, is this `dependencies.xml` in any branch? I can give it a try if you can point me to the correct branch.

It is on my [joshua-cogliati-inl:tensorflow_212](https://github.com/joshua-cogliati-inl/raven/tree/tensorflow_212) branch that #2138 uses, it would be useful to know if it fixes things on the M1 chip.

**Comment by wanghy-anl** [comment]
> It is on my [joshua-cogliati-inl:tensorflow_212](https://github.com/joshua-cogliati-inl/raven/tree/tensorflow_212) branch that #2138 uses, it would be useful to know if it fixes things on the M1 chip.

Thanks Joshua, Let me give it a try on M1 chip tonight or tomorrow. I will attach the log file here.

**Comment by joshua-cogliati-inl** [comment]
FYI: If anyone uses the diff for the dependencies.xml, do not remove `smt` since that will cause newer versions of RAVEN to fail.

**Comment by wanghy-anl** [comment]
> FYI: If anyone uses the diff for the dependencies.xml, do not remove `smt` since that will cause newer versions of RAVEN to fail.

Josh, you were correct. I deleted `<smt/>` in the attached `dependencies_a.xml` and 694 tests failed on M1 chip. See attached `Log_Sep05_2023_a.log`.
So I re-added `<smt source='pip'/>` in the attached `dependencies_b.xml` and it runs better. 19 tests failed. See attached `Log_Sep05_2023_b.log`.
[Sep_5_2022_Trials.zip](https://github.com/idaholab/raven/files/12540261/Sep_5_2022_Trials.zip)

**Comment by wangcj05** [comment]
[like]  Congjian Wang reacted to your message:
________________________________
From: Joshua J. Cogliati ***@***.***>
Sent: Thursday, September 7, 2023 5:00:13 PM
To: idaholab/raven ***@***.***>
Cc: Congjian Wang ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/raven] [UNDER-DISCUSSION] Issue finding tensorflow during Install RAVEN libraries for Mac M2 (Issue #2158)


Some errors I saw:

File ".../raven/ravenframework/Optimizers/acquisitionFunctions/AcquisitionFunction.py", line 138, in conductAcquisition res = sciopt.differential_evolution(optFunc, bounds=self._bounds, polish=self._polish, maxiter=self._maxiter, tol=self._tol,
TypeError: differential_evolution() got an unexpected keyword argument 'vectorized'

File ".../python3.10/site-packages/netCDF4/__init__.py", line 3, in <module> from ._netCDF4 import
ImportError: dlopen(.../python3.10/site-packages/netCDF4/_netCDF4.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_nc_close'

libc++abi: terminating due to uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::overflow_error>>: Error in function ibeta_derivative<e>(e,e,e): Overflow Error

Also, a bunch of diffs.

I think it is worth trying netcdf 1.6 to see if that fixes the netcdf errors.
I think the floating point hardware must be a bit different and causing the overflow error and some of the diffs.

**Comment by joshua-cogliati-inl** [comment]
So apparently the remaining errors are:
```
FAILED:
Diff tests/framework/redundantInputs
Diff tests/framework/NDGridProbabilityWeightValue
Diff tests/framework/CodeInterfaceTests/CobraTF/test3
Diff tests/framework/pca_sparseGridCollocation/polyCorrelation
Diff tests/framework/PostProcessors/LimitSurface/testLimitSurfaceIntegralPPWithBoundingError
Diff tests/framework/Optimizers/GeneticAlgorithms/simionescuConstrainedInvLin
Diff tests/framework/Samplers/SparseGrid/normal
Failed tests/framework/Samplers/SparseGrid/betanorm
Failed tests/framework/Samplers/SparseGrid/beta
Diff tests/framework/Samplers/SparseGrid/triangular
Diff tests/framework/pca_adaptive_sgc/test_adaptive_sgc_poly_pca_analytic

PASSED: 778
SKIPPED: 93
FAILED: 11
```

I think a lot of those are from differences between how arm64 and amd64 handle floating point numbers. (From what I have seen online, I think basic arithmetic (+-*/) are the same, but things like floating to integer and back are different as well as functions like sin which will give differences eventually)

**Comment by wangcj05** [comment]
[like]  Congjian Wang reacted to your message:
________________________________
From: Joshua J. Cogliati ***@***.***>
Sent: Monday, September 11, 2023 4:39:31 PM
To: idaholab/raven ***@***.***>
Cc: Congjian Wang ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/raven] [UNDER-DISCUSSION] Issue finding tensorflow during Install RAVEN libraries for Mac M2 (Issue #2158)


So apparently the remaining errors are:

FAILED:
Diff tests/framework/redundantInputs
Diff tests/framework/NDGridProbabilityWeightValue
Diff tests/framework/CodeInterfaceTests/CobraTF/test3
Diff tests/framework/pca_sparseGridCollocation/polyCorrelation
Diff tests/framework/PostProcessors/LimitSurface/testLimitSurfaceIntegralPPWithBoundingError
Diff tests/framework/Optimizers/GeneticAlgorithms/simionescuConstrainedInvLin
Diff tests/framework/Samplers/SparseGrid/normal
Failed tests/framework/Samplers/SparseGrid/betanorm
Failed tests/framework/Samplers/SparseGrid/beta
Diff tests/framework/Samplers/SparseGrid/triangular
Diff tests/framework/pca_adaptive_sgc/test_adaptive_sgc_poly_pca_analytic

PASSED: 778
SKIPPED: 93
FAILED: 11


I think a lot of those are from differences between how arm64 and amd64 handle floating point numbers. (From what I have seen online, I think basic arithmetic (+-*/) are the same, but things like floating to integer and back are different as well as functions like sin which will give differences eventually)

**Comment by alfoa** [comment]
Just FYI: (on M2, I had to download and "pip install" smt directly from https://github.com/SMTorg/SMT)

**Comment by joshua-cogliati-inl** [comment]
@alfoa Yes, we are discussing smt at: https://github.com/idaholab/raven/pull/2138#discussion_r1337680697

**Comment by wangcj05** [comment]
This issue is partly addressed by PR #2138

**Comment by joshua-cogliati-inl** [comment]
It looks like #2201 fixed the  beta Sampler problems:
```
(49/69) Success(  2.87sec)tests/framework/Samplers/SparseGrid/beta
(50/69) Success(  2.90sec)tests/framework/Samplers/SparseGrid/betanorm
```

**Comment by wangcj05** [comment]
[like]  Congjian Wang reacted to your message:
________________________________
From: Joshua J. Cogliati ***@***.***>
Sent: Friday, November 10, 2023 5:57:25 PM
To: idaholab/raven ***@***.***>
Cc: Congjian Wang ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [idaholab/raven] [TASK] Issue finding tensorflow during Install RAVEN libraries for Mac M2 (Issue #2158)


It looks like #2201<https://github.com/idaholab/raven/pull/2201> fixed the beta Sampler problems:

(49/69) Success(  2.87sec)tests/framework/Samplers/SparseGrid/beta
(50/69) Success(  2.90sec)tests/framework/Samplers/SparseGrid/betanorm

**Comment by wangcj05** [comment]
It seems this issue has been resolved.
