### ISSUE TITLE
[TASK] Support top level variables in moose inputs

### ISSUE THREAD

**Issue by veeshy** [idaholab/raven#2159]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
MOOSE supports inputs to live outside of typical `[]` tags like in this [arbitrarily chosen test](https://github.com/idaholab/moose/blob/98c121565021040d042a982ab2ca0726c512b7b2/modules/thermal_hydraulics/test/tests/components/hs_coupler_2d3d/hs_coupler_2d3d.i#L3-L9C13). Using such an input in raven cause it to fail. 

```
  File "raven/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseInputParser.py", line 138, in getpotToInputTree
    if attribute in (c.tag for c in currentNode.children): #currentNode.attrib:
AttributeError: 'NoneType' object has no attribute 'children'
```

**Describe the solution you'd like**
I'd like to see RAVEN be able to handle this typical moose input. 

Here is a patch that would do  but I have no idea if I've missed some gotcha's, like at the least this doesn't check for a duplicate anymore on a top level input. 

```
diff --git a/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseInputParser.py b/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseInputParser.py
index e2edf54b1..f5889c1bd 100644
--- a/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseInputParser.py
+++ b/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseInputParser.py
@@ -135,7 +135,11 @@ def getpotToInputTree(getpot):
     #------------------
     # if the "value" if the "attribute" is closed, record the entry
     if closeEntry:
-      if attribute in (c.tag for c in currentNode.children): #currentNode.attrib:
+      if currentNode is None:
+        currentNode = TreeStructure.InputNode(tag=attribute, text=value)
+        roots.append(currentNode)
+        currentNode = None
+      elif attribute in (c.tag for c in currentNode.children): #currentNode.attrib:
         raise IOError('Multiple entries defined with same name "{a}"!'.format(a=attribute))
       else:
         new = TreeStructure.InputNode(tag=attribute, text=value)
```

and this allows the var to be sampled:

```
diff --git a/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseBasedAppInterface.py b/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseBasedAppInterface.py
index 8f7fcb11d..857c1137f 100644
--- a/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseBasedAppInterface.py
+++ b/ravenframework/CodeInterfaceClasses/MooseBasedApp/MooseBasedAppInterface.py
@@ -160,9 +160,6 @@ class MooseBasedApp(CodeInterfaceBase):
         request, elemLoc = (v.strip() for v in var.split(':'))
       else:
         request = var
-      if '|' not in request:
-        # what modifications don't have the path in them?
-        continue
       pathedName = request.split('|')
       modifDict['name'] = pathedName
       if elemLoc is not None:
```

**Describe alternatives you've considered**
Don't use top level inputs, but they are just too convenient. At the least a nice error when this is detected would be nice.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@wangcj05 @mandd

**Comment by PaulTalbot-INL** [comment]
Approved to close via #2274.
