### ISSUE TITLE
[TASK] Markov-switching autoregressive models

### ISSUE THREAD

**Issue by j-bryan** [idaholab/raven#2160]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
An approach of segmentation and clustering of the data is common when fitting time series models with the TSA module, but this approach often results in having too few data to accurately estimate model parameters. Also, changes in the model occur only as one segment ends and another begins, which is inflexible and does not reflect the dynamic nature of regime change in some applications.

**Describe the solution you'd like**
Regime-switching models like Markov-switching autoregressive models (MSAR) address the above concerns by conditioning the model parameters on the state of a hidden Markov model. MSAR models switch between regimes probabilistically. In effect, inferring the Markov states and each state's model parameters is akin to the current clustering approach but does not require segmentation, adding flexibility. The MSAR model could be added to the TSA module and used in place of the existing ARMA model.

**Describe alternatives you've considered**
Major revisions to the segmentation and clustering in the ROMCollection.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Approved to close via #2161
