### ISSUE TITLE
[TASK] Add an option similar to preserveInputCDF from the ARMA ROM to the TSA module

### ISSUE THREAD

**Issue by j-bryan** [idaholab/raven#2164]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
1) The ARMA ROM has the ability to transform the distribution of a generated sample to the same distribution as the original training data. The TSA module does not yet implement this feature.
2) The ARMA algorithm in TSA performs a gaussianizing transformation by default and does not include an option to toggle that setting. Given the recent addition of data transformations to TSA, it would be more readable and more consistent with the current TSA interface to have this gaussianizing transformation as a separate transformation. The QuantileTransformer transformation can accomplish this, but this may not be apparent to those less familiar with TSA or scikit-learn's preprocessing capabilities.

**Describe the solution you'd like**
1) Implement a CDF-preserving algorithm that can be included in a TSA model.
2) Implement a `Gaussianize` algorithm to perform that transformation outside of the ARMA class, and add an attribute to allow the `gaussianize` setting for ARMA to be changed by the user.

**Describe alternatives you've considered**
Add additional documentation telling users to use a QuantileTransformer to gaussianize their signal.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Approved to close via #2165
