### ISSUE TITLE
[TASK] abce code interface

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2173]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
It would be useful to have an interface to ABCE: agent-based capacity expansion modeling
ABCE is a modeling tool used to model adding capacity (new generators) to an electricity market.
ABCE is given information on the agents, demand, and unit costs and returns information about the assets constructed in a given time period.

**Describe the solution you'd like**
Create a code interface for this

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
@joshua-cogliati-inl @JiaZhou-PU Could you add more descriptions about abce in the issue description section?

**Comment by joshua-cogliati-inl** [comment]
> @joshua-cogliati-inl @JiaZhou-PU Could you add more descriptions about abce in the issue description section?

I added a bit more to the the description.

**Comment by PaulTalbot-INL** [comment]
Approved to close via #2184. No email to users needed, but should probably be noted in our next release notes.
