### ISSUE TITLE
[DEFECT] Gradient Descent Optimizer requires type=FiniteDifference 

### ISSUE THREAD

**Issue by cbroman-usnctech** [idaholab/raven#2175]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

When creating a Gradient Descent optimization input file, it is required to define within Multirun an optimizer class with **type="FiniteDifference"** i.e.

    <Optimizer class="Optimizers" type="FiniteDifference">myGradientDescentOptimizer</Optimizer>

When it should accept **type ="GradientDescent"**

    <Optimizer class="Optimizers" type="GradientDescent">gradientAlgo</Optimizer>

The subnode **gradient** is where the `FiniteDifference` or `CentralDifference` types should be specified.

### Steps to Reproduce

Run the GradientDescent algorithm with Optimizer type=GradientDescent. You will receive the following message. 

`OSError: The number of times class = Optimizers type= ['SPSA', 'FiniteDifference', 'ConjugateGradient', 'SimulatedAnnealing', 'GeneticAlgorithm'] is used as Optimizer is improper. Number of allowable times is 1.Got 0`

### Expected Behavior

<Optimizer class="Optimizers" type="GradientDescent">gradientAlgo</Optimizer>

is a valid input and consistent with other optimizers. 

### OS

Linux

### OS Version

20.04

### Dependency Manager

PIP

### For Change Control Board: Issue Review

- [ ] Is it tagged with a type: defect or task?
- [ ] Is it tagged with a priority: critical, normal or minor?
- [ ] If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
please comment on this issue @PaulTalbot-INL @dylanjm

**Comment by alfoa** [comment]
[opt.patch](https://github.com/idaholab/raven/files/12543117/opt.patch)

We created this patch (that also updates the tests). If any developer wants to take a look and create a MR it would be nice.

**Comment by dylanjm** [comment]
> [opt.patch](https://github.com/idaholab/raven/files/12543117/opt.patch)
> 
> We created this patch (that also updates the tests). If any developer wants to take a look and create a MR it would be nice.

I've gone ahead and opened #2177 to apply the patch @alfoa provided.

**Comment by PaulTalbot-INL** [comment]
No incorrect solutions can be obtained as a result of this defect, only code crashing based on surface syntax.

Approved to close via #2177
