### ISSUE TITLE
[DEFECT] Installation HPC Lemhi

### ISSUE THREAD

**Issue by mgarrouste** [idaholab/raven#2199]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [ ] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Here is the error I get when trying to re-install raven on Lemhi following the wiki's instructions:
![image](https://github.com/idaholab/raven/assets/74023858/e1b2be41-e941-4c3d-83ae-d11391ceebd4)

### Steps to Reproduce

Install raven on lemhi

### Expected Behavior

Installation without issues

### Screenshots and Input Files

![image](https://github.com/idaholab/raven/assets/74023858/2d30391a-ce97-4f7a-8f4a-8c606a13719c)

### OS

Linux

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [ ] Is it tagged with a type: defect or task?
- [ ] Is it tagged with a priority: critical, normal or minor?
- [ ] If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [ ] If the issue is a defect, is the defect fixed?
- [ ] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
To use raven on LEMHI you just need to do two things:

1. Make sure you don't have a local conda environments called `raven_libraries`
2. Run `module load raven` 

You should be able to use RAVEN and HERON through the command line now. 

We will update our wiki instructions to close this issue.

**Comment by mgarrouste** [comment]
When I do module load raven in Lemhi and I try to run an input from the command line I get this error
<img width="965" alt="image" src="https://github.com/idaholab/raven/assets/74023858/0d266660-91eb-43e5-a347-b125d3dab517">

**Comment by dylanjm** [comment]
I can't be sure what your alias `raven` is defined as. I'm guessing it's probably defined something like `alias raven=<your/path/to/a/local/raven>/raven_framework.py` this is not the raven that is used when loading `module load raven`

You should be able to run `raven_framework ARMA_train_keynya_solar_2021.xml`

**Comment by mgarrouste** [comment]
Thanks the reaven_framework command worked, however I would like to be able to use heron as well but when I try running heron the conda definition needs to be updated, what can I do?

**Comment by dylanjm** [comment]
Hi @mgarrouste can you post a few things, so I can help diagnose the issue:

1. The command you are trying to run
2. The error you are recieving
3. The output of running `echo $PATH`

Thanks!

**Comment by dylanjm** [comment]
Closing this issue. The Wiki has been updated with instructions on how to use RAVEN on LEMHI. I have also worked with Marisol offline to fix her issue.
