### ISSUE TITLE
Typical History Post-Processor does not validate that data is synchronized

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#222]
--------
Issue Description
--------
##### What did you expect to see happen?

The typical history Post-Processor does not validate that data is synchronized. It should error when the data is not synchronized.

##### What did you see instead?

The program errors with an obfuscated stack trace and error message like the one given below:

```
IndexError: index 7 is out of bounds for size 7
```

##### Do you have a suggested fix for the development team?

A better error message pointing the user to the mistake in their input file would be much more user-friendly and would turn around debugging time.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[example.zip](https://github.com/idaholab/raven/files/1089786/example.zip)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?  __Does not affect requirements__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __Not a defect__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by maljovec** [comment]
This should be addressed in [maljdan/error_messages](https://github.com/idaholab/raven/tree/maljdan/error_messages)

**Comment by PaulTalbot-INL** [comment]
Approved for closure with #223.
