### ISSUE TITLE
[DEFECT] Recent RNG changes broke MarkovAR sampling

### ISSUE THREAD

**Issue by j-bryan** [idaholab/raven#2228]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Recent changes to RNG interface in RAVEN have broken signal generation in `ravenframework/TSA/MarkovAR.py`. This wasn't caught by the existing test because samples from the model were not checked in the regression test.

### Steps to Reproduce

The existing test case (`tests/framework/ROM/TimeSeries/SyntheticHistory/markov_ar.xml`) reproduces the error.

### Expected Behavior

Generation of a signal with the fitted model. Execution of the current code results in an `AttributeError`.

### OS

Windows

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [ ] If the issue is a defect, is the defect fixed?
- [ ] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Fixed by #2229
