### ISSUE TITLE
[DEFECT] conda-forge liblapack 3.9.0 21 is broken

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2252]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [ ] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

With liblapack 3.9.0 21 we get this error:
```
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import scipy.stats
>>> mean = np.zeros(1)
>>> cov=np.eye(1)
>>> mean
array([0.])
>>> cov
array([[1.]])
>>> scipy.stats.multivariate_normal(mean=mean, cov=cov)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fred/.conda/envs/raven_libraries_new/lib/python3.10/site-packages/scipy/stats/_multivariate.py", line 382, in __call__
    return multivariate_normal_frozen(mean, cov,
  File "/home/fred/.conda/envs/raven_libraries_new/lib/python3.10/site-packages/scipy/stats/_multivariate.py", line 759, in __init__
    self.cov_info = _PSD(self.cov, allow_singular=allow_singular)
  File "/home/fred/.conda/envs/raven_libraries_new/lib/python3.10/site-packages/scipy/stats/_multivariate.py", line 157, in __init__
    s, u = scipy.linalg.eigh(M, lower=lower, check_finite=check_finite)
  File "/home/fred/.conda/envs/raven_libraries_new/lib/python3.10/site-packages/scipy/linalg/_decomp.py", line 547, in eigh
    w, v, *other_args, info = drv(a=a1, **drv_args, **lwork_args)
_flapack.error: (liwork>=max(1,10*n)||liwork==-1) failed for 10th keyword liwork: dsyevr:liwork=1
```

### Steps to Reproduce

install liblapack 3.9.0 21_linux64_openblas with scipy 1.9

### Expected Behavior

Not to crash.

### OS

Linux

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [ ] Is it tagged with a type: defect or task?
- [ ] Is it tagged with a priority: critical, normal or minor?
- [ ] If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
User impact results in crashed runs, not numerical errors. Good to close via #2251.
