### ISSUE TITLE
[TASK] Script to build packages without conda

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2258]
--------
Issue Description
--------

**Is your feature request related to a problem? Please describe.**
Conda built pip packages can link in libraries that are not available on a different computer. This resulted in errors like:
```
Traceback (most recent call last):
  File "/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/ravenframework/utils/utils.py", line 659, in find_crow
    import crow_modules.distribution1D
  File "/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/crow_modules/distribution1D.py", line 13, in <module>
    from . import _distribution1D
ImportError: dlopen(/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/crow_modules/_distribution1D.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <E3888BAA-1459-3DCE-B489-9E19A724980B> /Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/crow_modules/_distribution1D.cpython-310-darwin.so
  Reason: tried: '/Users/fred/miniconda3_arm64/envs/python310_pip/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/fred/miniconda3_arm64/envs/python310_pip/lib/libc++.1.dylib' (no such file), '/Users/fred/miniconda3_arm64/envs/python310_pip/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/fred/miniconda3_arm64/envs/python310_pip/lib/libc++.1.dylib' (no such file), '/Users/jack/miniconda3/envs/test_raven/bin/../lib/libc++.1.dylib' (no such file), '/Users/jack/miniconda3/envs/test_raven/bin/../lib/libc++.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jack/miniconda3/envs/test_raven/bin/raven_framework", line 8, in <module>
    sys.exit(wheelMain())
  File "/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/ravenframework/Driver.py", line 34, in wheelMain
    main(False)
  File "/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/ravenframework/Driver.py", line 43, in main
    dutils.doSetup(checkLibraries)
  File "/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/ravenframework/CustomDrivers/DriverUtils.py", line 39, in doSetup
    setupCpp()
  File "/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/ravenframework/CustomDrivers/DriverUtils.py", line 105, in setupCpp
    utils.find_crow(frameworkDir)
  File "/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/ravenframework/utils/utils.py", line 683, in find_crow
    raise IOError(UreturnPrintTag('UTILS') + ': '+UreturnPrintPostTag('ERROR')+ ' -> Crow has not been found. It location is supposed to be one of '+str(crowDirs)+'. Has RAVEN been built?')
OSError: UTILS                    : ERROR      -> Crow has not been found. It location is supposed to be one of ['/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages/crow', '/Users/jack/miniconda3/envs/test_raven/lib/python3.10/crow', '/Users/jack/miniconda3/envs/test_raven/lib/python3.10/site-packages']. Has RAVEN been built?
```

**Describe the solution you'd like**
Building the pip packages without using conda would be useful.  This might fix the linking errors.

**Describe alternatives you've considered**
Building the libraries with static linking might be possible, but there doesn't seem to be a documented way to do this.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
checklist is good.
