### ISSUE TITLE
[DEFECT] mamba might not be available in new conda environment

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2269]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [ ] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

If mamba is in the outer environment, establish_conda will not install it in the newly created environment. This can be a problem because then mamba may not be found when trying to use mamba to install.

This can result in the following error message:
```
... conda-forge pre-command: conda create --name raven_libraries -y -c conda-forge
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

...

... Activating environment ...
... conda-forge command: mamba install -y -c conda-forge h5py numpy=1.22 scipy=1.9 scikit-learn=1.0 pandas xarray=2023 matplotlib=3.5 statsmodels=0.13 cloudpickle=2.2 python=3 hdf5 swig pylint coverage lxml psutil pip importlib_metadata nomkl numexpr smt setuptools liblapack=3.9.0=20_linux64_openblas numpy-financial networkx pytest dill=0.3.5 pyomo=6.4 pyutilib glpk ipopt coincbc=2.10.5 cvxpy cvxopt quadprog qpsolvers
scripts/establish_conda_env.sh: line 196: mamba: command not found
```

### Steps to Reproduce

Install with mamba in the base library, but not on the system.

### Expected Behavior

This to work.

### OS

Linux

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
checklist is good.
