### ISSUE TITLE
[UNDER-DISCUSSION] SMT vs. PyDOE

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#2294]
--------
Under Discussion Topic
--------

**Summary of the topic to be discussed with the development team**

Currently both SMT and PyDOE are used inside RAVEN to generate random samples. SMT is used by BayesianOptimizer to perform LHS sampling, while PyDOE is used by Samplers to perform Factorial Design, ResponseSurfaceDesign etc. In addition SMT is not available for MAC. We should consider to use just one of them. Possible solution is to remove both SMT and PyDOE, and use PyDOE3 directly (https://pydoe3.readthedocs.io/en/stable/index.html). The current issue with SMT is that we can not run BayesianOptimizer using MAC and we can not generate the corresponding manual also in MAC system. While PyDOE is currently used as contrib library for raven. 

**Describe the solution you'd like to be implemented**

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with the under_discussion type?
- [ ] 2. If implemented, it will add a new requirement?
- [ ] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by wangcj05** [comment]
Hi @joshua-cogliati-inl @PaulTalbot-INL @mandd @dylanjm @Jimmy-INL, please let me know what do you think.

**Comment by PaulTalbot-INL** [comment]
Hm, that's interesting. If PyDOE can do the same LHS sampling that BO needs, we should probably pivot to using that. How did this not show up in the regression tests? Or did it?

**Comment by PaulTalbot-INL** [comment]
Do we have any idea what we added to pyDOE for our needs? As I recall, we only used it in the Design of Experiment sampler, which barely sees the light of day as far as I know.

**Comment by joshua-cogliati-inl** [comment]
I don't recall having to do major changes to pyDOE, just things like adding a few docstrings (to make pylint happy) and making some imports relative (so we didn't have to mangle the PYTHONPATH for pyDOE)  ab269846be6f8bc13adce562f80f84bcbb497f9d and 3b253877bde67832265c5f5414bba22b45b26272

**Comment by PaulTalbot-INL** [comment]
Hm. Why doe we have pyDOE as a contrib rather than a lib? Did I miss this detail?

**Comment by joshua-cogliati-inl** [comment]
I am not sure at this point.  It might be worth making a quick pull request that deletes the directory and adds it as a pip/conda dependency and seeing what happens.

**Comment by alfoa** [comment]
> Internally, SMT is using PyDOE3 to perform LHS sampling, so for me there is no need to use SMT. In addition, we are using PyDOE as contrib, and I do not remember the specific reason for that. For me, I do not think we need SMT, but there is probably some minor work to do when switching PyDOE to PyDOE3. Regarding the regression test, PyDOE and LHS are used in different entities, we do test them, and there is no conflict. @PaulTalbot-INL @dylanjm

Hi guys. The reason why PyDOE was added as a ``contrib`` folder 10 years ago was that it was not available as pip/conda package at that time.

**Comment by PaulTalbot-INL** [comment]
Thanks, @alfoa !

**Comment by joshua-cogliati-inl** [comment]
I created a pull request to use pyDOE3 directly. #2298 

I don't have time at the moment to switch the smt stuff to pyDOE, but the above pull request is ready to review.

**Comment by PaulTalbot-INL** [comment]
Approved to close via #2365.
