### ISSUE TITLE
[DEFECT] SimulatedAnnealing Opt fails with for 1 variable optimization

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#2295]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

If simulated annealing optimization is used with a single variable, the code crashes in the method ```_nextNeighbour```.
```
Traceback (most recent call last):
  File "./raven/raven_framework.py", line 25, in <module>
    sys.exit(main(True))
  File "./raven/ravenframework/Driver.py", line 207, in main
    raven()
  File "./raven/ravenframework/Driver.py", line 160, in raven
    simulation.run()
  File "./raven/ravenframework/Simulation.py", line 901, in run
    self.executeStep(stepInputDict, stepInstance)
  File "./raven/ravenframework/Simulation.py", line 834, in executeStep
    stepInstance.takeAstep(stepInputDict)
  File "./raven/ravenframework/Steps/Step.py", line 317, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "./raven/ravenframework/Steps/MultiRun.py", line 229, in _localTakeAstepRun
    sampler.finalizeActualSampling(finishedJob,model,inputs)
  File "./raven/ravenframework/Samplers/Sampler.py", line 1081, in finalizeActualSampling
    self.localFinalizeActualSampling(jobObject, model, myInput)
  File "./raven/ravenframework/Optimizers/RavenSampled.py", line 308, in localFinalizeActualSampling
    self._useRealization(info, rlz)
  File "./raven/ravenframework/Optimizers/SimulatedAnnealing.py", line 317, in _useRealization
    newPoint = self._nextNeighbour(rlz, fraction)
  File "./raven/ravenframework/Optimizers/SimulatedAnnealing.py", line 717, in _nextNeighbour
    nextNeighbour[var] = rlz[var] + delta[i]
IndexError: invalid index to scalar variable.
```

The reason Is that the ```delta``` variable is cast as float in case of a 1-variable optimization.
The fix is as follows:
```
diff --git a/ravenframework/Optimizers/SimulatedAnnealing.py b/ravenframework/Optimizers/SimulatedAnnealing.py
index 03f1ba144..05ff7d1df 100644
--- a/ravenframework/Optimizers/SimulatedAnnealing.py
+++ b/ravenframework/Optimizers/SimulatedAnnealing.py
@@ -708,6 +708,7 @@ class SimulatedAnnealing(RavenSampled):
     elif self._coolingMethod == 'cauchy':
       amp = (np.pi - (-np.pi))*randomUtils.random(dim=D, samples=1)-np.pi
       delta = alpha*self.T*np.tan(amp)
+    delta = np.atleast_1d(delta)
     for i,var in enumerate(self.toBeSampled.keys()):
       nextNeighbour[var] = rlz[var] + delta[i]
       self.info['amp_'+var] = amp
```

### Steps to Reproduce

Single variable optimization using SimulatedAnnealing

### Expected Behavior

Successful optimization process

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [X] Is it tagged with a type: defect or task?
- [X] Is it tagged with a priority: critical, normal or minor?
- [X] If it will impact requirements or requirements tests, is it tagged with requirements?
- [X] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue closure checklist is good.
