### ISSUE TITLE
[DEFECT] Genetic Algorithm crashes with Ensemble model and <functions> 

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#2304]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Genetic Algorithm crashes with Ensemble model and <functions> .

If the GA is used with variables produced by functions with an ensemble model, the code crashes.

E.g.

```
--------------------------------------------------
Exception in thread 1:
Traceback (most recent call last):
  File "/Users/aalfonsi/mambaforge3/envs/raven_libraries/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/aalfonsi/mambaforge3/envs/raven_libraries/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "raven/ravenframework/Runners/SharedMemoryRunner.py", line 115, in <lambda>
    self.thread = InterruptibleThread(target = lambda q, *arg : q.append(self.functionToRun(*arg)),
  File "raven/ravenframework/Models/EnsembleModel.py", line 512, in evaluateSample
    Input = self.createNewInput(myInput[0], samplerType, **kwargsToKeep)
  File "raven/ravenframework/Models/EnsembleModel.py", line 425, in createNewInput
    self.raiseAnError(RuntimeError,"for sub-model "+ modelIn + " the input "+inp+" has not been found among other models' outputs and sampled variables!")
  File "raven/ravenframework/BaseClasses/MessageUser.py", line 77, in raiseAnError
    self.messageHandler.error(self, etype, msg, str(tag), verbosity, color)
  File "raven/ravenframework/MessageHandler.py", line 235, in error
    raise etype(message)
RuntimeError: for sub-model testModel the input decay_B has not been found among other models' outputs and sampled variables!
```

### Steps to Reproduce

I will add an input file

### Expected Behavior

no crash. This is a critical show stopper.

### Screenshots and Input Files

[input_file.inl.zip](https://github.com/idaholab/raven/files/15064365/input_file.inl.zip)

### OS

Linux

### Dependency Manager

PIP

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue closure checklist is good.
