### ISSUE TITLE
Loading CSV into DataObject with existing data

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#231]
--------
Issue Description
--------
##### What did you expect to see happen?

According to the user manual under the IOStep chapter (20.3 at the time of issue creation), the user should be able to perform the following action with an IOStep:

"construct/update a DataObject from a CSV file contained in a directory;"

In this sense of the word update, I consider this to mean a non-destructive update. That is, existing data will not be lost in the operation, only new data will be appended to the DataObject.

##### What did you see instead?

The process is destructive in the sense that it deletes whatever is currently present in the file.

##### Do you have a suggested fix for the development team?

Yes, I have identified the issue and will create a follow-up PR shortly.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

Input included with related PR.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
No additional notification necessary, as this is functionally a new feature despite being claimed previously.
