### ISSUE TITLE
[DEFECT] Specialized plots (e.g. OptPath, PopulationPlot, etc.) ignore "dir" attribute in the input file

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#2315]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Specialized plots (e.g. OptPath, PopulationPlot, etc.) ignore "dir" attribute in the input file

### Steps to Reproduce

add a "dir" attribute in any of the specialized plots

### Expected Behavior

"dir" directory to be considered and plot to be save in subdirectories when indicated

### OS

Linux

### Dependency Manager

PIP

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue closure checklist is good.
