### ISSUE TITLE
[DEFECT] Opt Path labels with a lot of underscores are illegible if too long

### ISSUE THREAD

**Issue by GabrielSoto-INL** [idaholab/raven#2329]
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

When using the optimization path plot, if the `var` names are too long the y-labels are not legible. 
Example from the HERON "optimization_settings" regression test:
![1-opt_path_old](https://github.com/idaholab/raven/assets/109242402/59263485-5978-47a7-af1c-9fee1d9c17e1)

### Steps to Reproduce

Run a RAVEN optimization script with an Outstreams node subtype OptPath, code example below from the [HERON optimization settings regression test](https://github.com/idaholab/HERON/tree/97bf72e4042b6fa8ef14fbb6ba378ba6bb9eb64b/tests/integration_tests/mechanics/optimization_settings):
```
<OutStreams>
    <Plot name="opt_path" subType="OptPath">
      <source>opt_soln</source>
      <vars>GRO_capacities, VaR_0.05_NPV</vars>
    </Plot>
  </OutStreams>
```
A current RAVEN example exists in the [workshop documentation](https://github.com/idaholab/raven/blob/dec9c70d7c1333035a4598d97a387b3f31ce7561/doc/workshop/optimizer/GeneticAlgorithms/exercises/1_GA_MaxwRep.xml)

### Expected Behavior

Y-labels should be legible even if names are long. Particularly, HERON uses a lot of strings joined by underscores. It would be good to split the strings by the underscores. 

### OS

Windows

### Dependency Manager

PIP

### For Change Control Board: Issue Review

- [x] Is it tagged with a type: defect or task?
- [x] Is it tagged with a priority: critical, normal or minor?
- [x] If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [x] If the issue is a defect, is the defect fixed?
- [x] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by dylanjm** [comment]
Approved to close via #2330
