### ISSUE TITLE
distInit input error on Monte Carlo sampler needs improved error message

### ISSUE THREAD

**Issue by tedb314** [idaholab/raven#235]
--------
In my monte carlo sampler, I had a distInit tag block, though it was not needed since I was not creating dependencies between parameters.
--------
It is not clear in the manual that this block is only needed for n-dimensional arrays, so I left it in, expecting normal sampling from my uniform distribution

##### What did you see instead?
(    0.10 sec) SIMULATION               : Message         -> -- Beginning step MCrun of type: MultiRun                           --
(    0.10 sec) STEP MULTIRUN            : Message         -> ***  Beginning initialization ***
(    0.10 sec) STEP MULTIRUN            : DEBUG           -> jobHandler initialized
(    0.10 sec) EnsembleModel            : Message         -> Model Execution list: construct_dispatch -> ARMA_price -> CashFlowPreP -> Cash_Flow
(    0.10 sec) EnsembleModel            : Message         -> EnsembleModel connections determined a linear system. Picard's iterations not activated!
(    0.10 sec) EnsembleModel            : Message         -> Specs of Graph Network represented by EnsembleModel:
(    0.10 sec) EnsembleModel            : Message         -> Graph Degree Sequence is    : (1, 1, 1, 0)
(    0.10 sec) EnsembleModel            : Message         -> Graph Minimum/Maximum degree: (0, 1)
(    0.10 sec) EnsembleModel            : Message         -> Graph density/diameter      : (0.5, 3)
(    0.10 sec) STEP MULTIRUN            : DEBUG           -> for the role Model  the item of class EnsembleModel   and name MyEnsemble      has been initialized
(    0.10 sec) STEP MULTIRUN            : DEBUG           -> for the role Output the item of class PointSet        and name MCoutput        has been initialized
(    0.10 sec) MonteCarlo               : Message         -> No restart for MonteCarlo
Traceback (most recent call last):
  File "/home/bakete/projects/hybrid/raven/framework/Driver.py", line 278, in <module>
    raven()
  File "/home/bakete/projects/hybrid/raven/framework/Driver.py", line 231, in raven
    simulation.run()
  File "/home/bakete/projects/hybrid/raven/framework/Simulation.py", line 1051, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/bakete/projects/hybrid/raven/framework/Steps.py", line 235, in takeAstep
    self._initializeStep(inDictionary)
  File "/home/bakete/projects/hybrid/raven/framework/Steps.py", line 191, in _initializeStep
    self._localInitializeStep(inDictionary)
  File "/home/bakete/projects/hybrid/raven/framework/Steps.py", line 465, in _localInitializeStep
    self._initializeSampler(inDictionary)
  File "/home/bakete/projects/hybrid/raven/framework/Steps.py", line 448, in _initializeSampler
    inDictionary[self.samplerType].initialize(**self._samplerInitDict)
  File "/home/bakete/projects/hybrid/raven/framework/Samplers/Sampler.py", line 508, in initialize
    self.distDict[temp].updateRNGParam(params)
AttributeError: 'Uniform' object has no attribute 'updateRNGParam'

##### Do you have a suggested fix for the development team?
Possibly update the manual and/or the error message to suggest that if you are not using n-dimensional arrays, that this block should not be included.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

`<Simulation verbosity="debug">
  <RunInfo>
    <WorkingDir>.</WorkingDir>
    <Sequence>read_ARMA_prices,MCrun,printMCfile</Sequence>
    <batchSize>24</batchSize>
    <internalParallel>True</internalParallel> 
    <NumThreads>1</NumThreads>
  </RunInfo>
  <Files>
    <Input name="caisoPrice" type="">ARMA_prices.pk</Input>
  </Files>

  <VariableGroups>
    <Group name="GRO_construct_dispatch_in">
      batE1,batE2,batE3,batE4,batE5,batE6,batE7,batE8,
      batE9,batE10,batE11,batE12,batE13,batE14,batE15,batE16,
      batE17,batE18,batE19,batE20,batE21,batE22,batE23,batE24
    </Group>
      
    <Group name="GRO_construct_dispatch_out">
      batteryEnergy, batteryPower
    </Group>

    <Group name="GRO_CashFlowPreP_in">
      batteryPower, price
    </Group>
    <Group name="GRO_CashFlowPreP_out">
      batteryRevenue, batteryPowerSold, battery_AVG_fuel, battery_AVG_CO2
    </Group> 
    <Group name="GRO_CashFlow_in" > batteryCapacity, batteryPowerSold, batteryRevenue, battery_AVG_fuel, battery_AVG_CO2</Group> 
    <Group name="GRO_CashFlow_out" >IRR, NPV, PI, HYB_fuel_tot, HYB_CO2_tot</Group>
  </VariableGroups>

  <Models>
    <ROM name='ARMA_price' subType='ARMA'>
      <Target>price,seconds</Target>
      <Features>scaling_price</Features>
      <pivotParameter>seconds</pivotParameter>
      <Pmax>6</Pmax>
      <Pmin>6</Pmin>
      <Qmax>1</Qmax>
      <Qmin>1</Qmin>
      <outTruncation>none</outTruncation>
      <Fourier>31536000,604800,86400, 1080</Fourier>
      <FourierOrder>12, 2, 6, 3</FourierOrder>   
    </ROM>
    <ExternalModel ModuleToLoad="vars_to_hist" name="construct_dispatch" subType="">
      <variables>GRO_construct_dispatch_in, GRO_construct_dispatch_out</variables>
      
      <Dispatch verbosity="51"> </Dispatch>
    </ExternalModel>
    <ExternalModel ModuleToLoad="CashFlowPreP" name="CashFlowPreP" subType="">
      <variables>GRO_CashFlowPreP_in, GRO_CashFlowPreP_out</variables>
      
      <NPVPreP verbosity="0"> 
      </NPVPreP>
    </ExternalModel>
    <ExternalModel ModuleToLoad="Cash_Flow" name="Cash_Flow" subType="">
      <variables> GRO_CashFlow_in, GRO_CashFlow_out</variables>
      <ExternalXML node="Economics" xmlToLoad="bat_Cash_Flow_input.xml"></ExternalXML>
    </ExternalModel>
    <EnsembleModel name="MyEnsemble" subType="">
      <Model class="Models" type="ROM">
        ARMA_price
        <Input            class="DataObjects" type="PointSet">SET_ARMA_prices_in</Input>
        <TargetEvaluation class="DataObjects" type="HistorySet">SET_ARMA_prices_out</TargetEvaluation>
      </Model>
      <Model class="Models" type="ExternalModel">
        construct_dispatch
        <Input            class="DataObjects" type="PointSet">SET_construct_dispatch_in</Input>
        <TargetEvaluation class="DataObjects" type="HistorySet">SET_construct_dispatch_out</TargetEvaluation>
      </Model>
      <Model class="Models" type="ExternalModel">
        CashFlowPreP
        <Input            class="DataObjects" type="PointSet">SET_CashFlowPreP_in</Input>
        <TargetEvaluation class="DataObjects" type="PointSet">SET_CashFlowPreP_out</TargetEvaluation>
      </Model>
      <Model class="Models" type="ExternalModel">
        Cash_Flow
        <Input            class="DataObjects" type="PointSet">SET_CashFlow_in</Input>
        <TargetEvaluation class="DataObjects" type="PointSet">SET_CashFlow_out</TargetEvaluation>
      </Model>
    </EnsembleModel>
  </Models>

  <Distributions>
    <Uniform name="energy_distrib">
      <upperBound>150000000</upperBound>   
      <lowerBound>0</lowerBound>    
    </Uniform>
  </Distributions>

  <Samplers>
    <MonteCarlo name='energyMC'>
      <samplerInit>
        <limit>20</limit>
        <initialSeed>200286</initialSeed>
        <reseedEachIteration>false</reseedEachIteration>
        <distInit>
          <distribution name= 'energy_distrib'>
            <initialGridDisc>10</initialGridDisc>
            <tolerance>0.2</tolerance>
          </distribution>
        </distInit>
      </samplerInit>
      <variable name='batE1'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE2'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE3'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE4'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE5'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE6'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE7'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE8'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE9'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE10'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE1l'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE12'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE13'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE14'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE15'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE16'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE17'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE18'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE19'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE20'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE21'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE22'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE23'>
        <distribution>energy_distrib</distribution>
      </variable>
      <variable name='batE24'>
        <distribution>energy_distrib</distribution>
      </variable>
    </MonteCarlo>
  </Samplers>

  <DataObjects>
    <HistorySet name="MCdata">
      <Input>GRO_construct_dispatch_in</Input>
      <Output>OutputPlaceHolder</Output>
    </HistorySet>
    <PointSet name="MCoutput">
      <Input>GRO_construct_dispatch_in</Input>
      <Output>NPV</Output>
    </PointSet>
    <PointSet name="SET_ARMA_prices_in">
      <Input>scaling_price</Input>
      <Output>OutputPlaceHolder</Output>
    </PointSet>
    <HistorySet name="SET_ARMA_prices_out">
      <Input>scaling_price</Input>
      <Output>price,seconds</Output>
    </HistorySet>
    <PointSet name="SET_construct_dispatch_in">
      <Input>GRO_construct_dispatch_in</Input>
      <Output>OutputPlaceHolder</Output>
    </PointSet>
    <HistorySet name="SET_construct_dispatch_out">
      <Input>GRO_construct_dispatch_in</Input>
      <Output>GRO_construct_dispatch_out</Output>
    </HistorySet>
    <PointSet name="SET_CashFlowPreP_in">
      <Input>GRO_CashFlowPreP_in</Input>
      <Output>OutputPlaceHolder</Output>
    </PointSet>
    <PointSet name="SET_CashFlowPreP_out">
      <Input>GRO_CashFlowPreP_in</Input>
      <Output>GRO_CashFlowPreP_out</Output>
    </PointSet>
    <PointSet name="SET_CashFlow_in">
      <Input>GRO_CashFlow_in</Input>
      <Output>OutputPlaceHolder</Output>
    </PointSet>
    <PointSet name="SET_CashFlow_out">
      <Input>GRO_CashFlow_in</Input>
      <Output>GRO_CashFlow_out</Output>
    </PointSet>
    <HistorySet name="SET_All_out">
      <Input>GRO_CashFlow_in</Input>
      <Output>GRO_CashFlow_out</Output>
    </HistorySet>
    <PointSet name="SET_IRR_out">
      <Input>batteryCapacity, GRO_construct_dispatch_in</Input>
      <Output>IRR, NPV, PI, batteryRevenue</Output>
    </PointSet>
    <PointSet name="optOutput">
      <Input>batteryCapacity,GRO_construct_dispatch_in
      
      </Input>
      <Output>NPV</Output>
    </PointSet>
    <HistorySet name="optData">
      <Input>trajID</Input>
      <Output>NPV</Output>
    </HistorySet>
  </DataObjects>

  <Steps>
    <IOStep name="read_ARMA_prices">
      <Input class="Files" type="">caisoPrice</Input>
      <Output class="Models" type="ROM">ARMA_price</Output>
    </IOStep>
    
    <MultiRun name="OPTrun" pauseAtEnd="True">
      <Input          class="DataObjects"   type="PointSet">SET_ARMA_prices_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_construct_dispatch_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_CashFlowPreP_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_CashFlow_in</Input>
      <Model          class="Models"        type="EnsembleModel">MyEnsemble</Model>
      <Optimizer      class="Optimizers"    type="SPSA">opt_smp</Optimizer>
      <SolutionExport class="DataObjects"   type="HistorySet">optData</SolutionExport>
      <Output         class="DataObjects"   type="PointSet">optOutput</Output>
    </MultiRun>
    <MultiRun name="MCrun" pauseAtEnd="True">
      <Input          class="DataObjects"   type="PointSet">SET_ARMA_prices_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_construct_dispatch_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_CashFlowPreP_in</Input>
      <Input          class="DataObjects"   type="PointSet">SET_CashFlow_in</Input>
      <Model          class="Models"        type="EnsembleModel">MyEnsemble</Model>
      <Sampler      class="Samplers"    type="MonteCarlo">energyMC</Sampler>
      <Output         class="DataObjects"    type="PointSet">MCoutput</Output>
    </MultiRun>
    <IOStep name="printMCfile">
     <Input          class="DataObjects"   type="PointSet">MCoutput</Input>
     <Output         class="OutStreams"    type="Print">dumpCSVMC</Output>
    </IOStep>
    <IOStep name="printTOfile">
     <Input          class="DataObjects"   type="PointSet">optOutput</Input>
     <Input          class="DataObjects"   type="HistorySet">optData</Input>
     <Output         class="OutStreams"    type="Print">dumpCSV</Output>
     <Output         class="OutStreams"    type="Print">dumpCSVall</Output>
    </IOStep>
  </Steps>

  <OutStreams>
    <Print name="dumpAll">
      <type>csv</type>
      <source>SET_IRR_out</source>
    </Print>
    <Print name="dumpCSV">
      <type>csv</type>
      <source>optData</source>
    </Print>
    <Print name="dumpCSVall">
      <type>csv</type>
      <source>optOutput</source>
    </Print>
    <Print name="dumpCSVMC">
      <type>csv</type>
      <source>MCoutput</source>
    </Print>
    <Plot  name="optimizationPoints" overwrite="true" verbosity="silent">
      <plotSettings>
        <plot>
          <type>scatter</type>
          <x>optOutput|Input|IP_capacity</x>
          <y>optOutput|Output|IRR</y>
        </plot>
        <xlabel>IP_capacity (W)</xlabel>
        <ylabel>IRR (p.u.)</ylabel>
      </plotSettings>
      <actions>
        <how>png</how>
        <title>
          <text>Optimization Points</text>
        </title>
      </actions>
    </Plot>
    <Plot  name="optimizationTrajectory" overwrite="true" verbosity="silent">
        <plotSettings>
            <plot>
                <type>scatter</type>
                <x>optData|Output|IP_capacity</x>
                <y>optData|Output|IRR</y>
            </plot>
            <xlabel>IP_capacity (W)</xlabel>
            <ylabel>IRR (p.u.)</ylabel>
        </plotSettings>
        <actions>
            <verticalLine>
                <x>8000000000</x>
                <ymin>0</ymin>
                <ymax>1</ymax>
            </verticalLine>
            <how>png</how>
            <title>
                <text>Optimization Trajectory</text>
            </title>
        </actions>
    </Plot>
  </OutStreams>

  <Optimizers>
    <SPSA name="opt_smp">
      <initialization>
        <limit>5000</limit>
        <type>max</type>
        <initialSeed>30</initialSeed>
      </initialization>
      <TargetEvaluation class="DataObjects" type="PointSet">optOutput</TargetEvaluation>
      <convergence>
        <iterationLimit>150</iterationLimit>
        <relativeThreshold>1.E-3</relativeThreshold>
        <gradientThreshold>1E-4</gradientThreshold>
        <absoluteThreshold>1e-5</absoluteThreshold>
      </convergence>
      <parameter>
        <numGradAvgIterations>24</numGradAvgIterations>
      </parameter>

      <variable name="batE1">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE2">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE3">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE4">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE5">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE6">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE7">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE8">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE9">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE10">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE11">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE12">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE13">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE14">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE15">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE16">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE17">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE18">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE19">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE20">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE21">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE22">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE23">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>
      <variable name="batE24">
        <upperBound>150000000.0</upperBound>   
        <lowerBound>0</lowerBound>    
        <initial>150000000.0,100000000.0,050000000.0,001000000.0</initial>      
      </variable>

      <constant name="scaling_price">1.0</constant>
      <constant name="batteryCapacity" >150000000.0</constant>  
      <objectVar>NPV</objectVar>
    </SPSA>
  </Optimizers>
</Simulation>

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Clarifying this error does not constitute an operational change and doesn't requite a specific email. Approved to close via #1864.
