### ISSUE TITLE
[UNDER-DISCUSSION] Internal network issues

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#2399]
--------
Under Discussion Topic
--------

Internal networking issues are preventing windows from cloning SRAW.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with the under_discussion type?
- [x] 2. If implemented, it will add a new requirement?
- [x] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by wangcj05** [comment]
Issue closure checklist is good.
