### ISSUE TITLE
 file used instead of open

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#24]
open should be used because that works in Python3.

**Comment by joshua-cogliati-inl** [comment]
This is from: https://hpcgitlab.inl.gov/idaholab/raven/issues/786

**Comment by alfoa** [comment]
@joshua-cogliati-inl I do not get this  . Can you explain a bit better?

**Comment by PaulTalbot-INL** [comment]
I can comment.

```python
file('my_output.csv','r')
```
works in Python 2, but not in 3.
```python
open('my_output.csv','r')
```
works in both.

**Comment by alfoa** [comment]
Ah ok....got it.
Thanks

**Comment by alfoa** [comment]
Closure checklist passed...
