### ISSUE TITLE
Windows: Command prompt does not return after plotting

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#258]
When running the workshop examples multiple users reported a problem with RAVEN failing to finish after a user closes a figure.

The fix exists, but was only active for Linux platforms. This is a single line adjustment to include Windows in the fix.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __N/A__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***yes***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) ***yes***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***not a error in results***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***n/a***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***MR***

**Comment by PaulTalbot-INL** [comment]
This appears to be a problem again if 2 plot windows are opened then closed, in Windows in particular.
