### ISSUE TITLE
Misleading error message when ROM subtype is not of allowable types.

### ISSUE THREAD

**Issue by bobkinl** [idaholab/raven#261]
When specifying an external pickled module with:

<ROM name="y3ROM" subType="PickledROM" />
(note that it should be "pickledROM")

The error message from RAVEN is:

```
(    0.25 sec) ROM                      : DEBUG           ->        qualityEstType : [u'score']
(    0.25 sec) ROM                      : DEBUG           ->        Current Setting:
(    0.25 sec) SIMULATION               : DEBUG           -> Reading type ROM with name y3ROM
(    0.25 sec) SupervisedGate           : ERROR           -> No Targets specified!!!
--------------------------------------------------
There were 1 warnings during the simulation run:
(1 time) not found attribute EndGroup in group sample_07-19-2017-11.Set True.
--------------------------------------------------
Traceback (most recent call last):
  File "/Users/bobk/projects/raven/framework/Driver.py", line 222, in <module>
    simulation.XMLread(root,runInfoSkip=set(["DefaultInputFile"]),xmlFilename=inputFile)
  File "/Users/bobk/projects/raven/framework/Simulation.py", line 749, in XMLread
    self.whichDict[Class][name].readXML(childChild, self.messageHandler, varGroups, globalAttributes=globalAttributes)
  File "/Users/bobk/projects/raven/framework/BaseClasses.py", line 107, in readXML
    self._readMoreXML(xmlNode)
  File "/Users/bobk/projects/raven/framework/Models/ROM.py", line 239, in _readMoreXML
    self._initializeSupervisedGate(**self.initializationOptionDict)
  File "/Users/bobk/projects/raven/framework/Models/ROM.py", line 250, in _initializeSupervisedGate
    self.supervisedEngine = LearningGate.returnInstance('SupervisedGate', self.subType, self,**initializationOptions)
  File "/Users/bobk/projects/raven/framework/LearningGate.py", line 222, in returnInstance
    return __interfaceDict[gateType](ROMclass, caller.messageHandler,**kwargs)
  File "/Users/bobk/projects/raven/framework/LearningGate.py", line 64, in __init__
    self.raiseAnError(IOError,'No Targets specified!!!')
  File "/Users/bobk/projects/raven/framework/MessageHandler.py", line 101, in raiseAnError
    self.messageHandler.error(self,etype,msg,str(tag),verbosity,color)
  File "/Users/bobk/projects/raven/framework/MessageHandler.py", line 314, in error
    raise etype(message)
IOError: No Targets specified!!!
```
This came up when running sample_rom.xml in branch maljdan/workshop.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Issue can be closed since no longer valid
