### ISSUE TITLE
Disappearing Data on Plots in 3D

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#263]
--------
Issue Description
--------
##### What did you expect to see happen?

I expect multiple `<plot>` tags to show multiple datasets on a single set of axes.

##### What did you see instead?

Only the last set of data is plotted.

##### Do you have a suggested fix for the development team?

No.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[plotExample.zip](https://github.com/idaholab/raven/files/1162885/plotExample.zip)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@Jimmy-INL are you planning to address it?

**Comment by Jimmy-INL** [comment]
I can try.
But I think this has less priority then PAWN and my other work with Diego.

Best,
________________________________

**Comment by alfoa** [comment]
Closure checklist passed... Closure approved via #263 

The defect can cause a wrong plot on 3D axes. An email is not required since this will be part of the RAVEN 2.0 release that will summarize all the bug fixes in 1 single email and change log.
