### ISSUE TITLE
Data Mining Post Process Does Not Copy Input Set to Output

### ISSUE THREAD

**Issue by corygoates** [idaholab/raven#265]
--------
Issue Description
--------
##### What did you expect to see happen?
When running a kMeans clustering model in a PostProcess step, I specified two separate PointSets (crescents_data and cluster_results) for input and output. I then plotted cluster_results using a cluster plotter in an IOStep. I expected a plot of the clusters in my data.

##### What did you see instead?
The application returned that my input space for the plotter (cluster_results|Input) was empty and wouldn't plot anything. To work around this, I had to specify that my input and output for the PostProcess step were both crescents_data and then fed this to the plotter. It then plotted correctly.

##### Do you have a suggested fix for the development team?
The PostProcessor should return a full set of data to the output set.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[data.zip](https://github.com/idaholab/raven/files/1163110/data.zip)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by maljovec** [comment]
Specifically, this is talking about the `<type>dataMining</type>` plot available in RAVEN. It appears that if the data is written to file, it exists, however when plotting the data, it will skip data points with a -1 label (signifies an outlier in sklearn). These points should be rendered differently to ensure that the user does not mistake them for a single cluster. Perhaps by modifying the marker/glyph in some way.

My first thought would be to make them "hollowed out" points, but it occurs to me that they would just look white. If they are sized smaller or use a different marker, the hope is that they will be different enough to not register in a user's head as part of a single cluster.
