### ISSUE TITLE
Unexpected exit in optimizer

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#269]
--------
Issue Description
--------
##### What did you expect to see happen?
When running with `debug` verbosity, the optimizer should always have an report a good reason for finishing at the end of the multirun.

##### What did you see instead?
In the special event that:
 - There are multiple trajectories,
 - The first trajectory is killed to follow the second trajectory,
 - There are outstanding runs for the first trajectory that are collected after it is killed,
 - The second trajectory is waiting to collect new opt points,
it seems that the optimizer can get caught in a loop and claim it is not ready to provide new points (since it's waiting to collect the new opt point) but also not submit any new points.

##### Do you have a suggested fix for the development team?
On inspection, this is because in GradientBasedOptimizer.localFinalizeActualSampling, if any trajectory does not have an update to solutionExport pending, then the "else" uses a "break" instead of a "continue", causing other trajectories not to be updated.

Changing this "else" seems to fix the niche issue.

Note this fix has been tested on a branch, talbpaul/optimizer_sprint_fixes, but needs a regression test to cover the bug in the future before merging onto the main development branch.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __No wrong results, instead a failure to produce results__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
@alfoa Documenting the issue that Ted found.

**Comment by alfoa** [comment]
Closing since the Optimizers are in the process of being rewritten completely...
