### ISSUE TITLE
Optimiser preconditioner vs. initail point

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#288]
--------
Issue Description
--------
##### What did you expect to see happen?
For the first iteration of the optimizer, it should be a user choice if the provided initial point is used or if the preconditioner is run to find the initial point.

##### What did you see instead?
For the first iteration, the optimizer always uses the provided initial point (or the average of min. and max. boundary if no initial point is provided) and never runs the preconditioner.

##### Do you have a suggested fix for the development team?
It is suggested that the preconditioner uses the provided initial point only if one is provided, but uses the preconditioner if no point is provided (instead of using the average of the min and max bounds). 

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
To address this issue, the following design was decided on:
 - Every input variable to the optimzation model must be provided either 1) by the user directly through the `<initial>` block, or 2) through a preconditioner in multilevel optimization.
 - If a variable does have the `<initial>` block, it must still have the same number of entries as other variables with the block
