### ISSUE TITLE
Inverse percentile

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#291]
--------
Issue Description
--------
##### What did you expect to see happen?
It would be nice to be able to give RAVEN a number and then get back the corresponding percentile from the basic statistics post processor.
For time-dependent statistics, it should be possible to specify if we want the minimum or average percentile over time.

##### What did you see instead?
This is a proposition for a new feature in RAVEN.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@AaronEpiney Can you explain the new feature a bit more? I did not get what you mean with "number"

**Comment by AaronEpiney** [comment]
By number I mean value. Here is what we have in mind:
Assume a set of observations A = [a1, a2, ... aN]
We can ask RAVEN to compute the X-th percentile, e.g. P_X(A) = value.
The proposed 'inverse percentile' functionality shroud allow to provide 'value' to RAVEN and get back 'X'.
Let me know if it is not clear.

**Comment by alfoa** [comment]
Now it is clear.
Thanks.

**Comment by wangcj05** [comment]
archived
