### ISSUE TITLE
handling infinity in the optimizer

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#302]
--------
Issue Description
--------
##### What did you expect to see happen?
Optimizer should either end or find a way to handle NaN outputs from the model being evaluated.  This may be a concern that should be addressed at the output collection level of the Model instead of the level of the optimizer.

##### What did you see instead?
Sometimes models return NaN such as "infinity" as a value for the optimization variable.  Currently, when that happens we end up with a gradient that is NaN, and step size that is NaN, and the optimization run ceases to act productively.

##### Do you have a suggested fix for the development team?
One option is to kill the run when a NaN is received.  Another option is to try to cut the spatial step if a NaN is received, in hope of finding a non-NaN value.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment]
Closure checklist passed...
