### ISSUE TITLE
EnsembleModel's use of clientQueue is used incorrectly

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#310]
--------
Issue Description
--------
##### What did you expect to see happen?

The number of jobs submitted should be capped by the `JobHandler.maxQueueSize` constant.

##### What did you see instead?

When running an EnsembleModel test case @PaulTalbot-INL was experiencing an unbounded submission of jobs before the queue was emptied.

##### Do you have a suggested fix for the development team?

The `JobHandler.__clientQueue` was not being checked for availability when using the `EnsembleModel` instead the `JobHandler.__queue` was checked.

In this case, new samples would be constantly appended to the clientQueue and the __queue would not be filled and thus would report empty spots available.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __should not affect current requirements__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __It is unclear to me if any data was lost when the jobs were submitted on top of possibly existing jobs? My assumption is that the model would fail.  I don't believe that the data would be "incorrect," but rather missing as the jobs would be labeled as failed?__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
The users affected by this change will be updated by an upcoming milestone report; since no incorrect results can be obtained, additional notification is optional.

Note that the defect itself is not directly tested, but the mechanics surrounding it are.  We don't have a methodology to test this kind of performance improvement at this time.
