### ISSUE TITLE
framework/user_guide/ravenTutorial.RomLoad's image varied

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#315]
--------
Issue Description
--------
##### What did you expect to see happen?
It to pass on all systems

##### What did you see instead?
Sometimes (such as Ubuntu 16.04) the output image would vary by 0.48 percent.

##### Do you have a suggested fix for the development team?
Increase the allowed relative error.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Guys.... no labels here..

**Comment by PaulTalbot-INL** [comment]
Yes, there seems to be some confusion about who needs to do the Issue Review (and attach labels).  Perhaps we should clarify the roles and explain them in the development guide on the wiki.

**Comment by joshua-cogliati-inl** [comment]
Who ever checked "7. The merge request must reference an issue. If the issue is closed, the issue close checklist shall be done." is the person who should check that Issue Review and Issue Close have been done :)

**Comment by PaulTalbot-INL** [comment]
That's an interesting perspective.  It seems to me the Issue Review is used to decide if development should be done, and the Issue Close is used to close the issue.  This further points out to me we don't know how to use this system consistently, collectively.
