### ISSUE TITLE
add a post-processor to handle metrics

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#322]
--------
Issue Description
--------
##### What did you expect to see happen?
This is a new feature. Based on the discussion with @alfoa, we need to develop a generalized post processor to handle the metrics that exists in RAVEN.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? __Improvement__
- [x] 2. Is it tagged with a priority: critical, normal or minor? __Normal
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __N/A__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __Not a defect__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) __Yes__

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***not a defect***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) ***not a defect***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***not a defect***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***not a defect***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***PR #323***

**Comment by alfoa** [comment]
Closure check-list passed...
