### ISSUE TITLE
Convert the Comparison Statistics to be part of the Metrics system

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#328]
--------
Issue Description
--------
##### What did you expect to see happen?
The Comparison Statistics should be a metric that can be used with any metric processing.

##### What did you see instead?
Comparison Statistics is a monolith.

##### Do you have a suggested fix for the development team?
1. Convert Comparison Statistics to use Metrics
Subparts:
a. Make Data -> CDF more independent
b. Make Metrics have a way to specify that they take CDFs or Data
c. Make Data -> CDF be able to handle weights
d. Make Comparison Statistics a metric

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

Issue Review by @joshua-cogliati-inl on 2017-Sept-6

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? _no a defect__
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) __N/A__
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?  __This PR is a new feature, and will not impact the users__ 
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? __No__
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? __a merge request is provided__

Checklists Passed. Issue Closure reviewed by Congjian Wang @wangcj05 on Oct. 4, 2017.

**Comment by wangcj05** [comment]
This issue can be closed by PR #354
