### ISSUE TITLE
 limit parameter in Sampler incorrectly parsed

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#33]
From: https://hpcgitlab.inl.gov/idaholab/raven/issues/683

The 'limit' parameter in the Sampler base class is parsed as a string rather than an int, which makes the count check in Sampler's amIreadyToProvideAnInput erroneously always return True even if the limit has been exceeded.

Changing this line in readSamplerInit(): self.limit = childChild.text to: self.limit = int(childChild.text) fixes the problem.

**Comment by mandd** [comment]
I am on it!
