### ISSUE TITLE
RAVEN running RAVEN

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#342]
--------
Issue Description
--------
##### What did you expect to see happen?
I would like to be able to spoon two levels of RAVEN calculations.

##### Do you have a suggested implementation for the development team?

A code interface for RAVEN should be implemented. In this way it will be possible to run RAVEN driving a "slave" RAVEN calculation. This can be useful to perform parametric studies on distributions, minimization of the error (based on some metrics) for Surrogates, etc.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
N/A

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? ***improvement***
- [x] 2. Is it tagged with a priority: critical, normal or minor?  ***critical***
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?  ***n/a***
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.  ***improvement***
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)  ***yes***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? *Improvement made*
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) *improvement tested*
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? *improvement, so no email needed*
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? *Not defect*
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? *Will be closed with merge request*

Issue Close reviewed by @joshua-cogliati-inl on 2017-Sept-21

**Comment by joshua-cogliati-inl** [comment]
What was happening was grep -q "Exit[s]  immediately  with  zero status if any match is found" but this causes an error in python:
https://stackoverflow.com/questions/15793886/how-to-avoid-a-broken-pipe-error-when-printing-a-large-amount-of-formatted-data
