### ISSUE TITLE
DataObject Attributes not functioning as expected

### ISSUE THREAD

**Issue by maljovec** [idaholab/raven#349]
--------
Issue Description
--------

Some of the DataObject attribute settings no longer work and the test cases do not exercise the appropriate functionality. Some of this functionality is captured elsewhere in RAVEN and some of it has not been used by the community. For the time being, I believe that the basic requirements of this feature should be made to work, but the more involved and invasive requirements can be rolled into a larger PR that looks into refactoring the DataObjects.

See PR #278 for more details.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? ***defect***
- [x] 2. Is it tagged with a priority: critical, normal or minor? ***normal***
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***n/a***
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. ***yes. But the functionalities to remove never been used by any user (no problem reported))***
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***yes***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? __Defective performance is removed and only the working parts now remain.__
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)  __Reduced functionality is tested__
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***No needed since the removed functionalities have never been used by any user***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***n/a***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***#278***

**Comment by alfoa** [comment]
Closure Check list passed...
