### ISSUE TITLE
CrossValidation does not work with newer numpy.

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#350]
--------
Issue Description
--------
##### What did you expect to see happen?
The tests to pass on newer versions of libraries.

Failed on:
```
numpy 1.13.1
h5py 2.7.0
scipy 0.19.1
sklearn 0.19.0
matplotlib 2.0.2 
```

##### What did you see instead?
```
framework/PostProcessors/CrossValidations.leaveOneLabelOut: Exception in thread 0:
framework/PostProcessors/CrossValidations.leaveOneLabelOut: Traceback (most recent call last):
framework/PostProcessors/CrossValidations.leaveOneLabelOut:   File "/home/jjc/miniconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
framework/PostProcessors/CrossValidations.leaveOneLabelOut:     self.run()
framework/PostProcessors/CrossValidations.leaveOneLabelOut:   File "/home/jjc/miniconda2/lib/python2.7/threading.py", line 754, in run
framework/PostProcessors/CrossValidations.leaveOneLabelOut:     self.__target(*self.__args, **self.__kwargs)
framework/PostProcessors/CrossValidations.leaveOneLabelOut:   File "/home/jjc/sub/raven/framework/Runners/SharedMemoryRunner.py", line 134, in <lambda>
framework/PostProcessors/CrossValidations.leaveOneLabelOut:     self.thread = threading.Thread(target = lambda q, *arg : q.append(self.functionToRun(*arg)), name = self.identifier, args=(self.subque,)+tuple(self.args))
framework/PostProcessors/CrossValidations.leaveOneLabelOut:   File "/home/jjc/sub/raven/framework/Models/PostProcessor.py", line 208, in evaluateSample
framework/PostProcessors/CrossValidations.leaveOneLabelOut:     returnValue = (Input, self.interface.run(Input))
framework/PostProcessors/CrossValidations.leaveOneLabelOut:   File "/home/jjc/sub/raven/framework/PostProcessors/CrossValidation.py", line 250, in run
framework/PostProcessors/CrossValidations.leaveOneLabelOut:     inputDict, self.CVEstimator = self.inputToInternal(inputIn, full = True)
framework/PostProcessors/CrossValidations.leaveOneLabelOut:   File "/home/jjc/sub/raven/framework/PostProcessors/CrossValidation.py", line 218, in inputToInternal
framework/PostProcessors/CrossValidations.leaveOneLabelOut:     if newInput.values().count(None) != 0:
framework/PostProcessors/CrossValidations.leaveOneLabelOut: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

##### Do you have a suggested fix for the development team?
Same general fix as bd14004ad10147654bdc8403dd7e7c37afc2ff17

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? ***improvement***
- [x] 2. Is it tagged with a priority: critical, normal or minor? ***normal***
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***n/a***
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.  (Causes crash, not wrong results) ***not a defect. New version compatibility***
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***yes***

Issue Reviewed by @joshua-cogliati-inl on 2017-Sept-13

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***not a defect***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) ***not a defect***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? ***not a defect***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? ***not a defect***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***#351***

Issue Closure Checklist Reviewed by @alfoa on 2017-Sept-13

**Comment by alfoa** [comment]
Closure check list passed...
