### ISSUE TITLE
Perturb specified word number in variable potentially broken

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#36]
This was: https://hpcgitlab.inl.gov/idaholab/raven/issues/635

To perturb a specific entry in a moose based app variable that is a list, the syntax in RAVEN is supposed to be yaml_var_path:word_number. As an example, to perturb the entry that contains 0.4 in the input containing:

```
[Materials]
  [./a]
    b = 0.1 0.2 0.4 0.5
  [../]
[]
```

you could specify the variable directly with Materials|a|b:3.  Further, the current way to specify which application a variable goes to in the MAMMOTH interface (yaml_var_path:app) conflicts with this syntax, yet there do not appear to be any tests that fail due to this conflict allowing it to be merged without incident. I believe that the culprit is the expandVarNames function in CodeInterfaceBaseClass as this appears to split the provided variable name using the colon as splitting character, but only then appears to use the first part of the key.

```
def expandVarNames(self,**Kwargs):
    """
      This method will assure the full proper variable names are returned in a dictionary.
      It primarily expands aliases. I will admit I don't know what colons do.
      @ In, Kwargs, dict, keyworded dictionary. Arguments include:
          - alias, the alias -> TrueName dictionary
          - SampleVars, short name -> sampled value dictionary
      @ Out, listDict, list, list of dictionaries. The dictionaries contain:
               ['name'][path,to,name]
               [short varname][var value]
    """
    listDict=[]
    modifDict={}
    for var in Kwargs['SampledVars']:
      if 'alias' in Kwargs.keys() and var in Kwargs['alias'].keys():
        # for understending the alias system, plase check module Models.py (class Code)
        #if var in Kwargs['alias'].keys():
        key = Kwargs['alias'][var].split(':')
      else:
        key = var.split(':')
      modifDict = {}
      if '|' not in key[0]: continue
      modifDict['name'] = key[0].split('|')[:-1]
      modifDict[key[0].split('|')[-1]] = Kwargs['SampledVars'][var]
      listDict.append(modifDict)
      del modifDict
    return listDict
```

Seeing as the Mammoth interface syntax works, this would suggest that the word number functionality is broken.

**Comment by alfoa** [comment]
We close this issue since it will be addressed in the new effort for MOOSE/RAVEN synergy
