### ISSUE TITLE
Collection/Submission deadlock in MultiRun Step

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#366]
--------
Issue Description
--------
It is possible to deadlock RAVEN in a MultiRun step if 1) the JobHandler is finished, 2) the Sampler has more points to provide, and 3) there are no new inputs to collect.  Thus far this hasn't occurred, but with killing jobs before they are collected, it is possible to get stuck in an infinite while loop.

It is recommended we flatten the collection and submission loop to:
 - Increase readability of the step,
 - Align code logic with reasonable expected behavior,
 - Prevent accidental locking/infinite loops.

This PR is necessary in order to have efficient parallel gradient operations developed for the SPSA.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Would solving #365 fix this?  (If not, then I think #365 is even less useful)

**Comment by PaulTalbot-INL** [comment]
Hm, I suspect these may be related, but the hang in this case is in `Step._localTakeAStepAndRun`, not in the JobHandler itself.
