### ISSUE TITLE
Failed runs - create a failed runs report instead of printing on screen

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#368]
--------
Issue Description
--------
When some of the RUNS failed, RAVEN is printing on screen a chunk of the screen output.
Sometimes it is in the middle of the output and gets confusing to understand which and what is actually failing
##### Do you have a suggested fix for the development team?
Probably, instead of printing on scree, a report (on file) can be created.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? ***improvement***
- [x] 2. Is it tagged with a priority: critical, normal or minor? ***minor***
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***n/a***
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. ***n/a***
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***yes***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
A a side note, printing the failures to the screen makes it easier to debug problems on the test machines where we don't have access to the filesystem.

**Comment by alfoa** [comment]
maybe a flag?

**Comment by joshua-cogliati-inl** [comment]
Hm, when do we print the failures to the screen?  Do we print them when verbosity=quiet?  Maybe only print it when verbosity=debug?  (Then we could bump it up to debug when we need to)

**Comment by alfoa** [comment]
Checklist passed. 
Closure approved via #1409
