### ISSUE TITLE
MRTAU output: exponential string missing in the numbers.csv  output file

### ISSUE THREAD

**Issue by rouxpn** [idaholab/raven#370]
[test_phisics_code_interface.zip](https://github.com/idaholab/raven/files/1325395/test_phisics_code_interface.zip)

--------
Issue Description
--------
##### What did you expect to see happen?
in the numbers.csv output, I expect to see

0.0000000000E+00, 6.9533376307-310, 1.7618744563**E**-315, 0.0000000000E+00, 0.0000000000E+00
 2.0000000000E+01, 1.9386057035E-02, 2.4336425587E+00, 3.9436415617E+01, 0.0000000000E+00
 4.0000000000E+01, 1.9386054027E-02, 2.4336425586E+00, 3.9436415617E+01, 0.0000000000E+00
 6.0000000000E+01, 1.9386051020E-02, 2.4336425585E+00, 3.9436415616E+01, 0.0000000000E+00
 8.0000000000E+01, 1.9386048012E-02, 2.4336425583E+00, 3.9436415616E+01, 0.0000000000E+00
 1.0000000000E+02, 1.9386045005E-02, 2.4336425582E+00, 3.9436415616E+01, 0.0000000000E+00
 1.0200000000E+02, 1.9386044704E-02, 2.4336425582E+00, 3.9436415616E+01, 0.0000000000E+00
 1.0400000000E+02, 1.9386044403E-02, 2.4336425582E+00, 3.9436415616E+01, 0.0000000000E+00

##### Do you have a suggested fix for the development team?
The first line of floating numbers is missing exponential string "E". 

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[Depletion_input.txt](https://github.com/idaholab/raven/files/1325375/Depletion_input.txt)
[Depletion_input.txt](https://github.com/idaholab/raven/files/1325403/Depletion_input.txt)

[test_phisics_code_interface.zip](https://github.com/idaholab/raven/files/1325404/test_phisics_code_interface.zip)
[numbers-0.txt](https://github.com/idaholab/raven/files/1325410/numbers-0.txt)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Can you attach the raven input as well?  Thanks.

**Comment by alfoa** [comment]
Hem... this is not RAVEN related... 

Wrong repository?

**Comment by rouxpn** [comment]
Okay actually no I thought this was raven related but this is not. 
actually, mrtau standalone prints correctly the numbers.csv values. Insant + mrtau doesn't
