### ISSUE TITLE
Adaptive and default parameters in Optimizer

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#39]
--------
Issue Description
--------
##### What did you expect to see happen?
Many parameters should self-adjust and have good defaults in the SPSA optimizer sampling.

##### What did you see instead?
The user currently provides static values or accepts defaults that may correspond poorly to the problem's needs.

##### Do you have a suggested fix for the development team?
Consider methods for calculating good defaults and adapting on-the-fly based on the optimization development.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed...

Closure approved via #1163 (New optimization class)
