### ISSUE TITLE
Add SciKitLearn regression metrics inside RAVEN Metric system, and some modifications in Cross Validation

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#396]
--------
Issue Description
--------
##### What did you expect to see happen?
Add some new metrics, and some modifications in RAVEN Metrics and Cross Validation PP
Raise an error when the input keywords is not expected by the Metrics. 
Only allow to use regression metrics inside Cross Validation PP, and rename the outputs of metric results to enable the use of the same type of metrics with different names in the Metric PP and Cross Validation PP.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved for closure.  Note the issue review, usually performed before development starts, was not performed for this issue.
