### ISSUE TITLE
Protect the users from using Sobol and GaussianPolynomial ROMs inside the HybridModel and CrossValidation

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#403]
--------
Issue Description
--------
Currently, the Sobol and GaussianPolynomial ROMs should not be used inside the HybridModel and CrossValidation post-processor. This is because this type ROMs are constructed using the stochastic collocation method, and can not be retrained using the current structure of HybridModel and CrossValidation post-processor.
##### Do you have a suggested fix for the development team?

An error should be raised if this type of ROMs are used in the HybridModel and CrossValidation post-processor.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? __improvement__
- [x] 2. Is it tagged with a priority: critical, normal or minor? __minor__
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __N/A__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __N/A__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) __Yes__

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved to close via merge.
