### ISSUE TITLE
Consistent Module Imports

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#42]
--------
Issue Description
--------
##### What did you expect to see happen?
Consistent, modular imports throughout RAVEN

##### What did you see instead?
Fiddling with PYTHONPATH and some inconsistency in when some modules can import others safely, as well as occasional imports in the body of python modules

##### Do you have a suggested fix for the development team?
We should probably continue towards making RAVEN more library-like, so that our imports all happen in a consistent way.

----------------
For Devs: Issue Review
----------------
- [x] 1. Is it tagged with a type: defect or improvement? __tagged__
- [x] 2. Is it tagged with a priority: critical, normal or minor? __tagged__
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __n/a__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __n/a__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) __provided__

-------
For Devs: Issue Closure
-------
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Note that when this is fixed, we can probably add some useful checks to the pylint checks in developer_tools/pylint_list  and developer_tools/pylint_check

**Comment by joshua-cogliati-inl** [comment]
I think this might have gotten fixed at somepoint, but never closed.  As in I think the great renaming of ```import utils``` to ```import utils.utils``` fixed this.

**Comment by joshua-cogliati-inl** [comment]
Hm, fixing this might be required for #1764 to get a reasonable wheel created.
