### ISSUE TITLE
import an Event-Tree into RAVEN

### ISSUE THREAD

**Issue by mandd** [idaholab/raven#422]
This issue refers to the possibility to add capability of importing Event-Tree structures into RAVEN
--------
Issue Description
--------
##### What did you expect to see happen?
Not a defect

##### What did you see instead?
Not a defect

##### Do you have a suggested fix for the development team?
Create a PP that import anET structure from file and save it as a PointSet

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
NA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __N/A__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __not a defect__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? __not a defect__
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) __not a defect__
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? __no impact on users__
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? __not a defect__
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? #421 

Issue closure checklists reviewed by Congjian Wang @wangcj05 on Nov. 22, 2017

**Comment by wangcj05** [comment]
Issue closure checklists are satisfied, this issue can be closed now.
