### ISSUE TITLE
Sensitivity Calculation: detection method for multicollinearity for linear regression inside basic statistics post-processor

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#427]
--------
Issue Description
--------
Migrated from issue 701 on gitlab.

Adding multiple collinear targets when calculating sensitivities results in different results than calculating for each target separately.

See [here](https://hpcgitlab.inl.gov/idaholab/raven/issues/701) for more details.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
This issue will be treated as task instead of defect. It is not the defect of RAVEN, but a general issue for the linear regression. An detection method is implemented by PR#928, and a warning will be raised.

**Comment by wangcj05** [comment]
Issue closure checklist are good.
