### ISSUE TITLE
RELAP5-3D executable in a dedicated folder

### ISSUE THREAD

**Issue by CarloParisi** [idaholab/raven#436]
--------
Issue Description
--------
##### What did you expect to see happen?
Running multiple cases with RAVEN/RELAP5-3D for Limit Surface Search, Monte Carlo sampling etc.

##### What did you see instead?
Random failures of the RAVEN/RELAP5-3D with error messages "text file busy". RELAP5-3D is copied in some directories but input deck are not run.

##### Do you have a suggested fix for the development team?
In the manual/user guide the following should be reported:

RELAP5-3D exe should be in a dedicated separate folder. It should not be copied in all the directories, therefore it should not be specified in the RAVEN  <Input> node, but just in the <Code>...<executable>path_to_RELAP</executable>. Instead RELAP5 input deck file, the license file and the water tables file should be specified in the <Input> node.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by CarloParisi** [comment]
@alfoa  @mandd

**Comment by CarloParisi** [comment]
@mandd  @alfoa

**Comment by alfoa** [comment]
It has been identified that the problem was in RELAP5...

Closing
