### ISSUE TITLE
Limit Surface Search termination before convergence reached

### ISSUE THREAD

**Issue by CarloParisi** [idaholab/raven#437]
--------
Issue Description
--------
##### What did you expect to see happen?
Limit Surface Search (LSS) should terminate when LS convergence is reached.

##### What did you see instead?
Run is terminated prematurely if number of cores > persistence parameter. The number of LSS runs is thus limited to the number of persistence parameter. E.g., if ncore=192 and persistence=100, only 100 RELAP5-3D runs will be performed by the LSS algorithm.

##### Do you have a suggested fix for the development team?
Temporary fix : provide warning in the user manual/guide, suggesting temporary run criterion ncores>persistence. Then fix the code.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by CarloParisi** [comment]
@alfoa @mandd

**Comment by PaulTalbot-INL** [comment]
Note the issue review was not performed for this issue, but it was closed by work inspired by other issues. Approved to close via #915.
