### ISSUE TITLE
keyword "interfacecheck" is ignored by "run_framework"

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#440]
--------
Issue Description
--------
##### What did you expect to see happen?
```run_framework``` should work with keyword ``interfacecheck``

##### What did you see instead?
```interfacecheck``` is ignored.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@wangcj05 the closure checklist

**Comment by alfoa** [comment]
Closure checklist passed... No email is needed since the problem was effecting a "testing" feature that we currently not expose to the users

**Comment by wangcj05** [comment]
Should do, I just get used to data-object rework branch.

On Mon, May 21, 2018 at 5:03 PM, Andrea Alfonsi - INL <
notifications@github.com> wrote:

> Closure checklist passed... No email is needed since the problem was
> effecting a "testing" feature that we currently not expose to the users
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_idaholab_raven_issues_440-23issuecomment-2D390808676&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=vJsbMjnzR6ErmdvVqv2kNhwbKhk1o91w6B8VQ4EHCto&m=9uhi2lzr944XUYz-7pd9CjKIhlm6kq6XIMT7n6h5ihA&s=R8udXvoF-V8Uko9uaobuvdUV3L7V0Xnt7Y9gRrl1jPI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG-2D17y7X0ZCuMhei5lbbFCkVaLR1w89Uks5t00fXgaJpZM4Qtqe1&d=DwMCaQ&c=54IZrppPQZKX9mLzcGdPfFD1hxrcB__aEkJFOKJFd00&r=vJsbMjnzR6ErmdvVqv2kNhwbKhk1o91w6B8VQ4EHCto&m=9uhi2lzr944XUYz-7pd9CjKIhlm6kq6XIMT7n6h5ihA&s=yE3pt5pKc0etyv0sY4f0gdD0l7fCaeoyn-47qDducpM&e=>
> .
>



-- 
Sincerely,

Congjian Wang

PhD, Nuclear Engineering Methods Development, INL
2525 North Fremont Ave., Idaho Falls, ID 83415-3860
Work Phone: 208-526-7220
