### ISSUE TITLE
missing attribute for SKLearn unsupervised learning nodes

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#45]
In clustering and PCA postprocessing models, there is a `labelFeature` attribute used in the test cases that isn't documented in the user manual.

Additionally, postprocessors that add a column to a data object should identify this behavior in the user manual (this might be a bigger issue).

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
We have following tests using the labelFeature: 
![image](https://user-images.githubusercontent.com/7321071/174899436-29df3f2b-19d8-4c6e-b404-9caa04b59622.png)

and we have the following documentation in the section of DataMining: 
![image](https://user-images.githubusercontent.com/7321071/174899623-5fd15099-479c-48c6-889d-91c58f871fd8.png)

I think we need to have a better description about it, and I think this issue can be properly addressed when we use the InputData for DataMining postprocessor to generate our manual. For now, I think the manual do document the feature.
