### ISSUE TITLE
Run terminated for memory?

### ISSUE THREAD

**Issue by CarloParisi** [idaholab/raven#454]
--------
Issue Description
--------
##### What did you expect to see happen?
Run the LSS. Sometimes get errors like this from HPC. 

##### What did you see instead?
IOError: There were 13 failed runs; aborting RAVEN.
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/apps/local/easybuild/software/Python/2.7.9-gmvolf-5.5.4/lib/python2.7/threading.py", line 763, in run
  File "/home/paric/projects/raven/framework/JobHandler.py", line 292, in startLoop
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'
****

FROM HPC got the following...

The following falcon jobs belonging to (paric) were killed by PBS CGroups because the amount of memory your job actually used exceed the amount of memory you requested in your PBS script.

##### Do you have a suggested fix for the development team?
No @alfoa  @mandd 

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
archived
