### ISSUE TITLE
CSVs and Metadata

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#456]
There is some discussion and decisions that need to be made regarding CSV files, metadata, and restarting.

## How it used to work
Previous to the data object rework, a CSV file was considered both a user-friendly output option that could be loaded up in a spreadsheet tool and looked at, as well as a data storage option that could be restarted from later.

## The problem
With the data object rework, we now include pointwise metadata with the main point as additional columns, instead of in a separate dictionary/XML tree, whereas general metadata is still stored in an XML structure.  This provided immense speedup in IO for data objects.

Printing these CSVs presents a conundrum.

 - If we omit printing the pointwise metadata such as `ProbabilityWeight` entirely, then the CSV cannot be restarted.
 - If we force the user to have the metadata in their CSV, then we remove power from the user to control their output files.
 - If, when printing the CSVs, we put the metadata back into the XML, we notice slowdown in writing.

As of the dataobject rework currently, restarting a `MultiRun` sampling using a CSV will always work, but loading a CSV without the metadata printed will not work in postprocessors like `BasicStatistics`.

## Moving forward
There are a few possibilities for how to move forward.
 1. By default print metadata into the CSVs.  If the user requests specific variables in their CSV, we instead push the metadata into the auxiliary XML file.
 1. Disallow restarting from a CSV except in the case where the user does not request special printing.  Instead, only allow restarting from databases.
 1. Add a third output CSV, an auxiliary CSV, to house the pointwise metadata.  We can either make the auxiliary CSV capable to be disabled by the user or forced regardless.

----------------
----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
@AaronEpiney in particular presented his view that a CSV does not seem like a restart tool to him, adding to some of the action items.

In a discussion with @alfoa, he suggested the first option under the Moving Forward section, which is a good choice is there's no further discussion.

**Comment by AaronEpiney** [comment]
How does option 1(under the Moving Forward section) handle the case where the user only asks for part of the input/output space to be printed to csv? Even if you have the metadata in a separate xml, you will not be able to restart, since you won't have the full input/output space?

In my opinion, 'user output' and 'restart' should be 2 different capabilities with the possibility to be controlled separately, i.e. 'restart file creation' yes/no, and output csv 'everything' or a 'selection of variables'.
