### ISSUE TITLE
Regression test script runs plugin tests multiple times

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#475]
--------
Issue Description
--------
##### What did you expect to see happen?
The regression test system should run each test only once.

##### What did you see instead?
When ./run_tests is executed, the plugin tests are run multiple times.
I did not check if other test are run multiple times as well...

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
Here is the (shortened) output from ./run_tests
```AutoHotkey
plugins/CashFlow.CashFlow_NPVsearch.................................................... OK
plugins/CashFlow.CashFlow_IRR................................................................ OK
plugins/CashFlow.CashFlow_PI.................................................................. OK
plugins/CashFlow.CashFlow_NPV....................... ....................................... OK
...
plugins/CashFlow/tests.CashFlow_IRR........................................................ OK
plugins/CashFlow/tests.CashFlow_NPV....................................................... OK
plugins/CashFlow/tests.CashFlow_NPVsearch............................................ OK
plugins/CashFlow/tests.CashFlow_PI.......................................................... OK
...
```

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
This has been resolved with the new plugin regression system.
