### ISSUE TITLE
Improve the CSV checking

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#50]
From https://hpcgitlab.inl.gov/idaholab/raven/issues/133

Right now there are two CSV checkers, the CSVDiffer.py and the UnorderedCSVDiffer.py  They have somewhat different abilities.

Original Text:
Right now the regression tests only can check CSV files that have one line of header, followed by equal numbers of numbers. It would be useful if this could be changed.

Possibly we should have two comparison, one for column type CSV (what we currently have) and one for free format CSVs, and the freeformat would not have the restrictions, and also would require that the columns stay in the same order.

This will require modification to scripts/TestHarness/testers/RavenFramework.py

Comments on Gitlab:
We can check unordered rows, but we can't check unordered columns, or mismatched lengths, as far as I'm aware. Unless someone else added this....

**Comment by wangcj05** [comment]
archived
