### ISSUE TITLE
ANL cluster parameter settings

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#516]
--------
Issue Description
--------
##### What did you expect to see happen?
It would be good to have a general factory/config file system to handle different cluster job handlers like PBS, torque, etc.
-> A design for this system, like who handles the config files, where are they stored, what is accessible form the RAVEN input file, etc. needs to be thought of.

##### What did you see instead?
Right now, every new job handler in every new institution has to change the job handler scripts provided by RAVEN. 

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Can we have a description of the deviations we need to perform for the new clusters we have experience with? 

we can come up with a generalization scheme

**Comment by PaulTalbot-INL** [comment]
In my one experience I had to create a new SimulationMode and a new raven_qsub_script.sh to be compliant with the scheduler (torque instead of pbspro).  The modified files reside on the remote server and are supposedly not maintained by us.

**Comment by wangcj05** [comment]
archived
