### ISSUE TITLE
Increased IOStep Explanations in User Guide

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#54]
Right now there's not much explanation on how to use the IOStep variants in the user manual.  While this might be a job for the user guide, somewhere we should explain things like loading CSV into data objects, outstreaming to CSV, what happens when you IO to/from an HDF5, etc.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
There is a section in User Guide to explain "IOStep", I believe we can expand it to include more guide information for users.

**Comment by wangcj05** [comment]
archived.
