### ISSUE TITLE
MOOSE Input Parse Fails on Hanging Quote

### ISSUE THREAD

**Issue by elementx54** [idaholab/raven#540]
--------
Issue Description
--------
##### What did you expect to see happen?
I was using Raven to do a parametric study for statistics on a MOOSE app. The MOOSE input file had a block that looked like this:
```
[Mesh]
  type = GeneratedBIDMesh # [cm]
  dim = 3
  xmin = 0.0
  xmax = 9.652
  ymin = 0.0
  ymax = 9.652
  zmin = 0.0
  zmax = 252.9320455
  nx = 2
  ny = 2
  nz = 23
  elem_type = HEX8
  subdomain = '
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  ' # 1 is outer, 2 is inside
  uniform_refine = 1
  1 Volume: 11269.4658501452 cm3
  2 Volume: 12293.962745613 cm3
[]
```
When Raven parsed the input file and did the code run, it messed up and put the " ' # 1 is outer, 2 is inside" line somewhere in the middle of the MOOSE block. The new block did not look like the original block and app had an error due to trying to convert parameter names to integers because it could not find the closing '.  

My **work around** was to change the code block to:
```
[Mesh]
  type = GeneratedBIDMesh # [cm]
  dim = 3
  xmin = 0.0
  xmax = 9.652
  ymin = 0.0
  ymax = 9.652
  zmin = 0.0
  zmax = 252.9320455
  nx = 2
  ny = 2
  nz = 23
  elem_type = HEX8
  subdomain = '
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  2 2 2 2
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1
  1 1 1 1'
  # 1 is outer, 2 is inside
  uniform_refine = 1
  1 Volume: 11269.4658501452 cm3
  2 Volume: 12293.962745613 cm3
[]
```
where the hanging ' is now on the line with the 1 1 1 1' instead of on the line with the comment. This worked just fine and the app ran and Raven did the job. The side note is that the MOOSE app is able to run both blocks just fine. Only when the original block went through Raven did the input block get messed up.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed.

An email should be sent.

Closure approved via PR  #1204
