### ISSUE TITLE
Output file selection in GenericCodeInterface

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#541]
--------
Issue Description
--------
##### What did you expect to see happen?
I should be able to tell RAVEN which output file(s) from my code that I want it to read results from.

##### What did you see instead?
RAVEN expects to rename the output file to a name of its own selection, which isn't convenient for all codes that use the GenericCodeInterface.

##### Do you have a suggested fix for the development team?
Remove the "out~" naming convention and instead allow the user to identify which output file to read.

This issue comes at the request of a user from a Jan 24, 2017 email thread to the RAVEN user group.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
@alfoa Here's an issue posting for the feature request we discussed this morning.

**Comment by alfoa** [comment]
Portion of the email sent by the user:

```
For example, for my input called "test.in" the results are "test_n.csv", "test_m.csv",  "test_s.csv", etc.
From these outputs I'm only interested in   "test_n.csv" .

I tried this input :
<Files>
    <Input name="originalInput" type="cfast_input">test.in</Input>
  </Files>

  <Models>
    <Code name="CFAST" subType="GenericCode">
      <executable>/home/user/cfast/CFAST.exe</executable>
      <clargs arg="wine" type="prepend"/>
      <clargs arg="" extension=".in" type="input"/>
      <fileargs   type="output" arg ="test_n.csv" /> 
      
    </Code>
  </Models>

The error message is  "No such file or directory: u' /home/user/cfast/CFASR_RUN_DIR/runMC/3/out~test.csv
```

**Comment by PaulTalbot-INL** [comment]
This is an expansion of existing tools, not a change in the input structure, so no additional notification needs to be made.
