### ISSUE TITLE
Lack of MELCOR radionuclide output data parsing

### ISSUE THREAD

**Issue by MagresTR** [idaholab/raven#544]
--------
Issue Description
--------
##### What did you expect to see happen?
To be able to parse MELCOR radionuclide location and movement tracking data.

##### What did you see instead?
The MELCOR-RAVEN interface can currently only parse hydrodynamic data from the CVH package - control volume pressure, temperature, void fraction, etc.

##### Do you have a suggested fix for the development team?
MELCOR control function data parsing would indirectly allow RAVEN to handle essentially any kind of data produced by MELCOR. To the best of my knowledge, anything in MELCOR can be passed into a control function inside of MELCOR, so if RAVEN can process CF data then any desired values can become parse-able outputs.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

[BWR_v2-2_Output.txt](https://github.com/idaholab/raven/files/1661214/BWR_v2-2_Output.txt)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure check list passed...
