### ISSUE TITLE
SKL Time-Dependent (consistent times)

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#554]
--------
Issue Description
--------
##### What did you expect to see happen?
A model with consistent "time" output values should train a time-dependent SciKitLearn ROM as well as any other model/ROM combination.

##### What did you see instead?
The ROM only trained on the first realization's values, and ignored the rest.

##### Do you have a suggested fix for the development team?
Fix the logic in the SupervisedLearning.SciKitLearn ROM.  Right now it checks if _any_ of the variables have the same output in all realizations; if so, use all the data from only the first realization.  What it should do is check if _all_ of the variables have the same output in all realizations.

Note there is not a good regression test for time-dependent SKL ROMs right now.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __since the fix is fast, we can email when we fix it__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
checklist passed
