### ISSUE TITLE
Encapsulating in Samplers

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#57]
Right now there is a lot of duplicated methods/structures/conditionals in the Samplers, hopefully some of which can be removed.  Right now it is a jungle for new developers trying to determine what a Sampler should do, and how.  The idea is to list some here as they are seen, which can then be addressed.

Fully Coupled Variables
===========================
Often, the following is seen in the `localGenerateInput` methods:
```python
  for kkey in varID.strip().split(','):
    self.values[kkey] = value
```
To prevent the developer from knowing WHY he has to loop over entries in varID, and since all samplers do this, we can implement a method in the base class like
```python
  def placeValue(self,variable,value):
    for var in variable.strip().split(','):
      self.values[var] = value
```

Multidimensional
=====
Each `localGenerateInput` has some kind of checker to see if the dimensions used is one or more.  It would be great if we could abstract the sampling to remove most of the duplicated code in these portions.

Point Probability
=====
Each `localGenerateInput` sets the `self.inputInfo['SampledVarsPb']` using the PDF of the point, which might be through a variety of different methods depending on transformed space, multidimensional distribution, coupled variables, etc.  It would be developer-friendly to abstract this if reasonably possible.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment]
Not valid anymore
