### ISSUE TITLE
variable name for percentile in BasicStatistics postprocessor

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#577]
--------
Issue Description
--------
##### What did you expect to see happen?

The RAVEN user manual explains how the BasicStatistics post-processor creates the variable names for the quantities the user asks for (in 17.5.1 BasicStatistics). Under "prefix", the manula explains that the variable names are created as “prefix” + “_” + “parameter name” for scalar quantities like the "expectedValue" or the "percentile". 

##### What did you see instead?
For the "percentile", RAVEN creates the variable name according to “prefix” + “_” + "percent" + "_" + “parameter name”.

##### Do you have a suggested fix for the development team?
Update the RAVEN manual and include an explanation how variable names are constructed for percentiles in the BasicStatistics post processor.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@AaronEpiney @PaulTalbot-INL is this still valid?

**Comment by AaronEpiney** [comment]
Don't know if this has been addressed as part of the re-work.
Maybe @PaulTalbot-INL knows.

**Comment by PaulTalbot-INL** [comment]
There is not an explanation for how the percentiles are named using the prefix, percentile, and variable name.  I honestly get it wrong first try most of the time.

**Comment by dgarrett622** [comment]
@wangcj05 I checked in the current user manual and it looks like this is fixed. Here is what the current user manual says under "prefix" for BasicStatistics:

> For percentile, RAVEN will define a variable with name defined as: “prefix” + “ ” + “percent” + “ ” + “parameter name”. For example, if we define “perc” as the prefix for percentile, percent as “10”, and parameter “x”, then variable “perc 10 x” will be defined by RAVEN.

I believe this issue can be closed.
