### ISSUE TITLE
Code alias check

### ISSUE THREAD

**Issue by mandd** [idaholab/raven#588]
--------
Issue Description
--------
##### What did you expect to see happen?
if a set of alias variables in a code models are not being generated by the sampler, the code should stop or warn the user

##### What did you see instead?
RAVEN just performs the runs with what it has available

##### Do you have a suggested fix for the development team?
A check should be performed at the code interface level: the set of alias variables should be found in the set of input variables

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
I generally agree with the premise that Code models should have some assurance that they use all Sampled values.

However, I'm not 100% sure that requiring all aliases to be used is the right answer.  Quite frequently in users' input files I see long lists of aliases that they may not all use in any particular simulation, but want to leave there in case they want to use again later. 

While a user can technically comment out any aliases they are not using, that hasn't been the way we've done the rest of the input file; we're perfectly fine having unused entities defined throughout the input file.
