### ISSUE TITLE
RAVEN interface and ExternalXML

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#593]
--------
Issue Description
--------
##### What did you expect to see happen?
When using the RAVEN interface:

If the "inner" RAVEN uses ExteranlXML, the outer run should not be affected.

##### What did you see instead?
If, for example, the OutStreams are in the main "inner" file and the DataObjects are in an ExternalXML file, the RAVENparser will crash with (for example):
```
IOError: RAVEN_PARSER ERROR: The OutStream of type "Print" named "dumpOPT" is linked to not existing DataObject!
```

##### Do you have a suggested fix for the development team?
Expand the necessary ExternalXML nodes before parsing the XML.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure check list passed...

Closing...
