### ISSUE TITLE
Python standards in testing system

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#61]
While we have an established set of standards for Python when writing Raven framework modules, these standards conflict with the Python-based Moose testing system, since we largely inherit from it.

We should decide what to do about this conflict, and whether our standards apply without exception to the testing system.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
This issue is not valid anymore.
We have our standards, MOOSE has his own

**Comment by PaulTalbot-INL** [comment]
This is still quite valid, as we have syntax in our testing harness that does not respect our standards.

For example, the RavenFramework Tester is rife with underscore-using variable names that are not used outside our code.

**Comment by alfoa** [comment]
I consider the test harness and specialization class in the ```contrib``` conceptual framework. 

But, we can address this

**Comment by alfoa** [comment]
Closing...
