### ISSUE TITLE
Conda after version 4.4 changes behavior

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#616]
--------
Issue Description
--------
Starting with conda version 4.4, the bashrc edit to make conda available changes from a path modification to a script running.

As a result, `which conda` no longer returns anything even if it exists.  This nullifies the script `raven/scripts/establish_conda_env.sh` because it checks for conda's existence using "which". 

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
This is an important issue...
Did we address it yet or planning to in the near near future?

**Comment by PaulTalbot-INL** [comment]
I think we addressed this, as far as I'm aware, via the "conda-defs" and `ravenrc` storage. Closed by #618.
