### ISSUE TITLE
Bad message in ExternalXML parsing message

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#62]
When reading an input XML with `ExternalXML` nodes, if there is a fundamental XML error (such as mismatched tags), the reported line number for the problem is with respect to the reconstructed XML, not the original, so it's quite difficult to locate what file the error is in.

This could be cleaned up by catching the error and raising it with more useful information when we attempt to read the external XML files.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
with the fix in #1864, the error for single input file looks like:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/7321071/174950004-559cfd2c-ead3-4670-80e6-34c4a737499b.png">

and the error for external xml file looks like: 
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/7321071/174950070-3ea3f5d5-e354-4873-a259-33026f1bd859.png">

**Comment by PaulTalbot-INL** [comment]
Changes to the error message do not constitute an operational change and don't requite a specific email. Approved to close via #1864.
