### ISSUE TITLE
Optimizer paths not identical

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#624]
--------
Issue Description
--------
When the optimizer (specifically SPSA) searches a path, it should always take the same path if seeded, with only minute differences due to operating system roundoff and similar issues.

However, even when seeded  and running on a single operating system, the same test run multiple times can take a slightly different path.  While it generally starts and ends the same, there are deviating points in the middle.

This effect has been noticed in most optimizers with longer paths (>100 iterations); in particular, the `framework/Optimizers.Vector` _usually_ does not respect identical pathing from one run to another below 5e-8 relative tolerance.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed...

Closure approved via #1163 (New optimization class)

If this problem appears again, please reopen the issue
