### ISSUE TITLE
Reading input space from Code output

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#63]
As per a team meeting discussion held on April 4, 2016, a few concepts about restarts came forward.

When RAVEN stores a sample in a data object, it reads the input space first from the output of the model, if possible, then the internal storage, if not available.

This can create an issue of the output of the model returns low-resolution values, as these values will not match the searched-for values in a restart.

We discussed adding a flag that will trigger the above behavior when desired, but by default will use RAVEN internal values first when possible.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
I believe this issue related to restartTolerance, which allows users to input the tolerance for restart point. This feature was implemented two years ago. I believe this issue has already been fixed.
