### ISSUE TITLE
Relative path for ExternalXML

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#65]
Currently when using relative pathing, ExternalXML paths start at the run directory, not the `WorkingDir` directory.  This is confusing from a user standpoint, as most entities have been standardized to work from the working directory.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Comment from wangc on gitlab:

The purpose for ExternalXML is to load external xml input file input main raven xml input file. Every node except the root can be loaded from external xml file. This is done before parse the main raven input file. The ExternalXML paths start at the run directory, this is because the WorkingDir directory is not known at this point. The WorkingDir directory will be assigned when the main raven input file is parsed.

**Comment by wangcj05** [comment]
@Jimmy-INL Please check this issue and Issue #86 about the path issues with input files. Please let me know if you want to resolve these issues. Otherwise, I will start to work on it.

**Comment by wangcj05** [comment]
closed with #1870
