### ISSUE TITLE
Error message for unhandled constant vector in distribution

### ISSUE THREAD

**Issue by jchen56** [idaholab/raven#677]
--------
Issue Description
--------
##### What did you expect to see happen?

Used <constant> to define a variable in <Distribution>. Added <shape>10</shape> while the driven code can't handle the constant vector instead of scalars.

##### What did you see instead?

Expected the variable to stay constant for the distribution. Yet RAVEN passed the constant vector instead of one scalar to the code, leading to wrong inputs for the driven code and RAVEN returned a failed runs error message.

##### Do you have a suggested fix for the development team?

Add error message like "Driven code can't handle constant vector. Remove <shape> in <Distribution> for variable "var".

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
We need to have a design talk about how we want models to be self-aware about handling vector variables, both Codes as well as ROMs, ExternalModels, etc.
