### ISSUE TITLE
Alias for pickled ROMs

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#678]
--------
Issue Description
--------
It wold be nice to have the possibility to change variable names from pickled ROMs.
An extension of the alias system to be used with ROMs is suggested.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
It's worth trying, but the pickledROM is not quite like other ROMs; it's an empty placeholder replaced by the pickled instance.  Aaron wants to add aliases a posteriori to the pickled ROM instance, which would probably require additional code to make work.

**Comment by AaronEpiney** [comment]
Added an alias to the ROM, like 
<ROM name='MyARMA' subType='pickledROM'>
   <alias variable="Time1" type="output">Time</alias>
</ROM>

and that did the trick.

**Comment by alfoa** [comment]
Fanstastic....so it works...
I close the issue.... Please reopen it in case you experience another problem...

**Comment by alfoa** [comment]
Closure checklist passed...
It worked...
