### ISSUE TITLE
imread issue with the image check

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#687]
--------
Issue Description
--------
The tests on the Falcon failed due to the image diff.

##### What did you see instead?
framework/user_guide/ForwardSamplingStrategies.Grid ............................................... RUNNING...
runWorker Exception: Traceback (most recent call last):
  File "/home/chenj/RAVEN/raven/moose/python/TestHarness/schedulers/Scheduler.py", line 605, in runWorker
    self.run(job_container)
  File "/home/chenj/RAVEN/raven/moose/python/TestHarness/schedulers/RunParallel.py", line 46, in run
    self.testOutput(job_container, output)
  File "/home/chenj/RAVEN/raven/moose/python/TestHarness/schedulers/RunParallel.py", line 53, in testOutput
    output = tester.processResults(tester.getMooseDir(), self.options, output)
  File "scripts/TestHarness/testers/RavenFramework.py", line 192, in processResults
    return self.rawProcessResults(moose_dir, options, output)
  File "scripts/TestHarness/testers/RavenFramework.py", line 277, in rawProcessResults
    (imgSame,imgMessages) = imgDiff.diff()
  File "scripts/TestHarness/testers/RAVENImageDiff.py", line 101, in diff
    diff = goldImage - testImage
TypeError: unsupported operand type(s) for -: 'instance' and 'instance'

Running the tests on local machine works fine. I loaded pbs and raven-devel-gcc modules on HPC. I wonder if I should load other modules?

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
From link:
https://stackoverflow.com/questions/8404956/installing-pil-with-jpeg-support-on-mac-os-x/12194881#12194881
Worth noting and good information to have whenever working with Python and PIL: If you use virtualenv (and I think it's a very good idea), PIL may not correctly detect the image libraries on your system and install without JPEG/PNG support. Use the pillow package for a compatible PIL fork that finds them correctly.

**Comment by PaulTalbot-INL** [comment]
We only ever install PIL through pillow.  If a user has PIL, then I would be curious to know how they got it.

**Comment by wangcj05** [comment]
I have tried:
```
[wangc@falcon2 testers]$ module purge
[wangc@falcon2 testers]$ module load raven-devel-gcc
```
Then PIL is found:
```
 '/apps/local/easybuild/software/PIL/1.1.7-GCC-4.9.2-Python-2.7.9/lib/python2.7/site-packages/PIL'
```

**Comment by PaulTalbot-INL** [comment]
Interesting; that is the right line of questioning to pursue.  

For what it's worth, In the libs update branch #668, we will discontinue use of the raven-devel-gcc module and use conda for everything, and pillow is used if the optional libraries are requested.

**Comment by alfoa** [comment]
Addressed by new reg test system.

Closure checklist passed...
