### ISSUE TITLE
Grid-like datasets are not scaled correctly in the DataSet

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#690]
--------
Issue Description
--------

When one restart the calculation, the dataset will be scaled before retrieving the realization from that dataset. If grid-like sampler is used, the scale factor could be zero, since the grid points for some variable could be constant, this will cause the failure of the restart capability as recently reported by one of our users. 

##### What did you expect to see happen?
The grid sampler with restart should work.

##### What did you see instead?

From raven user:
```
so I started a test without the meshfile variable. Left it running for some time so I had a dataset of 34 restart points. Then cancled Raven and tried to restart from the previous results but again the same error and Raven ignored the restart points completely and started sampling the same points again that already exist in the restart data.
```

##### Do you have a suggested fix for the development team?
@mandd and I found we have an issue with the SCALE in the DataSet. The fix can be found in 
https://github.com/idaholab/raven/tree/wangc/std_issue 

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
closure check list passed...

No email to users is necessary since this issue can not cause wrong results but was causing a crash.
