### ISSUE TITLE
RunInfo block per Step

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#70]
Not every step should be run with the same same parameters that we put in our RunInfo block (for example, NumMPI, runQSUB, expectedTime, etc).

At some point (possibly when/if RAVEN moves to a client-based mode), it would be smart to have the option to designate run information for each Step instead of globally.

As per a team discussion April 4, 2016, we considered that a code-wide restart capability might offer the first step towards a step-handling-based RAVEN operation, where a RAVEN-master determines how each RAVEN step should be treated in terms of parallel operation.  MPI-QSUB can be used to submit individual long-running jobs, while internal parallel can be used for evaluating ROMs and such.  The "master" then reconstructs objects from the restart files created by a finished step to begin the next step in the calculation.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
archived
