### ISSUE TITLE
Expand restart-from-CSV coverage

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#73]
There are some difficulties with importing from CSV to creating Point, History, and HistorySet data objects that are then used for restarting samplers.  These should be overcome.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by maljovec** [comment]
@PaulTalbot-INL, does #231 have any relevance to this issue? I was searching for issues related to CSVs. If we can close multiple issues with one PR, it would be helpful.

**Comment by PaulTalbot-INL** [comment]
I think it is, yes.  This is a transfer from [gitlab](https://hpcgitlab.inl.gov/idaholab/raven/issues/257) that further points to a [merge request](https://hpcgitlab.inl.gov/idaholab/raven/merge_requests/296) where restarts for PointSets loaded from CSV were touched up, but I bailed on HistorySets because it was more trouble than it was worth.

It's quite possible the work you're doing will fix the issue, which is loading from a History CSV then restarting a sampler with the data.
