### ISSUE TITLE
Manual entry for HS2PS postprocessor 

### ISSUE THREAD

**Issue by jchen56** [idaholab/raven#737]
--------
Issue Description
--------
##### What did you expect to see happen?
Manual entry for HS2PS postprocessor: The input for this method should be

    <PostProcessor name="snapshot" subType="InterfacedPostProcessor">
      <method>HS2PS</method>
      <pivotParameter>time</pivotParameter>
    </PostProcessor>

##### What did you see instead?
In the raven manual, this method is listed as HSPS, instead of HS2PS. Further, in the Interfaced post processor section of the manual, there're two entries for HSPS, with different contents.

##### Do you have a suggested fix for the development team?
An update on this section of the manual would be helpful. Also this feature should be included in future workshops, although not necessarily important for a hands-on session.

The section for interfaced post processors in the manual don't make much sense to me. They either don't have examples or lack information on how those parameters actually work within the code. The examples are also different from the test inputs in the devel branch or long outdated.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed...

Closure approved via #1197
