### ISSUE TITLE
Request for a post processor of combining HistorySet into PointSet

### ISSUE THREAD

**Issue by jchen56** [idaholab/raven#738]
--------
Issue Description
--------
##### What did you expect to see happen?
A post processor that combines HistorySet into PointSet that does not apply any operator but rather just gather all the points in a HistorySet and combine them into a PointSet.

##### Do you have a suggested fix for the development team?
The HStoPSOperator should be expanded so that it each history in a HistorySet dataObject is decomponsed as a collection of points

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by mandd** [comment]
I am trying to understand: what is the problem about this post-processor?

**Comment by jchen56** [comment]
No I can't find a post processor to combine HistorySet into a PointSet. The test input test_HS2PS.xml doesn't make much sense to me and there's no documentation for it in the manual. The idea of combining HistorySet into PointSet is stacking all the points over time into one PointSet. Yet the HS2PS method doesn't seem to do that.

**Comment by jchen56** [comment]
I have checked the HStoPSOperator PP. It only supports operator or row type processing, instead of collecting all the points in a HistorySet. I've used a workaround and gathered all the points from the printed HistorySet into one CSV using a python script. I heard that a similar tool for combining printed history csv files is included in RAVEN but this could be modified into a feature.

**Comment by mandd** [comment]
What we can do is to add a functionality to either of the two PPs to satisfy your needs.
I added a comment in the issue description: let me know if this sounds good to you.

**Comment by jchen56** [comment]
I'd say the functionality is great. Moreover, I would suggest keeping time as one of the variables in the PointSet generated by such functionality.

**Comment by wangcj05** [comment]
archived
