### ISSUE TITLE
Files "type" in two places but not linked

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#74]
Currently, the "type" of a Files object is specified both in the Files node and in the Steps when it is listed as an Input or otherwise.  

The "type" in the Files node refers to a handle usable by the CodeInterface to distinguish files.

The "type" in the Steps is unused still.  We should decide what use we want this to have.  It seems like the type of Files would make most sense, so for instance,
```
<Files>
  <Input name='myfile'>myfile.txt</Input>
</Files>
...
<Steps>
  <MultiRun name='run'>
    <Input class='Files' type='Input'>myfile</Input>
    ...
  </MultiRun>
</Steps>
```

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
closed, #96 can cover this issue.
