### ISSUE TITLE
RrR inner run fail results in Optimizer crash

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#745]
--------
Issue Description
--------
When running HYBRID cases on the HPC, occasionally (and not at the same run every try) the Optimizer will fail in a gradient evaluation iteration with the error:
```
  File "/home/talbpaul/projects/hybrid/raven/framework/Optimizers/SPSA.py", line 293, in localEvaluateGradient
    lossDiff = mathUtils.diffWithInfinites(pert['output'],opt['output'])
KeyError: u'output'
```
In particular, the "opt" point (not the "pert" point) only has the input space, and not the output space.

This seems to be because one of the inner runs in RrR failed, but that failure doesn't trigger as a failure when returning to the outer RrR run.

This can't cause wrong results, but it does cause crashes.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed...

Closure approved via #1163 (New optimization class)
