### ISSUE TITLE
Improved CTF (Cobra-TF) Interface

### ISSUE THREAD

**Issue by alptezbasaran** [idaholab/raven#749]
--------
Issue Description
--------
##### What did you expect to see happen?

Three different input files should have been modified with for each new sample. 
All the output data was supposed to be converted into csv files.

##### What did you see instead?

There is no surface number definition in the parser, also some geometry types are missing. Only the main input can be modified with new samples. Auxiliary  input files (vuq_param.txt and vuq_mult.txt) cannot be changed by RAVEN.

##### Do you have a suggested fix for the development team?

Yes, pull request corresponding to solve this issue is submitted. (#750 )

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

N/A

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

Reviewed by Congjian Wang @wangc on 8/10/2018.

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Issue closure checklist is satisfied.
