### ISSUE TITLE
Code using input files in other directories not thread safe

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#753]
--------
Issue Description
--------
When a Code has input files taken from another directory, it uses that path to write the input files for each instance of the Code run.

The problem comes when this path is outside the working directory; then all the parallel runs share the same path for that folder.

### Example
I have an input file in directory `main` called `input.xml` and it uses `.` as a working directory.  I run `input.xml` with a batch size greater than one.  My MultiRun step is called `doSample`.

The Step creates the directory `main/doSample`, then each run creates a subfolder with the number of the run, creating the following input structure:
```
main/
  input.xml
  doSample/
       1/
       2/
```
This is as expected.

Now to complicate things, say my Code model takes its input files from a neighboring directory of `main`, called `common`.  Its input file is `in.i`:
```
common/
    in.i
main/
    input.xml
    doSample/
        1/
        2/
```
The path listed in the input for this  `in.i` input file is `../common/in.i`.

When the Code goes to write this file for run 1, the path starts at `main/doSample/1`, making the full path `main/doSample/1/../common/in.i`, which absolute path is `main/doSample/common/in.i`.  Note there is no reference to the folder `1` in the absolute path.  Thus, when it writes the input for `2`, it overwrites all the same files in `common`.

If `1` happens to be reading a file in `common` while `2` is writing, you get bad behaviors and often a crash.

We should either try to find a thread-safe solution, or at least detect such a pathing problem and prevent a user from making this workflow error.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or improvement?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
In discussing with @wangcj05 we came up with a few ideas:
- Don't use relative paths within RAVEN (but let the user input them), always convert to absolute.
- Forbid using paths as part of the variable name, and offer a "path" attribute to give alternate location.
- Individual code interfaces can potentially provide tools to not copy some files that are not perturbed, saving some effort (for example, in raven-running-raven the external model files could be left in their original path and not treated as inputs)

**Comment by alfoa** [comment]
It was supposed to be closed
