### ISSUE TITLE
Why does OpenModelica pass the xsd test? 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#76]
--------
Issue Description
--------
##### What did you expect to see happen?
An error in the validation test, or an error in:
```
xmllint --schema developer_tools/XSDSchemas/raven.xsd tests/framework/CodeInterfaceTests/test_OpenModelica_code_interface.xml 
```

CodeInterfaceTests/test_OpenModelica_code_interface.xml has:
```<Code name="BouncingBall" subType="OpenModelica">```
but the xsd has:
```    
    <xsd:simpleType  name="CodeModelType">
        <xsd:restriction   base="xsd:string">
            <xsd:enumeration value="GenericCode" />
            <xsd:enumeration value="Relap5" />
            <xsd:enumeration value="RAVEN" />
        </xsd:restriction>
    </xsd:simpleType>
```
Why is this not failing?

##### What did you see instead?
```tests/framework/CodeInterfaceTests/test_OpenModelica_code_interface.xml validates```

##### Do you have a suggested fix for the development team?
Check that subType is actually being checked in the XSD, or modify the XSD.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by joshua-cogliati-inl** [comment]
Answer, because this is how ModelsData is defined in Models.xsd:
```
    <xsd:complexType name="ModelsData">
        <xsd:sequence>
            <!--xsd:element name="Dummy"         type="DummyModel"    minOccurs="0" maxOccurs="unbounded"/>
             <xsd:element name="ExternalModel" type="ExternalModel" minOccurs="0" maxOccurs="unbounded"/-->
            <xsd:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
```

Basically, the xsd allows anything in Models.

This could be fixed by fixing Models.xsd, but since this is minor, probably it can just be fixed as part of the InputData work.

**Comment by alfoa** [comment]
It will be addressed as part of the InputData system. It can be closed
