### ISSUE TITLE
Error in saveInDB step of runLS.xml case from raven_folder/doc/workshop folder

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#780]
--------
Issue Description
--------
##### What did you expect to see happen?
workshop case to run successfully 

##### What did you see instead?

```
Email from an user:

Hello RAVEN Users,

I'm having trouble to run the workshop case runLS available from raven_folder/doc/workshop (see attached).

For this case, 4 steps are supposed to be executed: MCRun, adaptive, plot, and saveInDB. The first three runs smoothly while the forth one produces the following error:

Traceback (most recent call last):
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Driver.py", line 281, in <module>
    raven()
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Driver.py", line 234, in raven
    simulation.run()
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Simulation.py", line 798, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Steps.py", line 312, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Steps.py", line 916, in _localTakeAstepRun
    outputs[i].addRealization(rlz)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/Databases.py", line 248, in addRealization
    self.database.addGroup(rlz)
  File "/home/av_ale/IdahoLab/RAVEN-Master_branch/framework/h5py_interface_creator.py", line 189, in addGroup
    groupName = str(rlz.get("prefix")[0] if not isinstance(rlz.get("prefix"),basestring) else rlz.get("prefix"))
TypeError: 'NoneType' object has no attribute '__getitem__'

Any idea why this happens?

Thank you in advance,
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Email is not required, since a new PR with the workshop update is created #797, and an email will be proposal in that PR.
