### ISSUE TITLE
MOOSE Input Drops Text After Second '='

### ISSUE THREAD

**Issue by elementx54** [idaholab/raven#792]
--------
Issue Description
--------
##### What did you expect to see happen?
I expected `function = 'alpha := total_volume * current_power_density * (1 - tau); beta := tau * current_power_density; alpha * beta'` in my moose input file to be parsed to the same thing when it spawned all the jobs.

##### What did you see instead?
Instead it dropped all the text after the second `=` putting in the new input file `function = 'alpha :` causing the run to error.

##### Do you have a suggested fix for the development team?
I do! Expect a merge request soon. :smiley: And it is running now with the fix.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
No email needed since it only crashes if the problem is discovered instead of giving an incorrect value.

**Comment by PaulTalbot-INL** [comment]
Defect is fixed, and not only does the implemented test check the fix, it furthermore checks the entire mechanics for the MOOSE input parser writing. Approved for closure via merging #794.
