### ISSUE TITLE
MOOSE Input Incorrect Parse of Multi-line String

### ISSUE THREAD

**Issue by elementx54** [idaholab/raven#794]
--------
Issue Description
--------
##### What did you expect to see happen?
In my MOOSE input file I have a multi-line string:
```
type = ParsedFunction
function = 'rT := temperature / 1000.0;
            cp_f := 52.1743 + 87.951 * rT - 82.2411 * pow(rT, 2) + 31.542 * pow(rT, 3) - 2.6334 * pow(rT, 4) - 0.7139 * pow(rT, -2);
            cp_rho_fuel := 1.0e-6 * rho_fuel / M_fuel * cp_f;
            cp_rho_graphite := 1e-9 * rho_graphite / (11.07 * pow(temperature, -1.644) + 0.0003688 * pow(temperature, 0.02191));
            rho_UO2 * cp_rho_fuel + (1 - rho_UO2) * cp_rho_graphite'
```
It treats each line as if it was not part of the string. This could be a problem if someone was changing a matrix of values using Raven.

##### What did you see instead?
The new input spawned by Raven had: (the first line had the problem in #792 )
```
function = 'rT :
type = ParsedFunction
cp_f : = 52.1743 + 87.951 * rT - 82.2411 * pow(rT, 2) + 31.542 * pow(rT, 3) - 2.6334 * pow(rT, 4) - 0.7139 * pow(rT, -2);
cp_rho_fuel : = 1.0e-6 * rho_fuel / M_fuel * cp_f;
cp_rho_graphite : = 1e-9 * rho_graphite / (11.07 * pow(temperature, -1.644) + 0.0003688 * pow(temperature, 0.02191));
rho_UO2 * cp_rho_fuel + (1 - rho_UO2) * cp_rho_graphite'
```
It doesn't preserve the order (which is important for a multi-line string) and some other lines in the block can end up between the lines that were part of the string.

##### Do you have a suggested fix for the development team?
Not really, I suggest to check for an open `'` and then end at the next `'`. I did find a work around: I could put the multi-line string on one line and it works (with the fix in #793 ). So perhaps taking a multi-line string and converting it to a single line string, first could work.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed.

An email should be sent.

Closure approved via PR  #1204
