### ISSUE TITLE
update workshop materials 

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#796]
--------
Issue Description
--------
##### What did you expect to see happen?
The workshop should be up to date.

EDIT @alfoa : All the inputs in the workshop material should be part of our regression test system.

##### What did you see instead?
It is quite old now

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@wangcj05 I added the following sentence as well:
```All the inputs in the workshop material should be part of our regression test system.```

**Comment by alfoa** [comment]
Closure checklist passed....

**Comment by wangcj05** [comment]
Email regarding this is sent to raven users, and the proposed email is:
```
Dear Users,
We recently realized that some tests for the RAVEN workshops are outdated and can not be executed. This issue has been resolved with PR#800 and is the modifications are currently available in the devel branch. Now all the tests under raven/doc/workshop are tested in the regression test systems. In this case, all the tests will be updated with any changes we made in the our devel branch.

Please let us know if you have any questions regarding these changes. 
```

**Comment by PaulTalbot-INL** [comment]
Could we put a more positive spin on that, or did it already send?

**Comment by wangcj05** [comment]
I have sent it out already.

________________________________
