### ISSUE TITLE
Improve RAVEN input handling 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#84]
This task is to improve RAVEN's input handling.

Goals:

Provide enough information in the class to be able to:

 *   Generate a GUI (like Peacock) from the data.
 *   Check that the input is valid
 *   Generate an xsd file.

The information should be generated statically (from static methods). The suggested method is to create functions in each class that have the correct data, and use that data to generate the needed information.

This is being done through the utils.InputData system which needs to be extended to more classes.

Originally: https://hpcgitlab.inl.gov/idaholab/raven/issues/611

We need to re-standardize the objects that are using the Input Data following the instructions reported in https://github.com/idaholab/raven/wiki/input-data
. An example is the Sampler, where the InputData is used within the read more XML

**Comment by joshua-cogliati-inl** [comment]
After Input improvements #395 goes in, PostProcessors, Steps, Distributions and DataObjects use the input handling system.  

Samplers use the input handling system to parse the input, but generally still use reading the xml to find the data inside.

If you want to check if a specific class use it, check to see if there is a readMoreXML function.  If there is, then it should use something like:
```
  def _readMoreXML(self,xmlNode):
    """
      Function to read the xml input block.
      @ In, xmlNode, xml.etree.ElementTree.Element, xml node
      @ Out, None
    """
    paramInput = self.getInputSpecification()()
    paramInput.parseNode(xmlNode)
    self._handleInput(paramInput)
```
if the input handling system is being used.

There are several subsystems not yet using the input handling system.   These include the Databases, Models, Files and RunInfo.  The Samplers need to use the input handling system for reading in data and not just parse the data.  Note that RunInfo and Models allow plugins to handle raw xml, so either the interface needs to be changed for the plugins, or a way to keep track of the original xml is needed.

**Comment by wangcj05** [comment]
@idaholab/raven-team Hello All, I think this is the issue for the InputData, let's push to further employment of InputData of our development. Please keep update this issue during the future development.

**Comment by PaulTalbot-INL** [comment]
I don't see a list of where it's not in place yet; does that information exist? It will be challenging to carve out other work to include that without knowing what needs to be targeted.

**Comment by wangcj05** [comment]
> I don't see an updated list of where it's not in place yet; does that information exist? It will be challenging to carve out other work to include that without knowing what needs to be targeted.

I will check our code, and list the things that we need to convert to use InputData.
