### ISSUE TITLE
Multi-colored line plots 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#85]
We can adapt the colorline method described [here](http://stackoverflow.com/questions/8500700/how-to-plot-a-gradient-color-line-in-matplotlib) in order to provide more robust line plots that can match the user expectations when a dataset of variable color parameter is used.

From: https://hpcgitlab.inl.gov/idaholab/raven/issues/720 and https://hpcgitlab.inl.gov/idaholab/raven/issues/655

**Comment by wangcj05** [comment]
archived
