### ISSUE TITLE
Distribution input files are relative to running directory rather than input directory

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#86]
The distribution input files find the files relative to the running directory rather than the working directory:
```raven/tests$ ../raven_framework framework/test_distributionCustom1D.xml``` fails but ```raven/tests/framework$ ../../raven_framework test_distributionCustom1D.xml``` works. 

From: https://hpcgitlab.inl.gov/idaholab/raven/issues/658

See also #65

**Comment by wangcj05** [comment]
I think this is resolved by PR #1870
