### ISSUE TITLE
utils.py depends on numpy and six

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#861]
--------
Issue Description
--------
##### What did you expect to see happen?
utils.py not to import numpy or six

##### What did you see instead?
```
#Do not import numpy or scipy or other libraries that are not
# built into python.  Otherwise the import can fail, and since utils
# are used by --library-report, this can cause diagnostic messages to fail.
import bisect
import sys, os, errno
import inspect
import subprocess
import platform
import copy
import numpy
import six
from difflib import SequenceMatcher
import importlib
```

##### Do you have a suggested fix for the development team?
move the functions that use numpy and six to mathUtils.py or rewrite them not to use six and numpy

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.
Try running ```./run_tests --library-report``` on a system without six or numpy.  It should work but it doesn't

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@joshua-cogliati-inl @wangcj05 @PaulTalbot-INL 

I am a bit confused about this issue. If we run the --library_report I agree we should be able to get info even if libraries such as numpy or scipy are present (it is actually the goal of the report to figure this out), but if we run the run_tests with the --library_report we always run the establish_conda script that tries to load the raven_libraries and errors out if not found. The only way to avoid this was (if I recall correctly) to specify the --no-conda stuff that I can not find anymore (or probably I am confusing with the fix I pushed for the compilation only).

**Comment by PaulTalbot-INL** [comment]
As I recall, the library report fails if the active python doesn't have the libraries imported by `utils.py`. This could come up when a user is trying to run the report but conda didn't install libraries correctly for some reason, right? Then the library report could still usefully show what's present and what's missing.

That's what I recall from talking about it years ago, I hope Josh can correct me where I'm wrong.

**Comment by alfoa** [comment]
@joshua-cogliati-inl @PaulTalbot-INL  is still valid? and if so, what's next?

**Comment by PaulTalbot-INL** [comment]
`utils.utils` does not appear to import six or numpy currently.

**Comment by joshua-cogliati-inl** [comment]
This has been fixed, but the pull request did not close it.  It was a task, not an issue so no email or regression test is needed.  Closing.
