### ISSUE TITLE
MOOSE Interface: Changing Single Value in String Vector

### ISSUE THREAD

**Issue by elementx54** [idaholab/raven#868]
--------
Issue Description
--------
##### What did you expect to see happen?
My MOOSE input file has a function that changes a value at the beginning, middle, and end:
```
x = '0 1.0 2.0'
y = '1.8 1.95 2.0'
```
I would like to vary just the first number (1.8) using Raven.

##### What did you see instead?
The MOOSE interface currently has no way of allowing a single value (or multiple values) in a string to be identified as the value to modify.

##### Do you have a suggested fix for the development team?
Perhaps make an interface that takes multiple variables and joins them in a string separated by spaces. Some of the variables could be varying and others could be constant or dependent.  

I have, however, found some work arounds that are a bit complicated. It is possible to form the string using a variable with a `<function>` which returns a string. However, for an optimization problem, that is not possible currently. So for that I've been using an external model to form the string: `self.y_str = "'{0} 1.95 2.0'".format(self.varying[0])` But you have to go into `ExternalModel.py` and add `'str'` to the `self._availableVariableTypes` list. The index `[0]` is necessary as the external model has the varying variable in an array.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
In the past, we will use  ```Mesh|length:3``` to identify  the third element in the moose vector string for variable ```Mesh|length```. However, this capability was no longer work due to lack of maintenance.
