### ISSUE TITLE
Make cluster running interface better 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#89]
The cluster running interface works, but is not designed very well. Now that it has been used for torque, pbsdsh and pbspro with mpiexec, it could be improved. First of all, it is complicated to figure out how to use. Secondly, it passes in simulation, which gives much more access to the plugins than is really needed.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? __N/A__
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __not a defect__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? __not a defect__
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) __not a defect__
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?  __Email has been drafted__
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?  __See #191__

**Comment by alfoa** [comment]
Was supposed to be closed
