### ISSUE TITLE
ARMA preserve CDF

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#899]
--------
Issue Description
--------
Even if the Fourier detrending of a signal is perfect, the variance of the residual signal has often shown a time-dependent behavior. However, the ARMA ROM currently redistributes this variance evenly across all sample points, which results in longer "tails" of the sampled distribution.

This can be mitigated by segmenting the signal into small pieces, but such segmentation makes it impossible to represent outliers in a way that differs from the original signal. For example, if training the ARMA ROM on temperatures for a year, segmenting by day means that if March 4 was hot in the training set, March 4 will likewise be hot throughout all future samples.

Instead, one tail-preserving method is to transform the Fourier-plus-ARMA signal via empirical distribution to fit the distribution of the original data. This will preserve the distribution and behavior of high and low points within the signal and maintain the integrity of the histogram of sampled behaviors.

This new feature should be optional to either include or opt out of.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
issue closure checklist is satisfied.
