### ISSUE TITLE
DET restart

### ISSUE THREAD

**Issue by valkus** [idaholab/raven#921]
--------
Request for proper DET restart.
--------
##### What did you expect to see happen?
We run big DET cases, up to 130000 branches, so we often hit the cluster wall time and we need to restart the same case multiple times. currently we implement the reading of the analysis file tree by the interface checking if there was a successfull previous MAAP run, it takes 2-3 days just to reed the full file tree.

The idea is to be able to restart the analysis from the database, by checking what were the finished branches

##### What did you see instead?
Nothing, we use our poor's man restart.

##### Do you have a suggested fix for the development team?
Implement a proper restart

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by valkus** [comment]
> For bookkeeping, note this issue is a sub-issue of #79.

Thanks Paul, restart can be thought in different ways, restart - meaning adding new points, restart meaning finishing unfinished simulation, fixing errors. For us the last two are of the most importance.

**Comment by wangcj05** [comment]
archived
