### ISSUE TITLE
HDF5 crash for allGroupPath failure to append in the attribute

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#925]
--------
Issue Description
--------
A user reported the following issue with the HDF5

```
Hi to all,

I am trying to create a database with 1024 histories but the process crash with:

RuntimeError: Unable to create attribute (object header message is too large)

The database is generated but it contain 951 histories only. Do you have any suggestion?

The RAVEN version I am using is compiled from the default branch of the 10/28/18.

Please find attached the tail of the raven output log file.

Best Regards,

Paolo
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
No wrong results for the users but just a crash

**Comment by mandd** [comment]
issue closed
