### ISSUE TITLE
feature request for a plot

### ISSUE THREAD

**Issue by waynemorrison** [idaholab/raven#930]
--------
Issue Description

would like to plot the pressures on the y-axis and node number on the x-axis;  I attached a plot that was created with Excel that was created using the data shown below.

0010801:1,time,p_1010000,p_1020000,p_1030000,p_1040000,p_1050000,p_1060000,p_1070000,p_1080000,p_1090000,p_1100000,ProbabilityWeight,prefix,PointProbability,ProbabilityWeight-0010801:1,ProbabilityWeight-0040201:2
3.47229224305e-05,25.0,99219.0,99216.0,99212.0,99209.0,99206.0,99203.0,99200.0,99196.0,99193.0,99190.0,1.0,1,7381.40617557,1.0,1.0
3.83468245857e-05,25.0,99367.0,99365.0,99362.0,99359.0,99357.0,99354.0,99351.0,99349.0,99346.0,99343.0,1.0,2,96090.8097055,1.0,1.0
1.88472227555e-05,25.0,99624.0,99622.0,99621.0,99619.0,99617.0,99616.0,99614.0,99613.0,99611.0,99610.0,1.0,3,205.885414498,1.0,1.0
3.33151302794e-05,25.0,99177.0,99174.0,99171.0,99167.0,99164.0,99160.0,99157.0,99154.0,99150.0,99147.0,1.0,4,2475.99455369,1.0,1.0
3.08815495437e-05,25.0,99588.0,99586.0,99584.0,99583.0,99581.0,99579.0,99577.0,99576.0,99574.0,99572.0,1.0,5,154969.624539,1.0,1.0

--------
##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

The RAVEN xml file is attached.  It plots with an x-axis of time which is not desired.  The desired kind of plot is attached.
[test_converted_json.txt](https://github.com/idaholab/raven/files/2931594/test_converted_json.txt)
![simple_pipe](https://user-images.githubusercontent.com/41389461/53816216-306e6780-3f31-11e9-9671-8f5afd224dee.png)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by waynemorrison** [comment]
plot vs node number (or length) where the node numbers and/or lengths were input.

**Comment by alfoa** [comment]
@waynemorrison Thank you for your feature request. We can create the possibility to have the user to plot using a custom Python file with clear API

**Comment by wangcj05** [comment]
archived, the plot plugin has been developed, and the user can use that feature to create plots.
