### ISSUE TITLE
check definition of V_1 in kurtosis definition 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#94]
In the kurtosis definition in the user guide, it has w_i^2 where I think it should be w_i

Proposed patch:
```
diff --git a/doc/user_guide/statisticalAnalysis.tex b/doc/user_guide/statisticalAnalysis.tex
index 3240974..4c037ba 100644
--- a/doc/user_guide/statisticalAnalysis.tex
+++ b/doc/user_guide/statisticalAnalysis.tex
@@ -197,7 +197,7 @@ where:
 \begin{itemize}
   \item $w_{i}$ is the weight associated with the sample $i$
   \item $n$ are the total number of samples
-  \item $V_{1} = \sum_{i=1}^{n} w_{i}^{2}$
+  \item $V_{1} = \sum_{i=1}^{n} w_{i}^{1}$
   \item $V_{2} = \sum_{i=1}^{n} w_{i}^{2}$
   \item $V_{3} = \sum_{i=1}^{n} w_{i}^{3}$
   \item $V_{4} = \sum_{i=1}^{n} w_{i}^{4}$.

```

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? N/A
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. Typo in the theory manual, no impact on users
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? Fixed
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) This a typo in the manual, no impact on the code.
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
No impact on users.
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? No.
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
Merge request #303 fixed this issue.
