### ISSUE TITLE
Edit in the User Guide Chap 1-7

### ISSUE THREAD

**Issue by JiaZhou-PU** [idaholab/raven#950]
--------
Issue Description
--------
User guide reference scripts in all chapters generate figures with the wrong colors(All figures).

Reference subchapters cannot be linked in a different chapter. (P.54 p3 ...) 

The batch size number in the text is different from the number in the script(P.55 p2 ...).

Some description is confusing (P55 " run **simultaneously.** Every time a simulation ends, a new one is launched.") and redundant (P25 line 1 and line 2)
 
Some reference scripts have the unused subclass (P52 <Files> ...output_1... output2...</Files>)

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved for closure via #951.
