### ISSUE TITLE
Default to Python 3

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#953]
--------
Issue Description
--------
##### What did you expect to see happen?
RAVEN to use Python3 unless explicitly asked for python2

##### What did you see instead?
Python 2 is the default.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Closing this will require a notification to the user group; a draft of it can be included here or elsewhere.

**Comment by joshua-cogliati-inl** [comment]
Draft email (Paul, can you check that this sounds reasonable?):
With the merge of https://github.com/idaholab/raven/pull/954 RAVEN now uses Python 3 by default.
The command:
scripts/establish_conda_env.sh --install 
will now install Python 3 instead of Python 2
In order to use Python 2 instead of Python 3, the command:
scripts/establish_conda_env.sh --install --py2 
needs to be used when installing.

The old makefiles have been removed.  The script:
build_raven
can be used to build raven, and the script
clean_raven
can be used to remove the compiled files.

The environmental variables CHECK_PYTHON3 and CROW_USE_PYTHON3 are no longer needed.
If you are not using the establish_conda_env.sh you may need to define the environmental variable PYTHON_COMMAND if python is not the command you need for running python (for example this may be needed if you are using pip instead of conda for the libraries and python3 is what you are using.)

Let us know if you have any issues.

**Comment by PaulTalbot-INL** [comment]
Looks good to me. At most, adding the link to the "updating raven" page as a final thought/summary of actions needed might be useful.

Approved to close via #954.

**Comment by elementx54** [comment]
It might be a good idea to change command line input into a different font in the email alert to distinguish it from the text describing what it does.

**Comment by joshua-cogliati-inl** [comment]
Email sent.
