### ISSUE TITLE
The Step entities does not check for the type of the class 

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#96]
In 015df149ea59ba5828e604259010313bdd9762ff we have in tests/framework/ensembleModelTests/test_ensemble_model_linear_threading_with_time_series.xml:

```
<Input class="DataObjects" type="PointSet">thermalConductivityComputationContainer</Input>
```

```
<TargetEvaluation class="DataObjects" type="HistorySet">thermalConductivityComputationContainer</TargetEvaluation>
```

```
<HistorySet name="thermalConductivityComputationContainer">
```

This should error out because it is PointSet in one place and HistorySet in another. thermalConductivityComputationContainer should be a HistorySet.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [ ] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment]
related issue #74
