### ISSUE TITLE
Modifying plots in DataMining Example

### ISSUE THREAD

**Issue by pralhadburli** [idaholab/raven#964]
--------
Issue Description
--------
##### What did you expect to see happen?
Modified the grid space, axis range, and labels for the plots and wanted to improve plot aesthetics.

##### What did you see instead?
Axis labels do not appear correctly or are hidden under plots, for instances where a grid space has more than one plot.

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
@pralhadburli if you could attach a brief XML example of what you tried, and maybe even examples of how it didn't work, that could be quite helpful. Thanks!

**Comment by pralhadburli** [comment]
In the figure below, the axis labels for the plots do not appear correctly. The spacing between the plots needs adjustment.
![1-PlotKMeans1_dataMining-dataMining](https://user-images.githubusercontent.com/46587653/56387974-07edb480-61e3-11e9-8224-e0593849370f.png)

In the plot below, the labels appear as x, y, and z. 
![1-PlotLabels_dataMining](https://user-images.githubusercontent.com/46587653/56387975-07edb480-61e3-11e9-915c-226745c2b444.png)

Including the following lines with the <plot> node in the code does not address the problem.
          <xlabel>velocity</xlabel>
          <ylabel>angle</ylabel>
          <zlabel>range</zlabel>

I am unable to attach my .xml file here.
