### ISSUE TITLE
Grid Sampler Crashed with Integer Grids

### ISSUE THREAD

**Issue by wangcj05** [idaholab/raven#973]
--------
Issue Description
--------
##### What did you expect to see happen?
Raven should run without crash

##### What did you see instead?
Crashed and the pdf generation complains the type.
```
jianw@lemhi1 stationary_cracks]$ cat raven_qsub.e73554
which: no conda in (/apps/moose/stack/mvapich-2.3.1_gcc-8.2.0/bin:/apps/moose/stack/gcc-8.2.0/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/bin:/opt/dell/srvadmin/bin)
/home/jianw/projects/raven/framework/contrib/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/jianw/.conda/envs/raven_libraries/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "/home/jianw/projects/raven/framework/Driver.py", line 285, in <module>
    raven()
  File "/home/jianw/projects/raven/framework/Driver.py", line 238, in raven
    simulation.run()
  File "/home/jianw/projects/raven/framework/Simulation.py", line 780, in run
    stepInstance.takeAstep(stepInputDict)
  File "/home/jianw/projects/raven/framework/Steps.py", line 312, in takeAstep
    self._initializeStep(inDictionary)
  File "/home/jianw/projects/raven/framework/Steps.py", line 242, in _initializeStep
    self._localInitializeStep(inDictionary)
  File "/home/jianw/projects/raven/framework/Steps.py", line 606, in _localInitializeStep
    newInput = self._findANewInputToRun(inDictionary[self.samplerType], inDictionary['Model'], inDictionary['Input'], inDictionary['Output'])
  File "/home/jianw/projects/raven/framework/Steps.py", line 722, in _findANewInputToRun
    found,newInp = sampler.generateInput(model,inputs)
  File "/home/jianw/projects/raven/framework/Samplers/Sampler.py", line 804, in generateInput
    self.localGenerateInput(model,oldInput)
  File "/home/jianw/projects/raven/framework/Samplers/Grid.py", line 205, in localGenerateInput
    self.inputInfo['SampledVarsPb'][key] = self.distDict[varName].pdf(self.values[key])
  File "/home/jianw/projects/raven/framework/Distributions.py", line 414, in pdf
    returnPdf = self._distribution.pdf(x)
  File "/home/jianw/projects/raven/crow/install/crow_modules/distribution1Dpy3.py", line 466, in pdf
    return _distribution1Dpy3.BasicUniformDistribution_pdf(self, x)
TypeError: in method 'BasicUniformDistribution_pdf', argument 2 of type 'double'
```

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __it will cause crash, but not wrong results__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
Approved for closure via #1008. No user-facing email is needed as this caused a crash, and is not of general interest.
