### ISSUE TITLE
Data Object error message

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#981]
--------
Issue Description
--------
Running the BasicStatistics post processor with more variables listed in the DataObject than produced by the post-processor, RAVEN crashes with an incomprehensible error message.

=> Please add a better check and clarify in the error message that it's something wrong with the variables listed in the DataObject.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
@AaronEpiney I created a test where the DataObject was containining a couple of variables not produced by the BasicStatistics. The error I get is the following:
```
(    7.12 sec) PointSet                 : ERROR           -> Provided realization does not have all requisite values for object "analyticalTest_basicStatPP": "vc_z"
KeyError: u'Provided realization does not have all requisite values for object "analyticalTest_basicStatPP": "vc_z"'
```

Do you get a different error?And if so, can you add it and/or add an input to replicate the problem?

**Comment by wangcj05** [comment]
This happens when you have the same variable in both input and output of DataObjects, for example:
```
<HistorySet name="hist">
  <Input>x,y</Input>
  <Output>y,z</Output>
</HistorySet>
```
The error will be:
```
Using param spec "DataSet" to read XML node "HistorySet.
Using param spec "DataSet" to read XML node "HistorySet.
Life is beautiful my friends. Do not waste it!
Traceback (most recent call last):
  File "/Users/wangc/projects/raven/framework/Driver.py", line 285, in <module>
    raven()
  File "/Users/wangc/projects/raven/framework/Driver.py", line 238, in raven
    simulation.run()
  File "/Users/wangc/projects/raven/framework/Simulation.py", line 780, in run
    stepInstance.takeAstep(stepInputDict)
  File "/Users/wangc/projects/raven/framework/Steps.py", line 315, in takeAstep
    self._localTakeAstepRun(inDictionary)
  File "/Users/wangc/projects/raven/framework/Steps.py", line 469, in _localTakeAstepRun
    model.collectOutput(finishedJob,output)
  File "/Users/wangc/projects/raven/framework/Models/PostProcessor.py", line 199, in collectOutput
    self.interface.collectOutput(finishedjob,output)
  File "/Users/wangc/projects/raven/framework/PostProcessors/BasicStatistics.py", line 1217, in collectOutput
    output.addRealization(outputRealization)
  File "/Users/wangc/projects/raven/framework/DataObjects/DataSet.py", line 235, in addRealization
    self._collector.append(newData)
  File "/Users/wangc/projects/raven/framework/utils/cached_ndarray.py", line 347, in append
    raise IOError('Tried to add new data to cNDarray.  Need {} entries in array, but got '.format(self.width)+str(entry.shape[0]))
OSError: Tried to add new data to cNDarray.  Need 168 entries in array, but got 169
[wangc][~/projects/raven/tests/framework/PostProcessors/BasicStatistics]> vim time_dep.xml
```
@alfoa

**Comment by wangcj05** [comment]
@alfoa Have you fixed this issue?

**Comment by alfoa** [comment]
Approved for closure by #989 

Checklist passed
