### ISSUE TITLE
ARMA: Signal processing for peaks

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#990]
--------
Issue Description
--------
The ARMA can currently handle a wide variety of input signals.

One it is poorly suited for, however, is intermittent periodic peaks (for example, a relatively flat signal with a singular spike every 25 entries), especially if the peak widths are small (1-2 entries).

In order to capture this punctuating effect, additional development is needed in the ARMA signal processing methods.

Furthermore, the ARMA should probably be renamed to StochasticSignalProcessingHistory or something, since it is expanding beyond just the ARMA algorithm.

This is a high-priority task due to needs in HYBRID program milestones this year.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
In a discussion with @JiaZhou-PU, we came up with an idea for handling the peak behavior, somewhat similar to the zero-filtering but with less discarded data:

For training the data:
 - Split the data into values below and above an arbitrary level (ideally to pick out peaks). This could be split multiple times for multiple bands of peaks, with one band including the residual noise.
 - For each band not including the no-peak band:
   - Record the periodicity of the peaks in this band, making a PDF of them for future sampling.
   - Collapse the parts of the signal containing no information (non-peak portions).
   - Use FFT to discover the applicable peak transform to a user-given coverage.
   - Removing the FFT from the band signal, use the ARMA to train the residual noise in this band.
   - Store the trained ARMA, FFT properties, period histogram, and filter masks for use during sample generation.

For evaluating the data:
 - For each peak-containing band:
    - Sample the ARMA to create "noise" for the peaks
    - Add the Fourier data from the FFT to create full peaks
    - For each filtered original location of the peaks:
      - Sample from the period history to determine the location of the next peak
      - Insert the portion of the peak signal corresponding to each peak into the signal

We found some potential concerns with this process (peak widths, ARMA p and q, appropriate FFT coverage levels) but it should be a good start to addressing this issue.

**Comment by wangcj05** [comment]
archived
