### ISSUE TITLE
Multi-year ARMA

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#991]
--------
Issue Description
--------
For multiple-year stochastic analysis, it would be great for the ARMA to be able to produce as many years as desired per sample. This would make the output of the ARMA three-dimensional: sample, year, and intrayear (e.g. hourly).

This would provide looping over the years of an ARMA within a model and performing some analysis.

Further, the ARMA could take growth factors defining how to change the signal's mean (or other statistics) from year to year.

This is needed for the HYBRID project.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
Closure checklist passed. Closure approved via #992
