### ISSUE TITLE
run_framework_tests anomolies with an existing raven_libraries

### ISSUE THREAD

**Issue by waynemorrison** [idaholab/raven#999]
--------
Issue Description

In a new clone,   with an activated raven_libraries environment which was previously established,
the framework/CodeInterfaceTests/RAVEN/Basic test fails.

--------
##### What did you expect to see happen?
I would expect that all tests would pass, just as when the conda environment for RAVEN was installed with the --install option.

##### What did you see instead?

- Attached is a log of the conda info:

[conda_info.log](https://github.com/idaholab/raven/files/3217415/conda_info.log)

- Attached is a nohup log of the cloning, activation of the raven_libraries environment, and run_framework_tests:

[nohup.log](https://github.com/idaholab/raven/files/3217424/nohup.log)

- Attached is a log of the test_report:

[test_report.log](https://github.com/idaholab/raven/files/3217436/test_report.log)

##### Do you have a suggested fix for the development team?
No.  I think it should be possible to activate an existing raven_libraries, build Raven, and run the framework tests without this issue.    Is the process I am using correct?   This problem does not occur when the --install option with establish_conda_env.sh

##### Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by waynemorrison** [comment]
I ran this with a shell script that performed these steps.   

git clone https://github.com/idaholab/raven.git
cd raven
./scripts/establish_conda_env.sh --load --conda-defs /home/wmorrison/miniconda3/etc/profile.d/conda.sh
conda activate raven_libraries
./build_raven
./run_framework_tests

**Comment by waynemorrison** [comment]
I accidentally closed the issue.  I repopened it.    Regardless of the "CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'." in the nohup.log file, the unexpected results are the same when the commands are issued at the command line, and I can successfully issue the command:  conda activate raven_libraries.    In short, the framework/CodeInterfaceTests/RAVEN/Basic test still fails.

**Comment by alfoa** [comment]
@PaulTalbot-INL and @joshua-cogliati-inl  It looks like this is the same problem @AaronEpiney  experienced. (The warnings reported at the end... so false positive for the failure)

**Comment by PaulTalbot-INL** [comment]
Part of installing RAVEN includes installing the libraries -- using our install procedure. If you install the libraries without the procedure, then the file `.ravenrc` is not created, and we can only guess where conda's functional definitions (`conda.sh`) are located.

Note that sourcing `conda.sh` from within a terminal session does _not_ make those definitions available in bash scripts; it has to be done within the scrips using `conda`, as of `conda 4.5`.

If you want to install the scripts separately, then an appropriate `.ravenrc` file has to be made pointing to both where your conda definitions file is, as well as the name of the conda environment where the libraries are installed. This isn't one of the recommended installation procedures, but it is possible.

**Comment by waynemorrison** [comment]
Paul,

Regarding the .ravenrc file, I cleaned raven, established the conda environment, and have a .ravenrc file in the raven directory…..

which conda
/home/wmorrison/miniconda3/bin/conda

  ./clean_raven
ls .ravenrc
./scripts/establish_conda_env.sh --load --conda-defs /home/wmorrison/miniconda3/etc/profile.d/conda.sh
./build_raven
  ./run_framework_tests
more .ravenrc

CONDA_DEFS = /home/wmorrison/miniconda3/etc/profile.d/conda.sh
RAVEN_LIBS_NAME = raven_libraries


And framework/CodeInterfaceTests/RAVEN/Basic test still fails.  I’m not sure why this particular test is the only one that fails.

**Comment by PaulTalbot-INL** [comment]
That is quite strange. Thanks for bearing with us and reporting back your efforts.

**Comment by wangcj05** [comment]
I believe our recommend approach to install raven libraries is through "./scripts/establish_conda_env.sh --install".  Let's close this issue, if needed, we can reopen it.
